// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import gorm "gorm.io/gorm"

// beforeCreate runs before the SpringBootDefinition is created.
func (s *SpringBootDefinition) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the SpringBootDefinition is updated.
//
// Receiver semantics depend on the GORM call shape; see
// pkg/api/lib/v0/update_helpers.go for the full model. The simplest
// per-field check is:
//   - tpapi_lib.IsFieldChanged(tx, "FieldName"): works under both PATCH
//     and PUT, handles the DB load internally
//
// Lower-level helpers, useful when tpapi_lib.IsFieldChanged doesn't fit:
//   - tpapi_lib.IncomingValues(tx): values being written
//   - tpapi_lib.IsFullReplace(tx): true on PUT (Save shape)
//   - tpapi_lib.IsPartialUpdate(tx): true on PATCH/DELETE (Updates shape)
//
// Import:
//
//	tpapi_lib "github.com/threeport/threeport/pkg/api/lib/v0"
func (s *SpringBootDefinition) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the SpringBootDefinition is deleted.
func (s *SpringBootDefinition) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the SpringBootDefinition is created.
func (s *SpringBootDefinition) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the SpringBootDefinition is updated.
func (s *SpringBootDefinition) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the SpringBootDefinition is deleted.
func (s *SpringBootDefinition) afterDelete(tx *gorm.DB) error {
	return nil
}

// beforeCreate runs before the SpringBootInstance is created.
func (s *SpringBootInstance) beforeCreate(tx *gorm.DB) error {
	return nil
}

// beforeUpdate runs before the SpringBootInstance is updated.
//
// Receiver semantics depend on the GORM call shape; see
// pkg/api/lib/v0/update_helpers.go for the full model. The simplest
// per-field check is:
//   - tpapi_lib.IsFieldChanged(tx, "FieldName"): works under both PATCH
//     and PUT, handles the DB load internally
//
// Lower-level helpers, useful when tpapi_lib.IsFieldChanged doesn't fit:
//   - tpapi_lib.IncomingValues(tx): values being written
//   - tpapi_lib.IsFullReplace(tx): true on PUT (Save shape)
//   - tpapi_lib.IsPartialUpdate(tx): true on PATCH/DELETE (Updates shape)
//
// Import:
//
//	tpapi_lib "github.com/threeport/threeport/pkg/api/lib/v0"
func (s *SpringBootInstance) beforeUpdate(tx *gorm.DB) error {
	return nil
}

// beforeDelete runs before the SpringBootInstance is deleted.
func (s *SpringBootInstance) beforeDelete(tx *gorm.DB) error {
	return nil
}

// afterCreate runs after the SpringBootInstance is created.
func (s *SpringBootInstance) afterCreate(tx *gorm.DB) error {
	return nil
}

// afterUpdate runs after the SpringBootInstance is updated.
func (s *SpringBootInstance) afterUpdate(tx *gorm.DB) error {
	return nil
}

// afterDelete runs after the SpringBootInstance is deleted.
func (s *SpringBootInstance) afterDelete(tx *gorm.DB) error {
	return nil
}
