// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	gorm "gorm.io/gorm"
)

// BeforeCreate is the GORM before-create hook for SpringBootDefinition.
func (s *SpringBootDefinition) BeforeCreate(tx *gorm.DB) error {
	if err := s.beforeCreate(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsBeforeCreate(tx, s)
}

// BeforeUpdate is the GORM before-update hook for SpringBootDefinition.
func (s *SpringBootDefinition) BeforeUpdate(tx *gorm.DB) error {
	if err := s.beforeUpdate(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsBeforeUpdate(tx, s)
}

// BeforeDelete is the GORM before-delete hook for SpringBootDefinition.
func (s *SpringBootDefinition) BeforeDelete(tx *gorm.DB) error {
	if err := s.beforeDelete(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsBeforeDelete(tx, s)
}

// AfterCreate is the GORM after-create hook for SpringBootDefinition.
func (s *SpringBootDefinition) AfterCreate(tx *gorm.DB) error {
	if err := s.afterCreate(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsAfterCreate(tx, s)
}

// AfterUpdate is the GORM after-update hook for SpringBootDefinition.
func (s *SpringBootDefinition) AfterUpdate(tx *gorm.DB) error {
	if err := s.afterUpdate(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsAfterUpdate(tx, s)
}

// AfterDelete is the GORM after-delete hook for SpringBootDefinition.
func (s *SpringBootDefinition) AfterDelete(tx *gorm.DB) error {
	if err := s.afterDelete(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsAfterDelete(tx, s)
}

// BeforeCreate is the GORM before-create hook for SpringBootInstance.
func (s *SpringBootInstance) BeforeCreate(tx *gorm.DB) error {
	if err := s.beforeCreate(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsBeforeCreate(tx, s)
}

// BeforeUpdate is the GORM before-update hook for SpringBootInstance.
func (s *SpringBootInstance) BeforeUpdate(tx *gorm.DB) error {
	if err := s.beforeUpdate(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsBeforeUpdate(tx, s)
}

// BeforeDelete is the GORM before-delete hook for SpringBootInstance.
func (s *SpringBootInstance) BeforeDelete(tx *gorm.DB) error {
	if err := s.beforeDelete(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsBeforeDelete(tx, s)
}

// AfterCreate is the GORM after-create hook for SpringBootInstance.
func (s *SpringBootInstance) AfterCreate(tx *gorm.DB) error {
	if err := s.afterCreate(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsAfterCreate(tx, s)
}

// AfterUpdate is the GORM after-update hook for SpringBootInstance.
func (s *SpringBootInstance) AfterUpdate(tx *gorm.DB) error {
	if err := s.afterUpdate(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsAfterUpdate(tx, s)
}

// AfterDelete is the GORM after-delete hook for SpringBootInstance.
func (s *SpringBootInstance) AfterDelete(tx *gorm.DB) error {
	if err := s.afterDelete(tx); err != nil {
		return err
	}
	return tpapi_v0.ProcessCoreTaggedFieldsAfterDelete(tx, s)
}
