// originally generated by 'threeport-sdk create' for API object
// scaffolding but will not be re-generated - intended for modification

package v0

import tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"

const (
	// DatabaseNone and DatabasePostgres are the values SpringBootDefinition's
	// Database field accepts. Unlike Django, a Spring Boot application does not
	// need a database to start - an embedded one such as H2 is a normal way to
	// run - so none is the default and PostgreSQL is deployed only when asked
	// for.
	DatabaseNone     = "none"
	DatabasePostgres = "postgres"

	// DefaultServerPort is the port Spring Boot serves on unless the project
	// changed server.port.
	DefaultServerPort = 8080

	// DefaultHealthPath is where Spring Boot Actuator exposes health.
	DefaultHealthPath = "/actuator/health"
)

type SpringBootDefinition struct {
	tpapi_v0.Common         `swaggerignore:"true" mapstructure:",squash"`
	tpapi_v0.Reconciliation `mapstructure:",squash"`
	tpapi_v0.Definition     `mapstructure:",squash"`

	// The container image for the Spring Boot application. A Spring Boot app is
	// packaged as an executable jar that the project builds itself, so there is
	// no canonical public image and the module cannot deploy anything without
	// one.
	Image *string `validate:"required" gorm:"not null"`

	// The Spring profiles the application runs with, e.g. postgres,prod. Passed
	// through as SPRING_PROFILES_ACTIVE. Spring reads this as a comma separated
	// list and the module does not interpret it.
	Profile *string `validate:"optional"`

	// The port the application serves on. Spring Boot defaults to 8080 and the
	// Service has to agree with whatever server.port the image is built with.
	ServerPort *int `validate:"optional" gorm:"default:8080"`

	// Options passed to the JVM through JAVA_TOOL_OPTIONS, e.g. -Xmx512m. The
	// JVM sizes its heap from the container's memory limit on its own, so this
	// is for the cases where that default is wrong rather than something every
	// application needs to set.
	JavaOpts *string `validate:"optional"`

	// The environment type used to determine config settings for a Spring Boot
	// definition.
	Environment *string `validate:"optional" gorm:"default:dev"`

	// The number of pod replicas to deploy for the Spring Boot app.
	Replicas *int `validate:"optional"`

	// The database to deploy alongside the application: none or postgres.
	// Unlike Django, Spring Boot does not require one - an application can run
	// on an embedded database - so this defaults to none and the module only
	// deploys PostgreSQL when it is asked to.
	Database *string `validate:"optional" gorm:"default:none"`

	// The HTTP path the kubelet probes to decide the application is up.
	// Defaults to Spring Boot Actuator's health endpoint, which is what an
	// application that includes the actuator dependency exposes. An image
	// without the actuator has to point this somewhere that answers.
	HealthPath *string `validate:"optional" gorm:"default:/actuator/health"`

	// The Kubernetes workload definition carrying the manifests this module
	// generates for the Spring Boot app and its database. The relationship tag
	// has the API create the attached object reference, so the workload
	// definition cannot be deleted while this definition still refers to it.
	KubernetesWorkloadDefinitionID *uint `validate:"optional" relationship:"owns"`

	SpringBootInstances []*SpringBootInstance `validate:"optional,association"`
}

type SpringBootInstance struct {
	tpapi_v0.Common         `swaggerignore:"true" mapstructure:",squash"`
	tpapi_v0.Reconciliation `mapstructure:",squash"`
	tpapi_v0.Instance       `mapstructure:",squash"`

	// When using a DomainName, the subdomain to use to reach the Spring Boot
	// instance.
	SubDomain *string `validate:"optional"`

	// The Kubernetes runtime to deploy this instance to. When unset the module
	// falls back to the default runtime, so a user with one cluster does not
	// have to name it.
	KubernetesRuntimeInstanceID *uint `validate:"optional" relationship:"requires"`

	// The Kubernetes workload instance deployed from this definition's workload
	// definition.
	KubernetesWorkloadInstanceID *uint `validate:"optional" relationship:"owns"`

	SpringBootDefinitionID *uint `validate:"required" gorm:"not null"`
}
