// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	"encoding/json"
	"fmt"
	api "github.com/threeport/threeport/pkg/api/v0"
	notifications "github.com/threeport/threeport/pkg/notifications/v0"
	"time"
)

const (
	ObjectTypeSpringBootDefinition string = "SpringBootDefinition"
	ObjectTypeSpringBootInstance   string = "SpringBootInstance"

	PathSpringBootDefinitionVersions = "/threeport-io/spring-boot-definitions/versions"
	PathSpringBootDefinitions        = "/threeport-io/v0/spring-boot-definitions"
	PathSpringBootInstanceVersions   = "/threeport-io/spring-boot-instances/versions"
	PathSpringBootInstances          = "/threeport-io/v0/spring-boot-instances"
)

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (sbd *SpringBootDefinition) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        sbd,
		ObjectVersion: sbd.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", sbd, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (sbd *SpringBootDefinition) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &sbd); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (sbd *SpringBootDefinition) GetId() uint {
	return *sbd.ID
}

// GetType returns the object type.
func (sbd *SpringBootDefinition) GetType() string {
	return "SpringBootDefinition"
}

// GetVersion returns the version of the API object.
func (sbd *SpringBootDefinition) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (sbd *SpringBootDefinition) GetFullyQualifiedType() string {
	return "threeport.io/v0.SpringBootDefinition"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (sbd *SpringBootDefinition) ScheduledForDeletion() *time.Time {
	return sbd.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on SpringBootDefinition.
func (s *SpringBootDefinition) RelationshipTaggedForeignKeys() []api.RelationshipTaggedForeignKey {
	return []api.RelationshipTaggedForeignKey{{
		FieldName:    "KubernetesWorkloadDefinitionID",
		ObjectID:     s.KubernetesWorkloadDefinitionID,
		ObjectType:   new(api.KubernetesWorkloadDefinition).GetFullyQualifiedType(),
		Relationship: api.RelationshipOwns,
	}}
}

// NotificationPayload returns the notification payload that is delivered to the
// controller when a change is made.  It includes the object as presented by the
// client when the change was made.
func (sbi *SpringBootInstance) NotificationPayload(
	operation notifications.NotificationOperation,
	requeue bool,
	creationTime int64,
) (*[]byte, error) {
	notif := notifications.Notification{
		CreationTime:  &creationTime,
		Object:        sbi,
		ObjectVersion: sbi.GetVersion(),
		Operation:     operation,
	}

	payload, err := json.Marshal(notif)
	if err != nil {
		return &payload, fmt.Errorf("failed to marshal notification payload %+v: %w", sbi, err)
	}

	return &payload, nil
}

// DecodeNotifObject takes the threeport object in the form of a
// map[string]interface and returns the typed object by marshalling into JSON
// and then unmarshalling into the typed object.  We are not using the
// mapstructure library here as that requires custom decode hooks to manage
// fields with non-native go types.
func (sbi *SpringBootInstance) DecodeNotifObject(object interface{}) error {
	jsonObject, err := json.Marshal(object)
	if err != nil {
		return fmt.Errorf("failed to marshal object map from consumed notification message: %w", err)
	}
	if err := json.Unmarshal(jsonObject, &sbi); err != nil {
		return fmt.Errorf("failed to unmarshal json object to typed object: %w", err)
	}
	return nil
}

// GetId returns the unique ID for the object.
func (sbi *SpringBootInstance) GetId() uint {
	return *sbi.ID
}

// GetType returns the object type.
func (sbi *SpringBootInstance) GetType() string {
	return "SpringBootInstance"
}

// GetVersion returns the version of the API object.
func (sbi *SpringBootInstance) GetVersion() string {
	return "v0"
}

// GetFullyQualifiedType returns the API-namespace-qualified type name.
func (sbi *SpringBootInstance) GetFullyQualifiedType() string {
	return "threeport.io/v0.SpringBootInstance"
}

// ScheduledForDeletion returns a pointer to the DeletionScheduled timestamp
// if scheduled for deletion or nil if not scheduled for deletion.
func (sbi *SpringBootInstance) ScheduledForDeletion() *time.Time {
	return sbi.DeletionScheduled
}

// RelationshipTaggedForeignKeys returns the relationship-tagged foreign keys on SpringBootInstance.
func (s *SpringBootInstance) RelationshipTaggedForeignKeys() []api.RelationshipTaggedForeignKey {
	return []api.RelationshipTaggedForeignKey{{
		FieldName:    "KubernetesRuntimeInstanceID",
		ObjectID:     s.KubernetesRuntimeInstanceID,
		ObjectType:   new(api.KubernetesRuntimeInstance).GetFullyQualifiedType(),
		Relationship: api.RelationshipRequires,
	}, {
		FieldName:    "KubernetesWorkloadInstanceID",
		ObjectID:     s.KubernetesWorkloadInstanceID,
		ObjectType:   new(api.KubernetesWorkloadInstance).GetFullyQualifiedType(),
		Relationship: api.RelationshipOwns,
	}}
}
