// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

// ApiNamespace is the module's api namespace; used as the
// prefix in this module's fully qualified type form.
const ApiNamespace = "threeport.io"

// Tabler allows custom table names for objects in the Threeport database.
type Tabler interface {
	TableName() string
}

// TableName sets the name of the table for the SpringBootDefinition objects in the database.
func (SpringBootDefinition) TableName() string {
	return "threeport_io_v0_spring_boot_definitions"
}

// TableName sets the name of the table for the SpringBootInstance objects in the database.
func (SpringBootInstance) TableName() string {
	return "threeport_io_v0_spring_boot_instances"
}
