// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	"errors"
	"fmt"
	tp_api "github.com/threeport/threeport/pkg/api/v0"
	tp_client_lib "github.com/threeport/threeport/pkg/client/lib/v0"
	tp_client "github.com/threeport/threeport/pkg/client/v0"
	tp_util "github.com/threeport/threeport/pkg/util/v0"
	"log"
	"net/http"
	routes "spring-boot-threeport-module/pkg/api-server/v0/routes"
	api_v0 "spring-boot-threeport-module/pkg/api/v0"
)

const (
	moduleName = "threeport.io/spring-boot-module-api"
)

// resolveModuleApi looks up the module API by name. It returns the record
// when one is registered under that name, and otherwise reports that a fresh
// record must be created.
func resolveModuleApi(tpApiClient *http.Client, tpApiAddr string) (*tp_api.ModuleApi, bool, error) {
	existingModApi, err := tp_client.GetModuleApiByName(tpApiClient, tpApiAddr, moduleName)
	if err == nil {
		log.Printf("register-module: found existing module api %q", moduleName)
		return existingModApi, false, nil
	}
	if !errors.Is(err, tp_client_lib.ErrObjectNotFound) {
		return nil, false, fmt.Errorf("failed to check for existing module API: %w", err)
	}

	return nil, true, nil
}

// upsertModuleController creates the module controller. When the create
// hits a name conflict, it looks up the existing row by name alone and, if
// that row points at a different module_api_id, updates it to the current
// one so the module claims the controller instead of colliding with it.
func upsertModuleController(tpApiClient *http.Client, tpApiAddr string, controller *tp_api.ModuleController, moduleApiID *uint) (*tp_api.ModuleController, error) {
	created, createErr := tp_client.CreateModuleController(tpApiClient, tpApiAddr, controller)
	if createErr == nil {
		return created, nil
	}
	if !errors.Is(createErr, tp_client_lib.ErrConflict) {
		return nil, createErr
	}

	log.Printf("register-module: controller %q create hit conflict; checking which module api owns it", *controller.Name)
	existing, lookupErr := tp_client.GetModuleControllerByName(tpApiClient, tpApiAddr, *controller.Name)
	if lookupErr != nil {
		return nil, fmt.Errorf("failed to look up conflicting controller %q by name: %w", *controller.Name, lookupErr)
	}
	if existing.ModuleApiID != nil && *existing.ModuleApiID == *moduleApiID {
		log.Printf("register-module: controller %q already bound to current module api %d", *controller.Name, *moduleApiID)
		return existing, nil
	}
	priorModuleApi := "none"
	if existing.ModuleApiID != nil {
		priorModuleApi = fmt.Sprintf("%d", *existing.ModuleApiID)
	}
	log.Printf("register-module: rebinding controller %q from module api %s to %d", *controller.Name, priorModuleApi, *moduleApiID)
	existing.ModuleApiID = moduleApiID
	existing.DeploymentName = controller.DeploymentName
	updated, upErr := tp_client.UpdateModuleController(tpApiClient, tpApiAddr, existing)
	if upErr != nil {
		return nil, fmt.Errorf("failed to rebind controller %q to current module api: %w", *controller.Name, upErr)
	}
	return updated, nil
}

// RegisterModule calls the Threeport API to register the module with core Threeport.
// This ensures that module object requests are proxied to the module API by the
// Threeport API server.
func RegisterModule(
	tpApiClient *http.Client,
	tpApiAddr string,
	moduleApiEndpoint string,
	moduleNamespace string,
) error {
	// look up the module API so a re-registration reuses the existing
	// record along with the controller and object rows that reference it
	existingModApi, createFresh, err := resolveModuleApi(tpApiClient, tpApiAddr)
	if err != nil {
		return err
	}
	if createFresh {
		// register the module in the Threeport API with the ModuleApi object
		log.Printf("register-module: no existing module api; creating %q", moduleName)
		moduleApi := tp_api.ModuleApi{
			ApiNamespace: tp_util.Ptr(api_v0.ApiNamespace),
			Endpoint:     tp_util.Ptr(moduleApiEndpoint),
			Name:         tp_util.Ptr(moduleName),
		}
		createdModApi, createErr := tp_client.CreateModuleApi(tpApiClient, tpApiAddr, &moduleApi)
		if createErr != nil {
			return fmt.Errorf("failed to create module API object in Threeport API: %w", createErr)
		}
		existingModApi = createdModApi
	}
	///////////////////////////////////////////////////////////////////////////////
	// registering controllers, objects and routes for Springboot object group
	///////////////////////////////////////////////////////////////////////////////
	// registering controller springboot-controller
	springbootControllerSlice, springbootControllerErr := tp_client.GetModuleControllersByQueryString(
		tpApiClient,
		tpApiAddr,
		fmt.Sprintf("name=%s&moduleapiid=%d", "springboot-controller", *existingModApi.ID),
	)
	if springbootControllerErr != nil {
		return fmt.Errorf("failed to check for existing controller springboot-controller: %w", springbootControllerErr)
	}
	var springbootController tp_api.ModuleController
	if len(*springbootControllerSlice) == 0 {
		// controller doesn't exist - create it
		controller := tp_api.ModuleController{
			DeploymentName: tp_util.Ptr(moduleNamespace + "/threeport-springboot-controller"),
			ModuleApiID:    existingModApi.ID,
			Name:           tp_util.Ptr("springboot-controller"),
		}
		// the lookup above is scoped to this module api, so a row
		// under a different one is invisible here and only shows up
		// as a name conflict on the create
		createdController, err := upsertModuleController(tpApiClient, tpApiAddr, &controller, existingModApi.ID)
		if err != nil {
			return fmt.Errorf("failed to register module controller springboot-controller in Threeport API: %w", err)
		}
		springbootController = *createdController

	} else if len(*springbootControllerSlice) == 1 {
		springbootController = (*springbootControllerSlice)[0]
	} else {
		return fmt.Errorf("expected 0 or 1 module controllers for springboot-controller, got %d", len(*springbootControllerSlice))
	}

	// registering object SpringBootDefinition
	var springBootDefinition tp_api.ModuleObject
	springBootDefinitionSlice, springBootDefinitionErr := tp_client.GetModuleObjectsByQueryString(
		tpApiClient,
		tpApiAddr,
		fmt.Sprintf("name=SpringBootDefinition&moduleapiid=%d", *existingModApi.ID),
	)
	if springBootDefinitionErr != nil {
		return fmt.Errorf("failed to check for existing object SpringBootDefinition: %w", springBootDefinitionErr)
	}
	if len(*springBootDefinitionSlice) == 0 {
		object := tp_api.ModuleObject{
			Description:        tp_util.Ptr(""),
			ModuleApiID:        existingModApi.ID,
			ModuleControllerID: springbootController.ID,
			Name:               tp_util.Ptr("SpringBootDefinition"),
			Version:            tp_util.Ptr("v0"),
		}
		objectResult, err := tp_client.CreateModuleObject(tpApiClient, tpApiAddr, &object)
		if err != nil {
			return fmt.Errorf("failed to create module object SpringBootDefinition in Threeport API: %w", err)
		}
		springBootDefinition = *objectResult
	} else if len(*springBootDefinitionSlice) == 1 {
		springBootDefinition = (*springBootDefinitionSlice)[0]
	} else {
		return fmt.Errorf("expected 0 or 1 module objects for SpringBootDefinition, got %d", len(*springBootDefinitionSlice))
	}

	// registering routes for SpringBootDefinition
	springBootDefinitionRoute := tp_api.ModuleApiRoute{
		ModuleApiID:   existingModApi.ID,
		ModuleObjects: []*tp_api.ModuleObject{&springBootDefinition},
		Path:          tp_util.Ptr(api_v0.PathSpringBootDefinitionVersions),
	}
	_, springBootDefinitionRouteErr := tp_client.CreateModuleApiRouteWithModuleObjectReferences(
		tpApiClient,
		tpApiAddr,
		&springBootDefinitionRoute,
	)
	if springBootDefinitionRouteErr != nil && !errors.Is(springBootDefinitionRouteErr, tp_client_lib.ErrConflict) {
		return fmt.Errorf("failed to create module route for SpringBootDefinition version in Threeport API: %w", springBootDefinitionRouteErr)
	}
	springBootDefinitionRoute = tp_api.ModuleApiRoute{
		ModuleApiID:   existingModApi.ID,
		ModuleObjects: []*tp_api.ModuleObject{&springBootDefinition},
		Path:          tp_util.Ptr(api_v0.PathSpringBootDefinitions),
	}
	_, springBootDefinitionRouteErr = tp_client.CreateModuleApiRouteWithModuleObjectReferences(
		tpApiClient,
		tpApiAddr,
		&springBootDefinitionRoute,
	)
	if springBootDefinitionRouteErr != nil && !errors.Is(springBootDefinitionRouteErr, tp_client_lib.ErrConflict) {
		return fmt.Errorf("failed to create module route for SpringBootDefinition in Threeport API: %w", springBootDefinitionRouteErr)
	}

	// registering object SpringBootInstance
	var springBootInstance tp_api.ModuleObject
	springBootInstanceSlice, springBootInstanceErr := tp_client.GetModuleObjectsByQueryString(
		tpApiClient,
		tpApiAddr,
		fmt.Sprintf("name=SpringBootInstance&moduleapiid=%d", *existingModApi.ID),
	)
	if springBootInstanceErr != nil {
		return fmt.Errorf("failed to check for existing object SpringBootInstance: %w", springBootInstanceErr)
	}
	if len(*springBootInstanceSlice) == 0 {
		object := tp_api.ModuleObject{
			Description:        tp_util.Ptr(""),
			ModuleApiID:        existingModApi.ID,
			ModuleControllerID: springbootController.ID,
			Name:               tp_util.Ptr("SpringBootInstance"),
			Version:            tp_util.Ptr("v0"),
		}
		objectResult, err := tp_client.CreateModuleObject(tpApiClient, tpApiAddr, &object)
		if err != nil {
			return fmt.Errorf("failed to create module object SpringBootInstance in Threeport API: %w", err)
		}
		springBootInstance = *objectResult
	} else if len(*springBootInstanceSlice) == 1 {
		springBootInstance = (*springBootInstanceSlice)[0]
	} else {
		return fmt.Errorf("expected 0 or 1 module objects for SpringBootInstance, got %d", len(*springBootInstanceSlice))
	}

	// registering routes for SpringBootInstance
	springBootInstanceRoute := tp_api.ModuleApiRoute{
		ModuleApiID:   existingModApi.ID,
		ModuleObjects: []*tp_api.ModuleObject{&springBootInstance},
		Path:          tp_util.Ptr(api_v0.PathSpringBootInstanceVersions),
	}
	_, springBootInstanceRouteErr := tp_client.CreateModuleApiRouteWithModuleObjectReferences(
		tpApiClient,
		tpApiAddr,
		&springBootInstanceRoute,
	)
	if springBootInstanceRouteErr != nil && !errors.Is(springBootInstanceRouteErr, tp_client_lib.ErrConflict) {
		return fmt.Errorf("failed to create module route for SpringBootInstance version in Threeport API: %w", springBootInstanceRouteErr)
	}
	springBootInstanceRoute = tp_api.ModuleApiRoute{
		ModuleApiID:   existingModApi.ID,
		ModuleObjects: []*tp_api.ModuleObject{&springBootInstance},
		Path:          tp_util.Ptr(api_v0.PathSpringBootInstances),
	}
	_, springBootInstanceRouteErr = tp_client.CreateModuleApiRouteWithModuleObjectReferences(
		tpApiClient,
		tpApiAddr,
		&springBootInstanceRoute,
	)
	if springBootInstanceRouteErr != nil && !errors.Is(springBootInstanceRouteErr, tp_client_lib.ErrConflict) {
		return fmt.Errorf("failed to create module route for SpringBootInstance in Threeport API: %w", springBootInstanceRouteErr)
	}

	// registering custom routes
	for _, customRoute := range *routes.CustomRoutes(nil) {
		// query the module objects for the custom route by name and version
		moduleObjects := []*tp_api.ModuleObject{}
		for _, apiObject := range *customRoute.ApiObjects {
			modObj, err := tp_client.GetModuleObjectsByQueryString(
				tpApiClient,
				tpApiAddr,
				fmt.Sprintf("name=%s&version=%s", apiObject.Name, apiObject.Version),
			)
			if err != nil {
				return fmt.Errorf("failed to retrieve module object %s: %w", apiObject.Name, err)
			}
			moduleObjects = append(moduleObjects, &(*modObj)[0])
		}
		route := tp_api.ModuleApiRoute{
			ModuleApiID:   existingModApi.ID,
			ModuleObjects: moduleObjects,
			Path:          tp_util.Ptr(customRoute.Path),
		}
		_, customRouteErr := tp_client.CreateModuleApiRouteWithModuleObjectReferences(
			tpApiClient,
			tpApiAddr,
			&route,
		)
		if customRouteErr != nil && !errors.Is(customRouteErr, tp_client_lib.ErrConflict) {
			return fmt.Errorf("failed to create module route for custom route %s: %w", customRoute.Path, customRouteErr)
		}
	}

	return nil
}
