// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import tpapiserver_lib "github.com/threeport/threeport/pkg/api-server/lib/v0"

var (
	SpringBootDefinitionTaggedFields = make(map[string]*tpapiserver_lib.FieldsByTag)
	SpringBootInstanceTaggedFields   = make(map[string]*tpapiserver_lib.FieldsByTag)
)
