// boilerplate generated by 'threeport-sdk gen' - do not edit

package springboot

import (
	"errors"
	"fmt"
	tpapi_lib "github.com/threeport/threeport/pkg/api/lib/v0"
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	tpclient_lib "github.com/threeport/threeport/pkg/client/lib/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
	event "github.com/threeport/threeport/pkg/event/v0"
	notifications "github.com/threeport/threeport/pkg/notifications/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"os"
	"os/signal"
	api_v0 "spring-boot-threeport-module/pkg/api/v0"
	client_v0 "spring-boot-threeport-module/pkg/client/v0"
	"strings"
	"syscall"
	"time"
)

// SpringBootInstanceReconciler reconciles system state when a SpringBootInstance
// is created, updated or deleted.
func SpringBootInstanceReconciler(r *controller.Reconciler) {
	r.ShutdownWait.Add(1)
	reconcilerLog := r.Log.WithValues("reconcilerName", r.Name)
	reconcilerLog.Info("reconciler started")
	shutdown := false

	// create a channel to receive OS signals
	osSignals := make(chan os.Signal, 1)
	lockReleased := make(chan bool, 1)

	// register the os signals channel to receive SIGINT and SIGTERM signals
	signal.Notify(osSignals, syscall.SIGINT, syscall.SIGTERM)

	for {
		// create a fresh log object per reconciliation loop so we don't
		// accumulate values across multiple loops
		log := r.Log.WithValues("reconcilerName", r.Name)

		if shutdown {
			break
		}

		// check for shutdown instruction
		select {
		case <-r.Shutdown:
			shutdown = true
		default:
			// pull message off queue
			msg := r.PullMessage()
			if msg == nil {
				continue
			}

			// consume message data to capture notification from API
			notif, err := notifications.ConsumeMessage(msg.Data)
			if err != nil {
				log.Error(
					err, "failed to consume message data from NATS",
					"msgData", string(msg.Data),
				)
				r.RequeueRaw(msg)
				log.V(1).Info("spring boot instance reconciliation requeued with identical payload and fixed delay")
				continue
			}

			// determine the correct object version from the notification
			var springBootInstance tpapi_lib.ReconciledThreeportApiObject
			switch notif.ObjectVersion {
			case "v0":
				springBootInstance = &api_v0.SpringBootInstance{}
			default:
				log.Error(errors.New("received unrecognized version of spring boot instance object"), "")
				r.RequeueRaw(msg)
				log.V(1).Info("spring boot instance reconciliation requeued with identical payload and fixed delay")
				continue
			}

			// decode the object that was sent in the notification
			if err := springBootInstance.DecodeNotifObject(notif.Object); err != nil {
				log.Error(err, "failed to marshal object map from consumed notification message")
				r.RequeueRaw(msg)
				log.V(1).Info("spring boot instance reconciliation requeued with identical payload and fixed delay")
				continue
			}
			log = log.WithValues("springBootInstanceID", springBootInstance.GetId())

			// back off the requeue delay as needed
			requeueDelay := controller.SetRequeueDelay(
				notif.CreationTime,
			)

			// check for lock on object
			locked, ok := r.CheckLock(springBootInstance)
			if locked || ok == false {
				r.Requeue(springBootInstance, requeueDelay, msg)
				log.V(1).Info("spring boot instance reconciliation requeued")
				continue
			}

			// set up handler to unlock and requeue on termination signal
			go func() {
				select {
				case <-osSignals:
					log.V(1).Info("received termination signal, performing unlock and requeue of spring boot instance")
					r.UnlockAndRequeue(springBootInstance, requeueDelay, lockReleased, msg)
				case <-lockReleased:
					log.V(1).Info("reached end of reconcile loop for spring boot instance, closing out signal handler")
				}
			}()

			// put a lock on the reconciliation of the created object
			if ok := r.Lock(springBootInstance); !ok {
				r.Requeue(springBootInstance, requeueDelay, msg)
				log.V(1).Info("spring boot instance reconciliation requeued")
				continue
			}

			// retrieve latest version of object
			var latestSpringBootInstance tpapi_lib.ReconciledThreeportApiObject
			var getLatestErr error
			switch notif.ObjectVersion {
			case "v0":
				latestObject, err := client_v0.GetSpringBootInstanceByID(
					r.APIClient,
					r.APIServer,
					springBootInstance.GetId(),
				)
				latestSpringBootInstance = latestObject
				getLatestErr = err
			default:
				getLatestErr = errors.New("received unrecognized version of spring boot instance object")
			}

			// check if error is 404 - if object no longer exists, no need to requeue
			if errors.Is(getLatestErr, tpclient_lib.ErrObjectNotFound) {
				log.Info("object no longer exists - halting reconciliation")
				r.ReleaseLock(springBootInstance, lockReleased, msg, true)
				continue
			}
			if getLatestErr != nil {
				log.Error(getLatestErr, "failed to get spring boot instance by ID from API")
				r.UnlockAndRequeue(springBootInstance, requeueDelay, lockReleased, msg)
				continue
			}
			springBootInstance = latestSpringBootInstance

			// determine which operation and act accordingly
			switch notif.Operation {
			case notifications.NotificationOperationCreated:
				if springBootInstance.ScheduledForDeletion() != nil {
					log.Info("spring boot instance scheduled for deletion - skipping create")
					break
				}
				var operationErr error
				var customRequeueDelay int64
				switch springBootInstance.GetVersion() {
				case "v0":
					requeueDelay, err := v0SpringBootInstanceCreated(
						r,
						springBootInstance.(*api_v0.SpringBootInstance),
						&log,
					)
					customRequeueDelay = requeueDelay
					operationErr = err
				default:
					operationErr = errors.New("unrecognized version of spring boot instance encountered for create operation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile created spring boot instance object"
					log.Error(operationErr, errorMsg)
					r.EventsRecorder.HandleEventOverride(
						&tpapi_v0.Event{
							Note:   util.Ptr(errorMsg),
							Reason: util.Ptr(event.ReasonFailedCreate),
							Type:   util.Ptr(event.TypeNormal),
						},
						springBootInstance.GetId(),
						springBootInstance.GetFullyQualifiedType(),
						operationErr,
						&log,
					)
					r.UnlockAndRequeue(
						springBootInstance,
						requeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				if customRequeueDelay != 0 {
					log.Info("create requeued for future reconciliation")
					r.UnlockAndRequeue(
						springBootInstance,
						customRequeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
			case notifications.NotificationOperationUpdated:
				if springBootInstance.ScheduledForDeletion() != nil {
					log.Info("spring boot instance scheduled for deletion - skipping update")
					break
				}
				var operationErr error
				var customRequeueDelay int64
				switch springBootInstance.GetVersion() {
				case "v0":
					requeueDelay, err := v0SpringBootInstanceUpdated(
						r,
						springBootInstance.(*api_v0.SpringBootInstance),
						&log,
					)
					customRequeueDelay = requeueDelay
					operationErr = err
				default:
					operationErr = errors.New("unrecognized version of spring boot instance encountered for update operation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile updated spring boot instance object"
					log.Error(operationErr, errorMsg)
					r.EventsRecorder.HandleEventOverride(
						&tpapi_v0.Event{
							Note:   util.Ptr(errorMsg),
							Reason: util.Ptr(event.ReasonFailedUpdate),
							Type:   util.Ptr(event.TypeNormal),
						},
						springBootInstance.GetId(),
						springBootInstance.GetFullyQualifiedType(),
						operationErr,
						&log,
					)
					r.UnlockAndRequeue(
						springBootInstance,
						requeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				if customRequeueDelay != 0 {
					log.Info("update requeued for future reconciliation")
					r.UnlockAndRequeue(
						springBootInstance,
						customRequeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
			case notifications.NotificationOperationDeleted:
				var operationErr error
				var customRequeueDelay int64
				switch springBootInstance.GetVersion() {
				case "v0":
					requeueDelay, err := v0SpringBootInstanceDeleted(
						r,
						springBootInstance.(*api_v0.SpringBootInstance),
						&log,
					)
					customRequeueDelay = requeueDelay
					operationErr = err
				default:
					operationErr = errors.New("unrecognized version of spring boot instance encountered for delete operation")
				}
				if operationErr != nil {
					errorMsg := "failed to reconcile deleted spring boot instance object"
					log.Error(operationErr, errorMsg)
					r.EventsRecorder.HandleEventOverride(
						&tpapi_v0.Event{
							Note:   util.Ptr(errorMsg),
							Reason: util.Ptr(event.ReasonFailedDelete),
							Type:   util.Ptr(event.TypeNormal),
						},
						springBootInstance.GetId(),
						springBootInstance.GetFullyQualifiedType(),
						operationErr,
						&log,
					)
					r.UnlockAndRequeue(
						springBootInstance,
						requeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				if customRequeueDelay != 0 {
					log.Info("delete requeued for future reconciliation")
					r.UnlockAndRequeue(
						springBootInstance,
						customRequeueDelay,
						lockReleased,
						msg,
					)
					continue
				}
				deletionTimestamp := util.Ptr(time.Now().UTC())
				deletedSpringBootInstance := api_v0.SpringBootInstance{
					Common: tpapi_v0.Common{ID: util.Ptr(springBootInstance.GetId())},
					Reconciliation: tpapi_v0.Reconciliation{
						DeletionAcknowledged: deletionTimestamp,
						DeletionConfirmed:    deletionTimestamp,
						Reconciled:           util.Ptr(true),
					},
				}
				_, err = client_v0.UpdateSpringBootInstance(
					r.APIClient,
					r.APIServer,
					&deletedSpringBootInstance,
				)
				if err != nil {
					log.Error(err, "failed to update spring boot instance to mark as deleted")
					r.UnlockAndRequeue(springBootInstance, requeueDelay, lockReleased, msg)
					continue
				}
				_, err = client_v0.DeleteSpringBootInstance(
					r.APIClient,
					r.APIServer,
					springBootInstance.GetId(),
				)
				if err != nil {
					log.Error(err, "failed to delete spring boot instance")
					r.UnlockAndRequeue(springBootInstance, requeueDelay, lockReleased, msg)
					continue
				}
			default:
				log.Error(
					errors.New("unrecognized notifcation operation"),
					"notification included an invalid operation",
				)
				r.UnlockAndRequeue(
					springBootInstance,
					requeueDelay,
					lockReleased,
					msg,
				)
				continue
			}

			// set the object's Reconciled field to true if not deleted
			if notif.Operation != notifications.NotificationOperationDeleted {
				reconciledSpringBootInstance := api_v0.SpringBootInstance{
					Common:         tpapi_v0.Common{ID: util.Ptr(springBootInstance.GetId())},
					Reconciliation: tpapi_v0.Reconciliation{Reconciled: util.Ptr(true)},
				}
				updatedSpringBootInstance, err := client_v0.UpdateSpringBootInstance(
					r.APIClient,
					r.APIServer,
					&reconciledSpringBootInstance,
				)
				if err != nil {
					log.Error(err, "failed to update spring boot instance to mark as reconciled")
					r.UnlockAndRequeue(springBootInstance, requeueDelay, lockReleased, msg)
					continue
				}
				log.V(1).Info(
					"spring boot instance marked as reconciled in API",
					"spring boot instanceName", updatedSpringBootInstance.Name,
				)
			}

			// release the lock on the reconciliation of the created object
			if ok := r.ReleaseLock(springBootInstance, lockReleased, msg, true); !ok {
				log.Error(errors.New("spring boot instance remains locked - will unlock when TTL expires"), "")
			} else {
				log.V(1).Info("spring boot instance unlocked")
			}

			// log and record event for successful reconciliation
			successMsg := fmt.Sprintf(
				"spring boot instance successfully reconciled for %s operation",
				strings.ToLower(string(notif.Operation)),
			)
			if err := r.EventsRecorder.RecordEvent(
				&tpapi_v0.Event{
					Note:   util.Ptr(successMsg),
					Reason: util.Ptr(event.GetSuccessReasonForOperation(notif.Operation)),
					Type:   util.Ptr(event.TypeNormal),
				},
				springBootInstance.GetId(),
				springBootInstance.GetFullyQualifiedType(),
			); err != nil {
				log.Error(err, "failed to record event for successful spring boot instance reconciliation")
			}
			log.Info(successMsg)
		}
	}

	r.Sub.Unsubscribe()
	reconcilerLog.Info("reconciler shutting down")
	r.ShutdownWait.Done()
}
