// boilerplate generated by 'threeport-sdk gen' - do not edit

package springboot

// The name and description of the NATS bucket used for springboot object locks
const (
	LockBucketName  = "springbootLock"
	LockBucketDescr = "contains locks on springboot objects"
)
