// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package springboot

import (
	"errors"
	"fmt"

	logr "github.com/go-logr/logr"
	tpapi "github.com/threeport/threeport/pkg/api/v0"
	tpclientlib "github.com/threeport/threeport/pkg/client/lib/v0"
	tpclient "github.com/threeport/threeport/pkg/client/v0"
	controller "github.com/threeport/threeport/pkg/controller/v0"
	util "github.com/threeport/threeport/pkg/util/v0"

	v0 "spring-boot-threeport-module/pkg/api/v0"
	client_v0 "spring-boot-threeport-module/pkg/client/v0"
)

// v0SpringBootDefinitionCreated performs reconciliation when a v0
// SpringBootDefinition has been created.
//
// It renders the Kubernetes manifests for the application and hands them to
// Threeport as a workload definition, then records that workload definition on
// the Spring Boot definition. The API creates the attached object reference
// from that foreign key, so nothing here manipulates attachments directly.
func v0SpringBootDefinitionCreated(
	r *controller.Reconciler,
	springBootDefinition *v0.SpringBootDefinition,
	log *logr.Logger,
) (int64, error) {
	environment := "dev"
	if springBootDefinition.Environment != nil {
		environment = *springBootDefinition.Environment
	}

	replicas := replicasByEnv(environment)
	if springBootDefinition.Replicas != nil {
		replicas = *springBootDefinition.Replicas
	}

	serverPort := v0.DefaultServerPort
	if springBootDefinition.ServerPort != nil {
		serverPort = *springBootDefinition.ServerPort
	}

	healthPath := v0.DefaultHealthPath
	if springBootDefinition.HealthPath != nil {
		healthPath = *springBootDefinition.HealthPath
	}

	// a Spring Boot application can run on an embedded database, so the module
	// deploys one only when the definition asks for it
	database := v0.DatabaseNone
	if springBootDefinition.Database != nil {
		database = *springBootDefinition.Database
	}

	var profile string
	if springBootDefinition.Profile != nil {
		profile = *springBootDefinition.Profile
	}

	var javaOpts string
	if springBootDefinition.JavaOpts != nil {
		javaOpts = *springBootDefinition.JavaOpts
	}

	cpuRequest := util.Deref(springBootDefinition.CpuRequest)
	cpuLimit := util.Deref(springBootDefinition.CpuLimit)
	memoryRequest := util.Deref(springBootDefinition.MemoryRequest)
	memoryLimit := util.Deref(springBootDefinition.MemoryLimit)

	yamlDoc, err := springBootYaml(springBootManifestInput{
		definitionName: *springBootDefinition.Name,
		image:          *springBootDefinition.Image,
		profile:        profile,
		serverPort:     serverPort,
		javaOpts:       javaOpts,
		cpuRequest:     cpuRequest,
		cpuLimit:       cpuLimit,
		memoryRequest:  memoryRequest,
		memoryLimit:    memoryLimit,
		replicas:       replicas,
		environment:    environment,
		database:       database,
		healthPath:     healthPath,
		dbStorageGb:    dbStorageByEnv(environment),
	})
	if err != nil {
		return 0, fmt.Errorf("failed to generate spring boot YAML manifest: %w", err)
	}

	// reconciliation runs again on requeue, so an existing workload definition
	// is adopted rather than duplicated
	nameQuery := fmt.Sprintf("name=%s", *springBootDefinition.Name)
	existingWorkloadDefinitions, err := tpclient.GetKubernetesWorkloadDefinitionsByQueryString(
		r.APIClient,
		r.APIServer,
		nameQuery,
	)
	if err != nil {
		return 0, fmt.Errorf(
			"failed to check for kubernetes workload definitions with name %s: %w",
			*springBootDefinition.Name, err,
		)
	}

	var workloadDefinition *tpapi.KubernetesWorkloadDefinition
	if len(*existingWorkloadDefinitions) == 0 {
		created, err := tpclient.CreateKubernetesWorkloadDefinition(
			r.APIClient,
			r.APIServer,
			&tpapi.KubernetesWorkloadDefinition{
				Definition:   tpapi.Definition{Name: springBootDefinition.Name},
				YAMLDocument: &yamlDoc,
			},
		)
		if err != nil {
			return 0, fmt.Errorf("failed to create kubernetes workload definition: %w", err)
		}
		workloadDefinition = created
	} else {
		workloadDefinition = &(*existingWorkloadDefinitions)[0]
	}

	// recording the foreign key is what creates the attachment: the API's
	// relationship hooks read it and write the attached object reference, which
	// then blocks the workload definition from being deleted out from under us
	if _, err := client_v0.UpdateSpringBootDefinition(
		r.APIClient,
		r.APIServer,
		&v0.SpringBootDefinition{
			Common:                         tpapi.Common{ID: springBootDefinition.ID},
			KubernetesWorkloadDefinitionID: workloadDefinition.ID,
		},
	); err != nil {
		return 0, fmt.Errorf("failed to record kubernetes workload definition on spring boot definition: %w", err)
	}

	return 0, nil
}

// v0SpringBootDefinitionUpdated performs reconciliation when a v0
// SpringBootDefinition has been updated.
func v0SpringBootDefinitionUpdated(
	r *controller.Reconciler,
	springBootDefinition *v0.SpringBootDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0SpringBootDefinitionDeleted performs reconciliation when a v0
// SpringBootDefinition has been deleted.
func v0SpringBootDefinitionDeleted(
	r *controller.Reconciler,
	springBootDefinition *v0.SpringBootDefinition,
	log *logr.Logger,
) (int64, error) {
	// a definition that never got as far as creating its workload has nothing
	// to clean up
	if springBootDefinition.KubernetesWorkloadDefinitionID == nil {
		return 0, nil
	}

	if _, err := tpclient.DeleteKubernetesWorkloadDefinition(
		r.APIClient,
		r.APIServer,
		*springBootDefinition.KubernetesWorkloadDefinitionID,
	); err != nil {
		// the workload definition being gone already is the state we want, and
		// happens whenever a delete is retried
		if !errors.Is(err, tpclientlib.ErrObjectNotFound) {
			return 0, fmt.Errorf(
				"failed to delete kubernetes workload definition with ID %d: %w",
				*springBootDefinition.KubernetesWorkloadDefinitionID, err,
			)
		}
	}

	return 0, nil
}

// replicasByEnv returns the default replica count for an environment, used when
// the definition does not state one.
func replicasByEnv(env string) int {
	switch env {
	case "prod":
		return 3
	default:
		return 1
	}
}

// dbStorageByEnv returns the database volume size in gigabytes for an
// environment.
func dbStorageByEnv(env string) int {
	switch env {
	case "prod":
		return 100
	default:
		return 20
	}
}
