// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package springboot

import (
	logr "github.com/go-logr/logr"
	controller "github.com/threeport/threeport/pkg/controller/v0"
	v0 "spring-boot-threeport-module/pkg/api/v0"
)

// v0SpringBootDefinitionCreated performs reconciliation when a v0 SpringBootDefinition
// has been created.
func v0SpringBootDefinitionCreated(
	r *controller.Reconciler,
	springBootDefinition *v0.SpringBootDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0SpringBootDefinitionUpdated performs reconciliation when a v0 SpringBootDefinition
// has been updated.
func v0SpringBootDefinitionUpdated(
	r *controller.Reconciler,
	springBootDefinition *v0.SpringBootDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0SpringBootDefinitionDeleted performs reconciliation when a v0 SpringBootDefinition
// has been deleted.
func v0SpringBootDefinitionDeleted(
	r *controller.Reconciler,
	springBootDefinition *v0.SpringBootDefinition,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
