// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package springboot

import (
	logr "github.com/go-logr/logr"
	controller "github.com/threeport/threeport/pkg/controller/v0"
	v0 "spring-boot-threeport-module/pkg/api/v0"
)

// v0SpringBootInstanceCreated performs reconciliation when a v0 SpringBootInstance
// has been created.
func v0SpringBootInstanceCreated(
	r *controller.Reconciler,
	springBootInstance *v0.SpringBootInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0SpringBootInstanceUpdated performs reconciliation when a v0 SpringBootInstance
// has been updated.
func v0SpringBootInstanceUpdated(
	r *controller.Reconciler,
	springBootInstance *v0.SpringBootInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}

// v0SpringBootInstanceDeleted performs reconciliation when a v0 SpringBootInstance
// has been deleted.
func v0SpringBootInstanceDeleted(
	r *controller.Reconciler,
	springBootInstance *v0.SpringBootInstance,
	log *logr.Logger,
) (int64, error) {
	return 0, nil
}
