// boilerplate generated by 'threeport-sdk gen' - do not edit

package util

import (
	echo "github.com/labstack/echo/v4"
	"net/http"
	version "spring-boot-threeport-module/internal/version"
)

// RestApiVersion provides the version of the REST API binary.
type RestApiVersion struct {
	Version string
}

// VersionRoute adds the /version route to the server to return the API
// server's version.
func VersionRoute(e *echo.Echo) {
	e.GET("/version", func(c echo.Context) error {
		return c.JSON(
			http.StatusOK,
			RestApiVersion{
				Version: version.GetVersion(),
			},
		)
	})
}
