// boilerplate generated by 'threeport-sdk gen' - do not edit

package routes

import (
	echo "github.com/labstack/echo/v4"
	handlers "spring-boot-threeport-module/pkg/api-server/v0/handlers"
)

// AddRoutes adds routes for all objects of a particular API version.
func AddRoutes(e *echo.Echo, h *handlers.Handler) {
	SpringBootDefinitionRoutes(e, h)
	SpringBootInstanceRoutes(e, h)
}
