// boilerplate generated by 'threeport-sdk gen' - do not edit

package routes

import (
	echo "github.com/labstack/echo/v4"
	handlers "spring-boot-threeport-module/pkg/api-server/v0/handlers"
	v0 "spring-boot-threeport-module/pkg/api/v0"
)

// SpringBootDefinitionRoutes sets up all routes for the SpringBootDefinition handlers.
func SpringBootDefinitionRoutes(e *echo.Echo, h *handlers.Handler) {
	e.GET(v0.PathSpringBootDefinitionVersions, h.GetSpringBootDefinitionVersions)

	e.POST(v0.PathSpringBootDefinitions, h.AddSpringBootDefinition)
	e.GET(v0.PathSpringBootDefinitions, h.GetSpringBootDefinitions)
	e.GET(v0.PathSpringBootDefinitions+"/:id", h.GetSpringBootDefinition)
	e.PATCH(v0.PathSpringBootDefinitions+"/:id", h.UpdateSpringBootDefinition)
	e.PUT(v0.PathSpringBootDefinitions+"/:id", h.ReplaceSpringBootDefinition)
	e.DELETE(v0.PathSpringBootDefinitions+"/:id", h.DeleteSpringBootDefinition)
}

// SpringBootInstanceRoutes sets up all routes for the SpringBootInstance handlers.
func SpringBootInstanceRoutes(e *echo.Echo, h *handlers.Handler) {
	e.GET(v0.PathSpringBootInstanceVersions, h.GetSpringBootInstanceVersions)

	e.POST(v0.PathSpringBootInstances, h.AddSpringBootInstance)
	e.GET(v0.PathSpringBootInstances, h.GetSpringBootInstances)
	e.GET(v0.PathSpringBootInstances+"/:id", h.GetSpringBootInstance)
	e.PATCH(v0.PathSpringBootInstances+"/:id", h.UpdateSpringBootInstance)
	e.PUT(v0.PathSpringBootInstances+"/:id", h.ReplaceSpringBootInstance)
	e.DELETE(v0.PathSpringBootInstances+"/:id", h.DeleteSpringBootInstance)
}
