// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import (
	"errors"
	"fmt"
	cobra "github.com/spf13/cobra"
	tptctl_cmd "github.com/threeport/threeport/cmd/tptctl/cmd"
	cli "github.com/threeport/threeport/pkg/cli/v0"
	"os"
	yaml "sigs.k8s.io/yaml"
	config_v0 "spring-boot-threeport-module/pkg/config/v0"
)

var (
	springbootName       string
	springbootConfigPath string
	springbootStdin      bool
	springbootVersion    string
	springbootOutput     string
)

///////////////////////////////////////////////////////////////////////////////
// SpringBoot
///////////////////////////////////////////////////////////////////////////////

// GetSpringBootsCmd represents the command 'tptctl spring-boot get spring-boots'
var GetSpringBootsCmd = &cobra.Command{
	Aliases: []string{"spring-boot"},
	Example: "  # get all spring boots\n  tptctl spring-boot get spring-boots\n\n  # get a specific spring boot\n  tptctl spring-boot get spring-boot --name some-spring-boot",
	Long:    "Get spring boots from the system. Use --name to get a specific spring boot. A spring boot is a unified abstraction of a spring boot definition and spring boot instance.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, requestedControlPlane := tptctl_cmd.GetClientContext(cmd)

		// flag validation
		if err := cli.ValidateConfigNameFlags(
			springbootConfigPath,
			springbootName,
			"spring boot",
		); err != nil {
			cli.Error("flag validation failed", err)
			os.Exit(1)
		}

		// get spring boot based on version
		switch springbootVersion {
		case "v0":
			// load spring boot values
			springBootConfig := config_v0.SpringBootConfig{}
			if springbootConfigPath != "" || springbootStdin {
				configContent, err := cli.ReadConfigContent(springbootConfigPath, springbootStdin)
				if err != nil {
					cli.Error("failed to read config", err)
					os.Exit(1)
				}
				if err := yaml.UnmarshalStrict(configContent, &springBootConfig); err != nil {
					cli.Error("failed to unmarshal config file yaml content", err)
					os.Exit(1)
				}
			} else if springbootName != "" {
				springBootConfig = config_v0.SpringBootConfig{
					SpringBoot: config_v0.SpringBootValues{
						Name: &springbootName,
					},
				}
			}

			// get spring boot
			springBootConfigs, err := springBootConfig.Get(apiClient, apiEndpoint)
			if err != nil {
				cli.Error("failed to retrieve spring boot", err)
				os.Exit(1)
			}

			// check if spring boot exists
			if len(*springBootConfigs) == 0 {
				cli.Info(fmt.Sprintf(
					"no spring boots found that are currently managed by %s threeport control plane",
					requestedControlPlane,
				))
				os.Exit(0)
			}

			// write the output
			switch springbootOutput {
			case "tabular":
				if err := outputGetv0SpringBootsCmd(springBootConfigs); err != nil {
					cli.Error("failed to produce output", err)
					os.Exit(1)
				}
			case "yaml":
				if err := cli.YamlObjectOutput(*springBootConfigs); err != nil {
					cli.Error("failed to produce YAML output", err)
					os.Exit(1)
				}
			case "json":
				if err := cli.JsonObjectOutput(*springBootConfigs); err != nil {
					cli.Error("failed to produce JSON output", err)
					os.Exit(1)
				}
			default:
				cli.Error("", fmt.Errorf("unrecognized output format: %s", springbootOutput))
				os.Exit(1)
			}
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Get spring boots from the system",
	SilenceUsage: true,
	Use:          "spring-boots",
}

func init() {
	GetCmd.AddCommand(GetSpringBootsCmd)

	GetSpringBootsCmd.Flags().StringVarP(
		&springbootName,
		"name", "n", "", "Name of spring boot.",
	)
	GetSpringBootsCmd.Flags().StringVarP(
		&springbootConfigPath,
		"config", "c", "", "Path to file with spring boot config.",
	)
	GetSpringBootsCmd.Flags().StringVarP(
		&springbootVersion,
		"version", "v", "v0", "Version of spring boot objects to retrieve. One of: [v0]",
	)
	GetSpringBootsCmd.Flags().StringVarP(
		&springbootOutput,
		"output", "o", "tabular", "Output format for spring boot objects. One of: [tabular, yaml, json]",
	)
	GetSpringBootsCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
}

// CreateSpringBootCmd represents the command 'tptctl spring-boot create spring-boot'
var CreateSpringBootCmd = &cobra.Command{
	Example: "  # create a new spring boot using a config file\n  tptctl spring-boot create spring-boot --config path/to/config.yaml",
	Long:    "Create a new spring boot. A spring boot is a unified abstraction of a spring boot definition and spring boot instance. This command creates both a new spring boot definition and spring boot instance.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, _ := tptctl_cmd.GetClientContext(cmd)

		// read spring boot config
		configContent, err := cli.ReadConfigContent(springbootConfigPath, springbootStdin)
		if err != nil {
			cli.Error("failed to read config", err)
			os.Exit(1)
		}

		// create spring boot based on version
		switch springbootVersion {
		case "v0":
			var springBootConfig config_v0.SpringBootConfig
			if err := yaml.UnmarshalStrict(configContent, &springBootConfig); err != nil {
				cli.Error("failed to unmarshal config file yaml content", err)
				os.Exit(1)
			}

			// create spring boot
			createdSpringBootSlice, err := springBootConfig.Create(
				apiClient,
				apiEndpoint,
			)
			if err != nil {
				cli.Error("failed to create spring boot", err)
				os.Exit(1)
			}

			// check the result of the create
			if createdSpringBootSlice == nil || len(*createdSpringBootSlice) == 0 {
				cli.Error("failed to create spring boot", errors.New("no spring boots received after create"))
				os.Exit(1)
			}
			createdSpringBoot := (*createdSpringBootSlice)[0]

			cli.Info(fmt.Sprintf("spring boot definition and instance with name %s created", *createdSpringBoot.SpringBoot.Name))
			cli.Complete(fmt.Sprintf("spring boot %s created", *createdSpringBoot.SpringBoot.Name))
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Create a new spring boot",
	SilenceUsage: true,
	Use:          "spring-boot",
}

func init() {
	CreateCmd.AddCommand(CreateSpringBootCmd)

	CreateSpringBootCmd.Flags().StringVarP(
		&springbootConfigPath,
		"config", "c", "", "Path to file with spring boot config.",
	)
	CreateSpringBootCmd.Flags().BoolVar(
		&springbootStdin,
		"stdin", false, "Read config from stdin instead of file.",
	)
	CreateSpringBootCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	CreateSpringBootCmd.Flags().StringVarP(
		&springbootVersion,
		"version", "v", "v0", "Version of spring boots object to create. One of: [v0]",
	)
}

// DeleteSpringBootCmd represents the command 'tptctl spring-boot delete spring-boot'
var DeleteSpringBootCmd = &cobra.Command{
	Example: "  # delete using a config file\n  tptctl spring-boot delete spring-boot --config path/to/config.yaml\n\n  # delete using name\n  tptctl spring-boot delete spring-boot --name some-spring-boot",
	Long:    "Delete an existing spring boot. This command deletes an existing spring boot definition and spring boot instance.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, _ := tptctl_cmd.GetClientContext(cmd)

		// flag validation
		if springbootConfigPath == "" {
			cli.Error("flag validation failed", errors.New("config file path is required"))
		}

		// read spring boot config
		configContent, err := cli.ReadConfigContent(springbootConfigPath, springbootStdin)
		if err != nil {
			cli.Error("failed to read config", err)
			os.Exit(1)
		}

		// delete spring boot based on version
		switch springbootVersion {
		case "v0":
			var springBootConfig config_v0.SpringBootConfig
			if err := yaml.UnmarshalStrict(configContent, &springBootConfig); err != nil {
				cli.Error("failed to unmarshal config file yaml content", err)
				os.Exit(1)
			}

			// delete spring boot
			_, err = springBootConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				cli.Error("failed to delete spring boot", err)
				os.Exit(1)
			}

			cli.Info(fmt.Sprintf("spring boot definition %s deleted", *springBootConfig.SpringBoot.Name))
			cli.Info(fmt.Sprintf("spring boot instance %s deleted", *springBootConfig.SpringBoot.Name))
			cli.Complete(fmt.Sprintf("spring boot %s deleted", *springBootConfig.SpringBoot.Name))
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Delete an existing spring boot",
	SilenceUsage: true,
	Use:          "spring-boot",
}

func init() {
	DeleteCmd.AddCommand(DeleteSpringBootCmd)

	DeleteSpringBootCmd.Flags().StringVarP(
		&springbootConfigPath,
		"config", "c", "", "Path to file with spring boot config.",
	)
	DeleteSpringBootCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	DeleteSpringBootCmd.Flags().StringVarP(
		&springbootVersion,
		"version", "v", "v0", "Version of spring boots object to delete. One of: [v0]",
	)
}

///////////////////////////////////////////////////////////////////////////////
// SpringBootDefinition
///////////////////////////////////////////////////////////////////////////////

// GetSpringBootDefinitionsCmd represents the command 'tptctl spring-boot get spring-boot-definitions'
var GetSpringBootDefinitionsCmd = &cobra.Command{
	Aliases: []string{"spring-boot-definition"},
	Example: "  # get all spring boot definitions\n  tptctl spring-boot get spring-boot-definitions\n\n  # get a specific spring boot definition\n  tptctl spring-boot get spring-boot-definition --name some-spring-boot-definition",
	Long:    "Get spring boot definitions from the system. Use --name to get a specific spring boot definition.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, requestedControlPlane := tptctl_cmd.GetClientContext(cmd)

		// flag validation
		if err := cli.ValidateConfigNameFlags(
			springbootConfigPath,
			springbootName,
			"spring boot definition",
		); err != nil {
			cli.Error("flag validation failed", err)
			os.Exit(1)
		}

		switch springbootVersion {
		case "v0":
			// load values
			springBootDefinitionConfig := config_v0.SpringBootDefinitionConfig{}
			if springbootConfigPath != "" || springbootStdin {
				configContent, err := cli.ReadConfigContent(springbootConfigPath, springbootStdin)
				if err != nil {
					cli.Error("failed to read config", err)
					os.Exit(1)
				}
				if err := yaml.UnmarshalStrict(configContent, &springBootDefinitionConfig); err != nil {
					cli.Error("failed to unmarshal config file yaml content", err)
					os.Exit(1)
				}
			} else if springbootName != "" {
				springBootDefinitionConfig = config_v0.SpringBootDefinitionConfig{
					SpringBootDefinition: config_v0.SpringBootDefinitionValues{
						Name: &springbootName,
					},
				}
			}

			// get spring boot definitions
			springBootDefinitions, err := springBootDefinitionConfig.Get(apiClient, apiEndpoint)
			if err != nil {
				cli.Error("failed to retrieve spring boot definitions", err)
				os.Exit(1)
			}

			// check if spring boot definition exists
			if len(*springBootDefinitions) == 0 {
				cli.Info(fmt.Sprintf(
					"no spring boot definitions found that are currently managed by %s threeport control plane",
					requestedControlPlane,
				))
				os.Exit(0)
			}

			// write the output
			switch springbootOutput {
			case "tabular":
				if err := outputGetv0SpringBootDefinitionsCmd(springBootDefinitions); err != nil {
					cli.Error("failed to produce output", err)
					os.Exit(1)
				}
			case "yaml":
				if err := cli.YamlObjectOutput(*springBootDefinitions); err != nil {
					cli.Error("failed to produce YAML output", err)
					os.Exit(1)
				}
			case "json":
				if err := cli.JsonObjectOutput(*springBootDefinitions); err != nil {
					cli.Error("failed to produce JSON output", err)
					os.Exit(1)
				}
			default:
				cli.Error("", fmt.Errorf("unrecognized output format: %s", springbootOutput))
				os.Exit(1)
			}
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Get spring boot definitions from the system",
	SilenceUsage: true,
	Use:          "spring-boot-definitions",
}

func init() {
	GetCmd.AddCommand(GetSpringBootDefinitionsCmd)

	GetSpringBootDefinitionsCmd.Flags().StringVarP(
		&springbootName,
		"name", "n", "", "Name of spring boot definition.",
	)
	GetSpringBootDefinitionsCmd.Flags().StringVarP(
		&springbootConfigPath,
		"config", "c", "", "Path to file with spring boot definition config.",
	)
	GetSpringBootDefinitionsCmd.Flags().StringVarP(
		&springbootVersion,
		"version", "v", "v0", "Version of spring boot definition objects to retrieve. One of: [v0]",
	)
	GetSpringBootDefinitionsCmd.Flags().StringVarP(
		&springbootOutput,
		"output", "o", "tabular", "Output format for spring boot definition objects. One of: [tabular, yaml, json]",
	)
	GetSpringBootDefinitionsCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
}

// CreateSpringBootDefinitionCmd represents the command 'tptctl spring-boot create spring-boot-definition'
var CreateSpringBootDefinitionCmd = &cobra.Command{
	Example: "  # create a new spring boot definition using a config file\n  tptctl spring-boot create spring-boot-definition --config path/to/config.yaml",
	Long:    "Create a new spring boot definition.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, _ := tptctl_cmd.GetClientContext(cmd)

		// read spring boot definition config
		configContent, err := cli.ReadConfigContent(springbootConfigPath, springbootStdin)
		if err != nil {
			cli.Error("failed to read config", err)
			os.Exit(1)
		}
		// create spring boot definition based on version
		switch springbootVersion {
		case "v0":
			var springBootDefinitionConfig config_v0.SpringBootDefinitionConfig
			if err := yaml.UnmarshalStrict(configContent, &springBootDefinitionConfig); err != nil {
				cli.Error("failed to unmarshal config file yaml content", err)
				os.Exit(1)
			}

			// create spring boot definition
			createdSpringBootDefinition, err := springBootDefinitionConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				cli.Error("failed to create spring boot definition", err)
				os.Exit(1)
			}

			cli.Complete(fmt.Sprintf("spring boot definition %s created", *createdSpringBootDefinition.SpringBootDefinition.Name))
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Create a new spring boot definition",
	SilenceUsage: true,
	Use:          "spring-boot-definition",
}

func init() {
	CreateCmd.AddCommand(CreateSpringBootDefinitionCmd)

	CreateSpringBootDefinitionCmd.Flags().StringVarP(
		&springbootConfigPath,
		"config", "c", "", "Path to file with spring boot definition config.",
	)
	CreateSpringBootDefinitionCmd.Flags().BoolVar(
		&springbootStdin,
		"stdin", false, "Read config from stdin instead of file.",
	)
	CreateSpringBootDefinitionCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	CreateSpringBootDefinitionCmd.Flags().StringVarP(
		&springbootVersion,
		"version", "v", "v0", "Version of spring boot definitions object to create. One of: [v0]",
	)
}

// ReplaceSpringBootDefinitionCmd represents the command 'tptctl spring-boot replace spring-boot-definition'
var ReplaceSpringBootDefinitionCmd = &cobra.Command{
	Example: "  # replace using a config file\n  tptctl spring-boot replace spring-boot-definition --config path/to/config.yaml --name some-spring-boot-definition",
	Long:    "Replace an existing spring boot definition.\n Note that the entire object will replaced with a PUT request.\n All fields must be provided in the config file.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, _ := tptctl_cmd.GetClientContext(cmd)

		// replace spring boot definition based on version
		switch springbootVersion {
		case "v0":
			var springBootDefinitionConfig config_v0.SpringBootDefinitionConfig
			// load spring boot definition config
			configContent, err := cli.ReadConfigContent(springbootConfigPath, springbootStdin)
			if err != nil {
				cli.Error("failed to read config", err)
				os.Exit(1)
			}
			if err := yaml.UnmarshalStrict(configContent, &springBootDefinitionConfig); err != nil {
				cli.Error("failed to unmarshal config file yaml content", err)
				os.Exit(1)
			}

			// replace spring boot definition
			updatedSpringBootDefinition, err := springBootDefinitionConfig.Replace(apiClient, apiEndpoint, springbootName)
			if err != nil {
				cli.Error("failed to update spring boot definition", err)
				os.Exit(1)
			}

			cli.Complete(fmt.Sprintf("spring boot definition %s updated", *updatedSpringBootDefinition.SpringBootDefinition.Name))
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Replace an existing spring boot definition",
	SilenceUsage: true,
	Use:          "spring-boot-definition",
}

func init() {
	ReplaceCmd.AddCommand(ReplaceSpringBootDefinitionCmd)

	ReplaceSpringBootDefinitionCmd.Flags().StringVarP(
		&springbootConfigPath,
		"config", "c", "", "Path to file with spring boot definition config.  The config file must be a complete config, i.e. the provided config will be used to replace the entire existing config for the object with a PUT request.",
	)
	ReplaceSpringBootDefinitionCmd.Flags().BoolVar(
		&springbootStdin,
		"stdin", false, "Read config from stdin instead of file.",
	)
	ReplaceSpringBootDefinitionCmd.Flags().StringVarP(
		&springbootName,
		"name", "n", "", "Name of existing spring boot definition to replace.  If the name in the spring boot definition config is different from the name provided here, the name of the existing object will be updated with the name in the config.",
	)
	ReplaceSpringBootDefinitionCmd.MarkFlagRequired("name")
	ReplaceSpringBootDefinitionCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	ReplaceSpringBootDefinitionCmd.Flags().StringVarP(
		&springbootVersion,
		"version", "v", "v0", "Version of spring boot definitions object to replace. One of: [v0]",
	)
}

// DeleteSpringBootDefinitionCmd represents the command 'tptctl spring-boot delete spring-boot-definition'
var DeleteSpringBootDefinitionCmd = &cobra.Command{
	Example: "  # delete using a config file\n  tptctl spring-boot delete spring-boot-definition --config path/to/config.yaml\n\n  # delete using name\n  tptctl spring-boot delete spring-boot-definition --name some-spring-boot-definition",
	Long:    "Delete an existing spring boot definition.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, _ := tptctl_cmd.GetClientContext(cmd)

		// flag validation
		if err := cli.ValidateConfigNameFlags(
			springbootConfigPath,
			springbootName,
			"spring boot definition",
		); err != nil {
			cli.Error("flag validation failed", err)
			os.Exit(1)
		}

		// delete spring boot definition based on version
		switch springbootVersion {
		case "v0":
			var springBootDefinitionConfig config_v0.SpringBootDefinitionConfig
			if springbootConfigPath != "" || springbootStdin {
				// load spring boot definition config
				configContent, err := cli.ReadConfigContent(springbootConfigPath, springbootStdin)
				if err != nil {
					cli.Error("failed to read config", err)
					os.Exit(1)
				}
				if err := yaml.UnmarshalStrict(configContent, &springBootDefinitionConfig); err != nil {
					cli.Error("failed to unmarshal config file yaml content", err)
					os.Exit(1)
				}
			} else {
				springBootDefinitionConfig = config_v0.SpringBootDefinitionConfig{
					SpringBootDefinition: config_v0.SpringBootDefinitionValues{
						Name: &springbootName,
					},
				}
			}

			// delete spring boot definition
			deletedSpringBootDefinition, err := springBootDefinitionConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				cli.Error("failed to delete spring boot definition", err)
				os.Exit(1)
			}

			cli.Complete(fmt.Sprintf("spring boot definition %s deleted", *deletedSpringBootDefinition.SpringBootDefinition.Name))
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Delete an existing spring boot definition",
	SilenceUsage: true,
	Use:          "spring-boot-definition",
}

func init() {
	DeleteCmd.AddCommand(DeleteSpringBootDefinitionCmd)

	DeleteSpringBootDefinitionCmd.Flags().StringVarP(
		&springbootConfigPath,
		"config", "c", "", "Path to file with spring boot definition config.",
	)
	DeleteSpringBootDefinitionCmd.Flags().StringVarP(
		&springbootName,
		"name", "n", "", "Name of spring boot definition.",
	)
	DeleteSpringBootDefinitionCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	DeleteSpringBootDefinitionCmd.Flags().StringVarP(
		&springbootVersion,
		"version", "v", "v0", "Version of spring boot definitions object to delete. One of: [v0]",
	)
}

///////////////////////////////////////////////////////////////////////////////
// SpringBootInstance
///////////////////////////////////////////////////////////////////////////////

// GetSpringBootInstancesCmd represents the command 'tptctl spring-boot get spring-boot-instances'
var GetSpringBootInstancesCmd = &cobra.Command{
	Aliases: []string{"spring-boot-instance"},
	Example: "  # get all spring boot instances\n  tptctl spring-boot get spring-boot-instances\n\n  # get a specific spring boot instance\n  tptctl spring-boot get spring-boot-instance --name some-spring-boot-instance",
	Long:    "Get spring boot instances from the system. Use --name to get a specific spring boot instance.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, requestedControlPlane := tptctl_cmd.GetClientContext(cmd)

		// flag validation
		if err := cli.ValidateConfigNameFlags(
			springbootConfigPath,
			springbootName,
			"spring boot instance",
		); err != nil {
			cli.Error("flag validation failed", err)
			os.Exit(1)
		}

		switch springbootVersion {
		case "v0":
			// load values
			springBootInstanceConfig := config_v0.SpringBootInstanceConfig{}
			if springbootConfigPath != "" || springbootStdin {
				configContent, err := cli.ReadConfigContent(springbootConfigPath, springbootStdin)
				if err != nil {
					cli.Error("failed to read config", err)
					os.Exit(1)
				}
				if err := yaml.UnmarshalStrict(configContent, &springBootInstanceConfig); err != nil {
					cli.Error("failed to unmarshal config file yaml content", err)
					os.Exit(1)
				}
			} else if springbootName != "" {
				springBootInstanceConfig = config_v0.SpringBootInstanceConfig{
					SpringBootInstance: config_v0.SpringBootInstanceValues{
						Name: &springbootName,
					},
				}
			}

			// get spring boot instances
			springBootInstances, err := springBootInstanceConfig.Get(apiClient, apiEndpoint)
			if err != nil {
				cli.Error("failed to retrieve spring boot instances", err)
				os.Exit(1)
			}

			// check if spring boot instance exists
			if len(*springBootInstances) == 0 {
				cli.Info(fmt.Sprintf(
					"no spring boot instances found that are currently managed by %s threeport control plane",
					requestedControlPlane,
				))
				os.Exit(0)
			}

			// write the output
			switch springbootOutput {
			case "tabular":
				if err := outputGetv0SpringBootInstancesCmd(springBootInstances); err != nil {
					cli.Error("failed to produce output", err)
					os.Exit(1)
				}
			case "yaml":
				if err := cli.YamlObjectOutput(*springBootInstances); err != nil {
					cli.Error("failed to produce YAML output", err)
					os.Exit(1)
				}
			case "json":
				if err := cli.JsonObjectOutput(*springBootInstances); err != nil {
					cli.Error("failed to produce JSON output", err)
					os.Exit(1)
				}
			default:
				cli.Error("", fmt.Errorf("unrecognized output format: %s", springbootOutput))
				os.Exit(1)
			}
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Get spring boot instances from the system",
	SilenceUsage: true,
	Use:          "spring-boot-instances",
}

func init() {
	GetCmd.AddCommand(GetSpringBootInstancesCmd)

	GetSpringBootInstancesCmd.Flags().StringVarP(
		&springbootName,
		"name", "n", "", "Name of spring boot instance.",
	)
	GetSpringBootInstancesCmd.Flags().StringVarP(
		&springbootConfigPath,
		"config", "c", "", "Path to file with spring boot instance config.",
	)
	GetSpringBootInstancesCmd.Flags().StringVarP(
		&springbootVersion,
		"version", "v", "v0", "Version of spring boot instance objects to retrieve. One of: [v0]",
	)
	GetSpringBootInstancesCmd.Flags().StringVarP(
		&springbootOutput,
		"output", "o", "tabular", "Output format for spring boot instance objects. One of: [tabular, yaml, json]",
	)
	GetSpringBootInstancesCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
}

// CreateSpringBootInstanceCmd represents the command 'tptctl spring-boot create spring-boot-instance'
var CreateSpringBootInstanceCmd = &cobra.Command{
	Example: "  # create a new spring boot instance using a config file\n  tptctl spring-boot create spring-boot-instance --config path/to/config.yaml",
	Long:    "Create a new spring boot instance.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, _ := tptctl_cmd.GetClientContext(cmd)

		// read spring boot instance config
		configContent, err := cli.ReadConfigContent(springbootConfigPath, springbootStdin)
		if err != nil {
			cli.Error("failed to read config", err)
			os.Exit(1)
		}
		// create spring boot instance based on version
		switch springbootVersion {
		case "v0":
			var springBootInstanceConfig config_v0.SpringBootInstanceConfig
			if err := yaml.UnmarshalStrict(configContent, &springBootInstanceConfig); err != nil {
				cli.Error("failed to unmarshal config file yaml content", err)
				os.Exit(1)
			}

			// create spring boot instance
			createdSpringBootInstance, err := springBootInstanceConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				cli.Error("failed to create spring boot instance", err)
				os.Exit(1)
			}

			cli.Complete(fmt.Sprintf("spring boot instance %s created", *createdSpringBootInstance.SpringBootInstance.Name))
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Create a new spring boot instance",
	SilenceUsage: true,
	Use:          "spring-boot-instance",
}

func init() {
	CreateCmd.AddCommand(CreateSpringBootInstanceCmd)

	CreateSpringBootInstanceCmd.Flags().StringVarP(
		&springbootConfigPath,
		"config", "c", "", "Path to file with spring boot instance config.",
	)
	CreateSpringBootInstanceCmd.Flags().BoolVar(
		&springbootStdin,
		"stdin", false, "Read config from stdin instead of file.",
	)
	CreateSpringBootInstanceCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	CreateSpringBootInstanceCmd.Flags().StringVarP(
		&springbootVersion,
		"version", "v", "v0", "Version of spring boot instances object to create. One of: [v0]",
	)
}

// ReplaceSpringBootInstanceCmd represents the command 'tptctl spring-boot replace spring-boot-instance'
var ReplaceSpringBootInstanceCmd = &cobra.Command{
	Example: "  # replace using a config file\n  tptctl spring-boot replace spring-boot-instance --config path/to/config.yaml --name some-spring-boot-instance",
	Long:    "Replace an existing spring boot instance.\n Note that the entire object will replaced with a PUT request.\n All fields must be provided in the config file.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, _ := tptctl_cmd.GetClientContext(cmd)

		// replace spring boot instance based on version
		switch springbootVersion {
		case "v0":
			var springBootInstanceConfig config_v0.SpringBootInstanceConfig
			// load spring boot instance config
			configContent, err := cli.ReadConfigContent(springbootConfigPath, springbootStdin)
			if err != nil {
				cli.Error("failed to read config", err)
				os.Exit(1)
			}
			if err := yaml.UnmarshalStrict(configContent, &springBootInstanceConfig); err != nil {
				cli.Error("failed to unmarshal config file yaml content", err)
				os.Exit(1)
			}

			// replace spring boot instance
			updatedSpringBootInstance, err := springBootInstanceConfig.Replace(apiClient, apiEndpoint, springbootName)
			if err != nil {
				cli.Error("failed to update spring boot instance", err)
				os.Exit(1)
			}

			cli.Complete(fmt.Sprintf("spring boot instance %s updated", *updatedSpringBootInstance.SpringBootInstance.Name))
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Replace an existing spring boot instance",
	SilenceUsage: true,
	Use:          "spring-boot-instance",
}

func init() {
	ReplaceCmd.AddCommand(ReplaceSpringBootInstanceCmd)

	ReplaceSpringBootInstanceCmd.Flags().StringVarP(
		&springbootConfigPath,
		"config", "c", "", "Path to file with spring boot instance config.  The config file must be a complete config, i.e. the provided config will be used to replace the entire existing config for the object with a PUT request.",
	)
	ReplaceSpringBootInstanceCmd.Flags().BoolVar(
		&springbootStdin,
		"stdin", false, "Read config from stdin instead of file.",
	)
	ReplaceSpringBootInstanceCmd.Flags().StringVarP(
		&springbootName,
		"name", "n", "", "Name of existing spring boot instance to replace.  If the name in the spring boot instance config is different from the name provided here, the name of the existing object will be updated with the name in the config.",
	)
	ReplaceSpringBootInstanceCmd.MarkFlagRequired("name")
	ReplaceSpringBootInstanceCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	ReplaceSpringBootInstanceCmd.Flags().StringVarP(
		&springbootVersion,
		"version", "v", "v0", "Version of spring boot instances object to replace. One of: [v0]",
	)
}

// DeleteSpringBootInstanceCmd represents the command 'tptctl spring-boot delete spring-boot-instance'
var DeleteSpringBootInstanceCmd = &cobra.Command{
	Example: "  # delete using a config file\n  tptctl spring-boot delete spring-boot-instance --config path/to/config.yaml\n\n  # delete using name\n  tptctl spring-boot delete spring-boot-instance --name some-spring-boot-instance",
	Long:    "Delete an existing spring boot instance.",
	PreRun:  CommandPreRunFunc,
	Run: func(cmd *cobra.Command, args []string) {
		apiClient, _, apiEndpoint, _ := tptctl_cmd.GetClientContext(cmd)

		// flag validation
		if err := cli.ValidateConfigNameFlags(
			springbootConfigPath,
			springbootName,
			"spring boot instance",
		); err != nil {
			cli.Error("flag validation failed", err)
			os.Exit(1)
		}

		// delete spring boot instance based on version
		switch springbootVersion {
		case "v0":
			var springBootInstanceConfig config_v0.SpringBootInstanceConfig
			if springbootConfigPath != "" || springbootStdin {
				// load spring boot instance config
				configContent, err := cli.ReadConfigContent(springbootConfigPath, springbootStdin)
				if err != nil {
					cli.Error("failed to read config", err)
					os.Exit(1)
				}
				if err := yaml.UnmarshalStrict(configContent, &springBootInstanceConfig); err != nil {
					cli.Error("failed to unmarshal config file yaml content", err)
					os.Exit(1)
				}
			} else {
				springBootInstanceConfig = config_v0.SpringBootInstanceConfig{
					SpringBootInstance: config_v0.SpringBootInstanceValues{
						Name: &springbootName,
					},
				}
			}

			// delete spring boot instance
			deletedSpringBootInstance, err := springBootInstanceConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				cli.Error("failed to delete spring boot instance", err)
				os.Exit(1)
			}

			cli.Complete(fmt.Sprintf("spring boot instance %s deleted", *deletedSpringBootInstance.SpringBootInstance.Name))
		default:
			cli.Error("", errors.New("unrecognized object version"))
			os.Exit(1)
		}
	},
	Short:        "Delete an existing spring boot instance",
	SilenceUsage: true,
	Use:          "spring-boot-instance",
}

func init() {
	DeleteCmd.AddCommand(DeleteSpringBootInstanceCmd)

	DeleteSpringBootInstanceCmd.Flags().StringVarP(
		&springbootConfigPath,
		"config", "c", "", "Path to file with spring boot instance config.",
	)
	DeleteSpringBootInstanceCmd.Flags().StringVarP(
		&springbootName,
		"name", "n", "", "Name of spring boot instance.",
	)
	DeleteSpringBootInstanceCmd.Flags().StringVarP(
		&cliArgs.ControlPlaneName,
		"control-plane-name", "i", "", "Optional. Name of control plane. Will default to current control plane if not provided.",
	)
	DeleteSpringBootInstanceCmd.Flags().StringVarP(
		&springbootVersion,
		"version", "v", "v0", "Version of spring boot instances object to delete. One of: [v0]",
	)
}
