// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import (
	"fmt"
	"os"
	config_v0 "spring-boot-threeport-module/pkg/config/v0"
	"text/tabwriter"
)

// outputGetv0SpringBootsCmd produces the tabular output for the
// 'get spring-boots' command.
func outputGetv0SpringBootsCmd(
	springBoots *[]config_v0.SpringBootConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	// TODO: add columns for each field that users should see
	// TODO: available fields are defined in the SpringBootValues object in pkg/config/v0/spring_boot.go
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, springBoot := range *springBoots {
		fmt.Fprintln(
			writer,
			*springBoot.SpringBoot.Name, "\t",
			*springBoot.SpringBoot.Age,
		)
	}
	writer.Flush()

	return nil
}

// outputGetv0SpringBootDefinitionsCmd produces the tabular output for the
// `get spring-boot-definitions` command.
func outputGetv0SpringBootDefinitionsCmd(
	springBootDefinitions *[]config_v0.SpringBootDefinitionConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	// TODO: add columns for each field that users should see
	// TODO: available fields are defined in the SpringBootDefinitionValues object in pkg/config/v0/spring_boot_definition.go
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, springBootDefinition := range *springBootDefinitions {
		fmt.Fprintln(
			writer,
			*springBootDefinition.SpringBootDefinition.Name, "\t",
			*springBootDefinition.SpringBootDefinition.Age,
		)
	}
	writer.Flush()

	return nil
}

// outputGetv0SpringBootInstancesCmd produces the tabular output for the
// `get spring-boot-instances` command.
func outputGetv0SpringBootInstancesCmd(
	springBootInstances *[]config_v0.SpringBootInstanceConfig,
) error {
	writer := tabwriter.NewWriter(os.Stdout, 4, 4, 4, ' ', 0)
	// TODO: add columns for each field that users should see
	// TODO: available fields are defined in the SpringBootInstanceValues object in pkg/config/v0/spring_boot_instance.go
	fmt.Fprintln(writer, "NAME\t AGE")
	for _, springBootInstance := range *springBootInstances {
		fmt.Fprintln(
			writer,
			*springBootInstance.SpringBootInstance.Name, "\t",
			*springBootInstance.SpringBootInstance.Age,
		)
	}
	writer.Flush()

	return nil
}
