// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package cmd

import (
	"fmt"
	cobra "github.com/spf13/cobra"
	version "spring-boot-threeport-module/internal/version"
)

// versionCmd represents the version command for the SpringBoot plugin
var versionCmd = &cobra.Command{
	Long: "Print the version of spring-boot",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println(version.GetVersion())
	},
	Short: "Print the version of spring-boot",
	Use:   "version",
}

func init() {
	rootCmd.AddCommand(versionCmd)
}
