// boilerplate generated by 'threeport-sdk gen' - do not edit

package versions

import (
	tpapiserver_lib "github.com/threeport/threeport/pkg/api-server/lib/v0"
	tpapi_lib "github.com/threeport/threeport/pkg/api/lib/v0"
	"reflect"
	apiserver_v0 "spring-boot-threeport-module/pkg/api-server/v0"
	api_v0 "spring-boot-threeport-module/pkg/api/v0"
)

// AddSpringBootDefinitionVersions adds field validation info and adds it
// to the REST API versions.
func AddSpringBootDefinitionVersions() {
	apiserver_v0.SpringBootDefinitionTaggedFields[string(tpapi_lib.ValidateTag)] = &tpapiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(tpapi_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	tpapiserver_lib.ParseStruct(
		string(tpapi_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.SpringBootDefinition)),
		"",
		tpapiserver_lib.Translate,
		apiserver_v0.SpringBootDefinitionTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := tpapiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeSpringBootDefinition),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	tpapiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.SpringBootDefinitionTaggedFields[string(tpapi_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	tpapiserver_lib.AddObjectVersion(versionObj)
}

// AddSpringBootInstanceVersions adds field validation info and adds it
// to the REST API versions.
func AddSpringBootInstanceVersions() {
	apiserver_v0.SpringBootInstanceTaggedFields[string(tpapi_lib.ValidateTag)] = &tpapiserver_lib.FieldsByTag{
		Optional:             []string{},
		OptionalAssociations: []string{},
		Required:             []string{},
		TagName:              string(tpapi_lib.ValidateTag),
	}

	// parse struct and populate the FieldsByTag object
	tpapiserver_lib.ParseStruct(
		string(tpapi_lib.ValidateTag),
		reflect.ValueOf(new(api_v0.SpringBootInstance)),
		"",
		tpapiserver_lib.Translate,
		apiserver_v0.SpringBootInstanceTaggedFields,
	)

	// create a version object which contains the object name and versions
	versionObj := tpapiserver_lib.VersionObject{
		Object:  string(api_v0.ObjectTypeSpringBootInstance),
		Version: "v0",
	}

	// add the object tagged fields to the global tagged fields map
	tpapiserver_lib.ObjectTaggedFields[versionObj] = apiserver_v0.SpringBootInstanceTaggedFields[string(tpapi_lib.ValidateTag)]

	// add the object tagged fields to the rest API version
	tpapiserver_lib.AddObjectVersion(versionObj)
}
