// boilerplate generated by 'threeport-sdk gen' - do not edit

package notif

const (
	SpringbootStreamName = "threeport-io_springbootStream"

	SpringBootDefinitionSubject       = "threeport-io_springBootDefinition.*"
	SpringBootDefinitionCreateSubject = "threeport-io_springBootDefinition.create"
	SpringBootDefinitionUpdateSubject = "threeport-io_springBootDefinition.update"
	SpringBootDefinitionDeleteSubject = "threeport-io_springBootDefinition.delete"

	SpringBootInstanceSubject       = "threeport-io_springBootInstance.*"
	SpringBootInstanceCreateSubject = "threeport-io_springBootInstance.create"
	SpringBootInstanceUpdateSubject = "threeport-io_springBootInstance.update"
	SpringBootInstanceDeleteSubject = "threeport-io_springBootInstance.delete"
)

// GetSpringBootDefinitionSubjects returns the NATS subjects
// for spring boot definitions.
func GetSpringBootDefinitionSubjects() []string {
	return []string{
		SpringBootDefinitionCreateSubject,
		SpringBootDefinitionUpdateSubject,
		SpringBootDefinitionDeleteSubject,
	}
}

// GetSpringBootInstanceSubjects returns the NATS subjects
// for spring boot instances.
func GetSpringBootInstanceSubjects() []string {
	return []string{
		SpringBootInstanceCreateSubject,
		SpringBootInstanceUpdateSubject,
		SpringBootInstanceDeleteSubject,
	}
}

// GetSpringbootSubjects returns the NATS subjects
// for all springboot objects.
func GetSpringbootSubjects() []string {
	var springbootSubjects []string

	springbootSubjects = append(springbootSubjects, GetSpringBootDefinitionSubjects()...)
	springbootSubjects = append(springbootSubjects, GetSpringBootInstanceSubjects()...)

	return springbootSubjects
}
