// boilerplate generated by 'threeport-sdk gen' - do not edit

package v0

import (
	"bytes"
	"encoding/json"
	"fmt"
	tpapiserver_lib "github.com/threeport/threeport/pkg/api-server/lib/v0"
	tpclient_lib "github.com/threeport/threeport/pkg/client/lib/v0"
	tputil "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
	v0 "spring-boot-threeport-module/pkg/api/v0"
)

// GetSpringBootDefinitions fetches all spring boot definitions.
func GetSpringBootDefinitions(apiClient *http.Client, apiAddr string) (*[]v0.SpringBootDefinition, error) {
	var springBootDefinitions []v0.SpringBootDefinition

	allPagesReceived := false
	var allPageData []tpapiserver_lib.Object
	nextCursor := uint(0)
	queryId := ""
	for !allPagesReceived {
		url := fmt.Sprintf("%s%s", apiAddr, v0.PathSpringBootDefinitions)
		if queryId != "" {
			url = fmt.Sprintf("%s%s?queryid=%s&cursor=%d", apiAddr, v0.PathSpringBootDefinitions, queryId, nextCursor)
		}

		response, err := tpclient_lib.GetResponse(
			apiClient,
			url,
			http.MethodGet,
			new(bytes.Buffer),
			map[string]string{},
			http.StatusOK,
		)
		if err != nil {
			return &springBootDefinitions, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
		}

		allPageData = append(allPageData, response.Data...)

		if response.Meta.Pagination.HasMore {
			nextCursor = response.Meta.Pagination.NextCursor
			queryId = response.Meta.Pagination.QueryId
		} else {
			allPagesReceived = true
		}
	}

	jsonData, err := json.Marshal(allPageData)
	if err != nil {
		return &springBootDefinitions, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&springBootDefinitions); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return &springBootDefinitions, nil
}

// GetSpringBootDefinitionByID fetches a spring boot definition by ID.
func GetSpringBootDefinitionByID(apiClient *http.Client, apiAddr string, id uint) (*v0.SpringBootDefinition, error) {
	var springBootDefinition v0.SpringBootDefinition

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s/%d", apiAddr, v0.PathSpringBootDefinitions, id),
		http.MethodGet,
		new(bytes.Buffer),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return &springBootDefinition, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return &springBootDefinition, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&springBootDefinition); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return &springBootDefinition, nil
}

// GetSpringBootDefinitionsByQueryString fetches spring boot definitions by provided query string.
func GetSpringBootDefinitionsByQueryString(apiClient *http.Client, apiAddr string, queryString string) (*[]v0.SpringBootDefinition, error) {
	var springBootDefinitions []v0.SpringBootDefinition

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s?%s", apiAddr, v0.PathSpringBootDefinitions, queryString),
		http.MethodGet,
		new(bytes.Buffer),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return &springBootDefinitions, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data)
	if err != nil {
		return &springBootDefinitions, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&springBootDefinitions); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return &springBootDefinitions, nil
}

// GetSpringBootDefinitionByName fetches a spring boot definition by name.
func GetSpringBootDefinitionByName(apiClient *http.Client, apiAddr, name string) (*v0.SpringBootDefinition, error) {
	var springBootDefinitions []v0.SpringBootDefinition

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s?name=%s", apiAddr, v0.PathSpringBootDefinitions, name),
		http.MethodGet,
		new(bytes.Buffer),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return &v0.SpringBootDefinition{}, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data)
	if err != nil {
		return &v0.SpringBootDefinition{}, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&springBootDefinitions); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	switch {
	case len(springBootDefinitions) < 1:
		return &v0.SpringBootDefinition{}, tpclient_lib.ErrObjectNotFound
	case len(springBootDefinitions) > 1:
		return &v0.SpringBootDefinition{}, fmt.Errorf("more than one spring boot definition with name %s returned", name)
	}

	return &springBootDefinitions[0], nil
}

// CreateSpringBootDefinition creates a new spring boot definition.
func CreateSpringBootDefinition(apiClient *http.Client, apiAddr string, springBootDefinition *v0.SpringBootDefinition) (*v0.SpringBootDefinition, error) {
	tpclient_lib.ReplaceAssociatedObjectsWithNil(springBootDefinition)
	jsonSpringBootDefinition, err := tputil.MarshalObject(springBootDefinition)
	if err != nil {
		return springBootDefinition, fmt.Errorf("failed to marshal provided object to JSON: %w", err)
	}

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s", apiAddr, v0.PathSpringBootDefinitions),
		http.MethodPost,
		bytes.NewBuffer(jsonSpringBootDefinition),
		map[string]string{},
		http.StatusCreated,
	)
	if err != nil {
		return springBootDefinition, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return springBootDefinition, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&springBootDefinition); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return springBootDefinition, nil
}

// UpdateSpringBootDefinition updates a spring boot definition with a PATCH request.
func UpdateSpringBootDefinition(apiClient *http.Client, apiAddr string, springBootDefinition *v0.SpringBootDefinition) (*v0.SpringBootDefinition, error) {
	tpclient_lib.ReplaceAssociatedObjectsWithNil(springBootDefinition)
	// capture the object ID, make a copy of the object, then remove fields that
	// cannot be updated in the API
	springBootDefinitionID := *springBootDefinition.ID
	payloadSpringBootDefinition := *springBootDefinition
	payloadSpringBootDefinition.ID = nil
	payloadSpringBootDefinition.CreatedAt = nil
	payloadSpringBootDefinition.UpdatedAt = nil

	jsonSpringBootDefinition, err := tputil.MarshalObject(payloadSpringBootDefinition)
	if err != nil {
		return springBootDefinition, fmt.Errorf("failed to marshal provided object to JSON: %w", err)
	}

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s/%d", apiAddr, v0.PathSpringBootDefinitions, springBootDefinitionID),
		http.MethodPatch,
		bytes.NewBuffer(jsonSpringBootDefinition),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return springBootDefinition, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return springBootDefinition, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&payloadSpringBootDefinition); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	payloadSpringBootDefinition.ID = &springBootDefinitionID
	return &payloadSpringBootDefinition, nil
}

// ReplaceSpringBootDefinition updates a spring boot definition with a PUT request.
func ReplaceSpringBootDefinition(apiClient *http.Client, apiAddr string, springBootDefinition *v0.SpringBootDefinition) (*v0.SpringBootDefinition, error) {
	tpclient_lib.ReplaceAssociatedObjectsWithNil(springBootDefinition)
	// capture the object ID, make a copy of the object, then remove fields that
	// cannot be updated in the API
	springBootDefinitionID := *springBootDefinition.ID
	payloadSpringBootDefinition := *springBootDefinition
	payloadSpringBootDefinition.ID = nil
	payloadSpringBootDefinition.CreatedAt = nil
	payloadSpringBootDefinition.UpdatedAt = nil

	jsonSpringBootDefinition, err := tputil.MarshalObject(payloadSpringBootDefinition)
	if err != nil {
		return springBootDefinition, fmt.Errorf("failed to marshal provided object to JSON: %w", err)
	}

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s/%d", apiAddr, v0.PathSpringBootDefinitions, springBootDefinitionID),
		http.MethodPut,
		bytes.NewBuffer(jsonSpringBootDefinition),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return springBootDefinition, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return springBootDefinition, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&payloadSpringBootDefinition); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	payloadSpringBootDefinition.ID = &springBootDefinitionID
	return &payloadSpringBootDefinition, nil
}

// DeleteSpringBootDefinition deletes a spring boot definition by ID.
func DeleteSpringBootDefinition(apiClient *http.Client, apiAddr string, id uint) (*v0.SpringBootDefinition, error) {
	var springBootDefinition v0.SpringBootDefinition

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s/%d", apiAddr, v0.PathSpringBootDefinitions, id),
		http.MethodDelete,
		new(bytes.Buffer),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return &springBootDefinition, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return &springBootDefinition, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&springBootDefinition); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return &springBootDefinition, nil
}

// GetSpringBootInstances fetches all spring boot instances.
func GetSpringBootInstances(apiClient *http.Client, apiAddr string) (*[]v0.SpringBootInstance, error) {
	var springBootInstances []v0.SpringBootInstance

	allPagesReceived := false
	var allPageData []tpapiserver_lib.Object
	nextCursor := uint(0)
	queryId := ""
	for !allPagesReceived {
		url := fmt.Sprintf("%s%s", apiAddr, v0.PathSpringBootInstances)
		if queryId != "" {
			url = fmt.Sprintf("%s%s?queryid=%s&cursor=%d", apiAddr, v0.PathSpringBootInstances, queryId, nextCursor)
		}

		response, err := tpclient_lib.GetResponse(
			apiClient,
			url,
			http.MethodGet,
			new(bytes.Buffer),
			map[string]string{},
			http.StatusOK,
		)
		if err != nil {
			return &springBootInstances, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
		}

		allPageData = append(allPageData, response.Data...)

		if response.Meta.Pagination.HasMore {
			nextCursor = response.Meta.Pagination.NextCursor
			queryId = response.Meta.Pagination.QueryId
		} else {
			allPagesReceived = true
		}
	}

	jsonData, err := json.Marshal(allPageData)
	if err != nil {
		return &springBootInstances, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&springBootInstances); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return &springBootInstances, nil
}

// GetSpringBootInstanceByID fetches a spring boot instance by ID.
func GetSpringBootInstanceByID(apiClient *http.Client, apiAddr string, id uint) (*v0.SpringBootInstance, error) {
	var springBootInstance v0.SpringBootInstance

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s/%d", apiAddr, v0.PathSpringBootInstances, id),
		http.MethodGet,
		new(bytes.Buffer),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return &springBootInstance, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return &springBootInstance, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&springBootInstance); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return &springBootInstance, nil
}

// GetSpringBootInstancesByQueryString fetches spring boot instances by provided query string.
func GetSpringBootInstancesByQueryString(apiClient *http.Client, apiAddr string, queryString string) (*[]v0.SpringBootInstance, error) {
	var springBootInstances []v0.SpringBootInstance

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s?%s", apiAddr, v0.PathSpringBootInstances, queryString),
		http.MethodGet,
		new(bytes.Buffer),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return &springBootInstances, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data)
	if err != nil {
		return &springBootInstances, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&springBootInstances); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return &springBootInstances, nil
}

// GetSpringBootInstanceByName fetches a spring boot instance by name.
func GetSpringBootInstanceByName(apiClient *http.Client, apiAddr, name string) (*v0.SpringBootInstance, error) {
	var springBootInstances []v0.SpringBootInstance

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s?name=%s", apiAddr, v0.PathSpringBootInstances, name),
		http.MethodGet,
		new(bytes.Buffer),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return &v0.SpringBootInstance{}, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data)
	if err != nil {
		return &v0.SpringBootInstance{}, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&springBootInstances); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	switch {
	case len(springBootInstances) < 1:
		return &v0.SpringBootInstance{}, tpclient_lib.ErrObjectNotFound
	case len(springBootInstances) > 1:
		return &v0.SpringBootInstance{}, fmt.Errorf("more than one spring boot instance with name %s returned", name)
	}

	return &springBootInstances[0], nil
}

// CreateSpringBootInstance creates a new spring boot instance.
func CreateSpringBootInstance(apiClient *http.Client, apiAddr string, springBootInstance *v0.SpringBootInstance) (*v0.SpringBootInstance, error) {
	tpclient_lib.ReplaceAssociatedObjectsWithNil(springBootInstance)
	jsonSpringBootInstance, err := tputil.MarshalObject(springBootInstance)
	if err != nil {
		return springBootInstance, fmt.Errorf("failed to marshal provided object to JSON: %w", err)
	}

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s", apiAddr, v0.PathSpringBootInstances),
		http.MethodPost,
		bytes.NewBuffer(jsonSpringBootInstance),
		map[string]string{},
		http.StatusCreated,
	)
	if err != nil {
		return springBootInstance, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return springBootInstance, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&springBootInstance); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return springBootInstance, nil
}

// UpdateSpringBootInstance updates a spring boot instance with a PATCH request.
func UpdateSpringBootInstance(apiClient *http.Client, apiAddr string, springBootInstance *v0.SpringBootInstance) (*v0.SpringBootInstance, error) {
	tpclient_lib.ReplaceAssociatedObjectsWithNil(springBootInstance)
	// capture the object ID, make a copy of the object, then remove fields that
	// cannot be updated in the API
	springBootInstanceID := *springBootInstance.ID
	payloadSpringBootInstance := *springBootInstance
	payloadSpringBootInstance.ID = nil
	payloadSpringBootInstance.CreatedAt = nil
	payloadSpringBootInstance.UpdatedAt = nil

	jsonSpringBootInstance, err := tputil.MarshalObject(payloadSpringBootInstance)
	if err != nil {
		return springBootInstance, fmt.Errorf("failed to marshal provided object to JSON: %w", err)
	}

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s/%d", apiAddr, v0.PathSpringBootInstances, springBootInstanceID),
		http.MethodPatch,
		bytes.NewBuffer(jsonSpringBootInstance),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return springBootInstance, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return springBootInstance, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&payloadSpringBootInstance); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	payloadSpringBootInstance.ID = &springBootInstanceID
	return &payloadSpringBootInstance, nil
}

// ReplaceSpringBootInstance updates a spring boot instance with a PUT request.
func ReplaceSpringBootInstance(apiClient *http.Client, apiAddr string, springBootInstance *v0.SpringBootInstance) (*v0.SpringBootInstance, error) {
	tpclient_lib.ReplaceAssociatedObjectsWithNil(springBootInstance)
	// capture the object ID, make a copy of the object, then remove fields that
	// cannot be updated in the API
	springBootInstanceID := *springBootInstance.ID
	payloadSpringBootInstance := *springBootInstance
	payloadSpringBootInstance.ID = nil
	payloadSpringBootInstance.CreatedAt = nil
	payloadSpringBootInstance.UpdatedAt = nil

	jsonSpringBootInstance, err := tputil.MarshalObject(payloadSpringBootInstance)
	if err != nil {
		return springBootInstance, fmt.Errorf("failed to marshal provided object to JSON: %w", err)
	}

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s/%d", apiAddr, v0.PathSpringBootInstances, springBootInstanceID),
		http.MethodPut,
		bytes.NewBuffer(jsonSpringBootInstance),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return springBootInstance, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return springBootInstance, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&payloadSpringBootInstance); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	payloadSpringBootInstance.ID = &springBootInstanceID
	return &payloadSpringBootInstance, nil
}

// DeleteSpringBootInstance deletes a spring boot instance by ID.
func DeleteSpringBootInstance(apiClient *http.Client, apiAddr string, id uint) (*v0.SpringBootInstance, error) {
	var springBootInstance v0.SpringBootInstance

	response, err := tpclient_lib.GetResponse(
		apiClient,
		fmt.Sprintf("%s%s/%d", apiAddr, v0.PathSpringBootInstances, id),
		http.MethodDelete,
		new(bytes.Buffer),
		map[string]string{},
		http.StatusOK,
	)
	if err != nil {
		return &springBootInstance, fmt.Errorf("call to threeport API returned unexpected response: %w", err)
	}

	jsonData, err := json.Marshal(response.Data[0])
	if err != nil {
		return &springBootInstance, fmt.Errorf("failed to marshal response data from threeport API: %w", err)
	}

	decoder := json.NewDecoder(bytes.NewReader(jsonData))
	decoder.UseNumber()
	if err := decoder.Decode(&springBootInstance); err != nil {
		return nil, fmt.Errorf("failed to decode object in response data from threeport API: %w", err)
	}

	return &springBootInstance, nil
}
