// boilerplate generated by 'threeport-sdk gen' - do not edit

package handlers

import (
	"errors"
	"fmt"
	crdbgorm "github.com/cockroachdb/cockroach-go/v2/crdb/crdbgorm"
	echo "github.com/labstack/echo/v4"
	tpapiserver_lib "github.com/threeport/threeport/pkg/api-server/lib/v0"
	tphandlers_v0 "github.com/threeport/threeport/pkg/api-server/v0/handlers"
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	notifications "github.com/threeport/threeport/pkg/notifications/v0"
	tputil_v0 "github.com/threeport/threeport/pkg/util/v0"
	zap "go.uber.org/zap"
	gorm "gorm.io/gorm"
	"net/http"
	notif "spring-boot-threeport-module/internal/springboot/notif"
	api_v0 "spring-boot-threeport-module/pkg/api/v0"
	"time"
)

///////////////////////////////////////////////////////////////////////////////
// SpringBootDefinition
///////////////////////////////////////////////////////////////////////////////

// @Summary GetSpringBootDefinitionVersions gets the supported versions for the spring boot definition API.
// @Description Get the supported API versions for spring boot definitions.
// @ID springBootDefinition-get-versions
// @Produce json
// @Success 200 {object} tpapiserver_lib.ApiObjectVersions "OK"
// @Router /threeport-io/spring-boot-definitions/versions [GET]
func (h Handler) GetSpringBootDefinitionVersions(c echo.Context) error {
	return c.JSON(http.StatusOK, tpapiserver_lib.ObjectVersions[string(api_v0.ObjectTypeSpringBootDefinition)])
}

// @Summary adds a new spring boot definition.
// @Description Add a new spring boot definition to the Threeport database.
// @ID add-v0-springBootDefinition
// @Accept json
// @Produce json
// @Param springBootDefinition body api_v0.SpringBootDefinition true "SpringBootDefinition object"
// @Success 201 {object} v0.Response "Created"
// @Failure 400 {object} v0.Response "Bad Request"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/spring-boot-definitions [POST]
func (h Handler) AddSpringBootDefinition(c echo.Context) error {
	objectType := api_v0.ObjectTypeSpringBootDefinition
	var springBootDefinition api_v0.SpringBootDefinition

	// check for empty payload, unsupported fields, GORM Model fields, optional associations, etc.
	if id, err := tpapiserver_lib.PayloadCheck(c, true, false, objectType, springBootDefinition); err != nil {
		h.Handler.Logger.Error("handler error: error performing payload check", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), objectType)
	}

	if err := c.Bind(&springBootDefinition); err != nil {
		h.Handler.Logger.Error("handler error: error binding object", zap.Error(err))
		return tpapiserver_lib.ResponseStatusBindErr(c, nil, err, objectType)
	}

	// check for missing required fields
	if id, err := tpapiserver_lib.ValidateBoundData(c, springBootDefinition, objectType); err != nil {
		h.Handler.Logger.Error("handler error: error validating bound data", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), objectType)
	}

	// the create runs inside a retryable transaction. Under
	// SERIALIZABLE isolation CockroachDB answers a write conflict with
	// SQLSTATE 40001 and expects the client to re-run the transaction.
	// the duplicate-name read joins it: a restart has to re-check the
	// name, and checking outside the transaction leaves a window where
	// two concurrent creates both find the name free.
	nameUsed := false
	if err := crdbgorm.ExecuteTx(
		c.Request().Context(), h.Handler.DB, nil,
		func(tx *gorm.DB) error {
			// the database assigns the primary key, so a retried attempt
			// must not carry the one a rolled-back attempt was given
			springBootDefinition.ID = nil
			nameUsed = true
			var existingSpringBootDefinition api_v0.SpringBootDefinition
			if result := tx.Scopes(tpapiserver_lib.QueryScopes(c)...).Where("name = ?", springBootDefinition.Name).First(&existingSpringBootDefinition); result.Error != nil {
				if !errors.Is(result.Error, gorm.ErrRecordNotFound) {
					return result.Error
				}
				nameUsed = false
			}
			// the name is taken; leave the transaction without writing
			// and let the caller answer 409
			if nameUsed {
				return nil
			}
			return tx.Scopes(tpapiserver_lib.QueryScopes(c)...).Create(&springBootDefinition).Error
		},
	); err != nil {
		h.Handler.Logger.Error("handler error: error creating object", zap.Error(err))
		// check if this is a custom HTTP error with specific status code
		var httpErr *tputil_v0.HttpError
		if errors.As(err, &httpErr) {
			return tpapiserver_lib.ResponseStatusErr(
				httpErr.GetStatusCode(), c, nil, err, objectType,
			)
		}
		return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
	}
	if nameUsed {
		return tpapiserver_lib.ResponseStatus409(c, nil, errors.New("object with provided name already exists"), objectType)
	}

	// notify controller if reconciliation is required
	if !*springBootDefinition.Reconciled {
		notifPayload, err := springBootDefinition.NotificationPayload(
			notifications.NotificationOperationCreated,
			false,
			time.Now().Unix(),
		)
		if err != nil {
			h.Handler.Logger.Error("handler error: error creating NATS notification", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
		}
		h.Handler.JS.Publish(notif.SpringBootDefinitionCreateSubject, *notifPayload)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		springBootDefinition,
		objectType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
	}

	return tpapiserver_lib.ResponseStatus201(c, *response)
}

// @Summary gets all spring boot definitions.
// @Description Get all spring boot definitions from the Threeport database.
// @ID get-v0-springBootDefinitions
// @Accept json
// @Produce json
// @Param name query string false "filter by exact spring boot definition name (case sensitive)"
// @Success 200 {object} v0.Response "OK"
// @Failure 400 {object} v0.Response "Bad Request"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/spring-boot-definitions [GET]
func (h Handler) GetSpringBootDefinitions(c echo.Context) error {
	objectType := api_v0.ObjectTypeSpringBootDefinition

	// get pagination parameters
	pageParams, err := c.(*tpapiserver_lib.CustomContext).GetPaginationParams()
	if err != nil {
		return tpapiserver_lib.ResponseStatus400(c, pageParams, err, objectType)
	}

	// bind filter
	var filter api_v0.SpringBootDefinition
	if err := c.Bind(&filter); err != nil {
		h.Handler.Logger.Error("handler error: error binding filter", zap.Error(err))
		return tpapiserver_lib.ResponseStatus400(c, pageParams, err, objectType)
	}

	pagination := new(tpapiserver_lib.Pagination)
	pagination.Limit = pageParams.Limit

	records := &[]api_v0.SpringBootDefinition{}
	var returnedCount int64

	switch {
	case pageParams.QueryId == "":
		// no query ID provided, so the client is not requesting a specific page of results
		// count total number of objects
		var totalCount int64
		if result := h.Handler.RequestDB(c).Model(&api_v0.SpringBootDefinition{}).Where(&filter).Count(&totalCount); result.Error != nil {
			h.Handler.Logger.Error("handler error: error counting objects", zap.Error(result.Error))
			return tpapiserver_lib.ResponseStatus500(c, pageParams, result.Error, objectType)
		}

		// see if total count is greater than the limit
		pagination.HasMore = totalCount > pagination.Limit

		switch pagination.HasMore {
		case false:
			// if we don't have to paginate, return all records
			if result := h.Handler.RequestDB(c).Order("ID asc").Where(&filter).Find(records); result.Error != nil {
				h.Handler.Logger.Error("handler error: error finding objects", zap.Error(result.Error))
				return tpapiserver_lib.ResponseStatus500(c, pageParams, result.Error, objectType)
			}
			returnedCount = int64(len(*records))
		case true:
			// dispatch to the configured pagination strategy to fetch the first page
			queryTable := filter.TableName()
			queryId, count, err := h.Handler.DispatchGetPaginatedRecords(h.Handler.RequestDB(c).Model(&api_v0.SpringBootDefinition{}).Where(&filter), records, queryTable, pageParams)
			if err != nil {
				if errors.Is(err, tpapiserver_lib.ErrInvalidPaginationQueryId) || errors.Is(err, tpapiserver_lib.ErrPaginationSessionExpired) {
					return tpapiserver_lib.ResponseStatus400(c, pageParams, err, objectType)
				}
				h.Handler.Logger.Error("handler error: error fetching paginated records", zap.Error(err))
				return tpapiserver_lib.ResponseStatus500(c, pageParams, err, objectType)
			}
			pagination.QueryId = queryId
			returnedCount = count

			// set the cursor for the next page of results
			if len(*records) > 0 {
				pagination.NextCursor = *(*records)[len(*records)-1].ID
			} else {
				pagination.NextCursor = 0
			}
		}
	case pageParams.QueryId != "" && pageParams.Cursor == 0:
		// client provided a query ID but no cursor, so we cannot fetch the next page of results
		return tpapiserver_lib.ResponseStatus400(c, pageParams, errors.New("cursor is required when query ID is provided"), objectType)
	case pageParams.QueryId != "" && pageParams.Cursor != 0:
		// continuation: dispatch to the configured pagination strategy to fetch the next page
		queryTable := filter.TableName()
		queryId, count, err := h.Handler.DispatchGetPaginatedRecords(h.Handler.RequestDB(c).Model(&api_v0.SpringBootDefinition{}).Where(&filter), records, queryTable, pageParams)
		if err != nil {
			if errors.Is(err, tpapiserver_lib.ErrInvalidPaginationQueryId) || errors.Is(err, tpapiserver_lib.ErrPaginationSessionExpired) {
				return tpapiserver_lib.ResponseStatus400(c, pageParams, err, objectType)
			}
			h.Handler.Logger.Error("handler error: error fetching paginated records", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, pageParams, err, objectType)
		}
		pagination.QueryId = queryId
		returnedCount = count

		// set the cursor for the next page of results
		if len(*records) > 0 {
			pagination.NextCursor = *(*records)[len(*records)-1].ID
		} else {
			pagination.NextCursor = 0
		}

		// see if we fetched the last of the records
		pagination.HasMore = returnedCount >= pagination.Limit
	}

	// construct response
	response, err := tpapiserver_lib.CreateResponse(
		&tpapiserver_lib.Meta{
			ObjectCount: returnedCount,
			Pagination:  *pagination,
		},
		*records,
		objectType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, pageParams, err, objectType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

// @Summary gets a spring boot definition.
// @Description Get a particular spring boot definition from the database.
// @ID get-v0-springBootDefinition
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Success 200 {object} v0.Response "OK"
// @Failure 404 {object} v0.Response "Not Found"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/spring-boot-definitions/{id} [GET]
func (h Handler) GetSpringBootDefinition(c echo.Context) error {
	objectType := api_v0.ObjectTypeSpringBootDefinition
	springBootDefinitionID := c.Param("id")
	var springBootDefinition api_v0.SpringBootDefinition
	if result := h.Handler.RequestDB(c).
		First(&springBootDefinition, springBootDefinitionID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, objectType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, objectType)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		springBootDefinition,
		objectType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

// @Summary updates specific fields for an existing spring boot definition.
// @Description Update a spring boot definition in the database.  Provide one or more fields to update.
// @Description Note: This API endpint is for updating spring boot definition objects only.
// @Description Request bodies that include related objects will be accepted, however
// @Description the related objects will not be changed.  Call the patch or put method for
// @Description each particular existing object to change them.
// @ID update-v0-springBootDefinition
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Param springBootDefinition body api_v0.SpringBootDefinition true "SpringBootDefinition object"
// @Success 200 {object} v0.Response "OK"
// @Failure 400 {object} v0.Response "Bad Request"
// @Failure 404 {object} v0.Response "Not Found"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/spring-boot-definitions/{id} [PATCH]
func (h Handler) UpdateSpringBootDefinition(c echo.Context) error {
	objectType := api_v0.ObjectTypeSpringBootDefinition
	springBootDefinitionID := c.Param("id")
	var existingSpringBootDefinition api_v0.SpringBootDefinition
	// check for empty payload, invalid or unsupported fields, optional associations, etc.
	if id, err := tpapiserver_lib.PayloadCheck(c, true, true, objectType, existingSpringBootDefinition); err != nil {
		h.Handler.Logger.Error("handler error: error performing payload check", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), objectType)
	}

	// bind payload
	var updatedSpringBootDefinition api_v0.SpringBootDefinition
	if err := c.Bind(&updatedSpringBootDefinition); err != nil {
		h.Handler.Logger.Error("handler error: error binding payload", zap.Error(err))
		return tpapiserver_lib.ResponseStatusBindErr(c, nil, err, objectType)
	}

	// the read and the write retry together. Under SERIALIZABLE
	// isolation CockroachDB answers a conflict with SQLSTATE 40001 and
	// expects the client to re-run the transaction; a restart that
	// re-ran only the write would land it on a stale row. RequestDB is
	// not used because ExecuteTx opens the transaction itself, so the
	// query scopes it would have applied go on tx instead.
	if err := crdbgorm.ExecuteTx(
		c.Request().Context(), h.Handler.DB, nil,
		func(tx *gorm.DB) error {
			// a retried attempt must not read into the previous one's leftovers
			existingSpringBootDefinition = api_v0.SpringBootDefinition{}
			if result := tx.Scopes(tpapiserver_lib.QueryScopes(c)...).First(&existingSpringBootDefinition, springBootDefinitionID); result.Error != nil {
				return result.Error
			}
			return tx.Scopes(tpapiserver_lib.QueryScopes(c)...).Model(&existingSpringBootDefinition).Updates(&updatedSpringBootDefinition).Error
		},
	); err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, err, objectType)
		}
		h.Handler.Logger.Error("handler error: error updating object", zap.Error(err))
		// check if this is a custom HTTP error with specific status code
		var httpErr *tputil_v0.HttpError
		if errors.As(err, &httpErr) {
			return tpapiserver_lib.ResponseStatusErr(
				httpErr.GetStatusCode(), c, nil, err, objectType,
			)
		}
		return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
	}

	// notify controller if reconciliation is required
	if !*existingSpringBootDefinition.Reconciled {
		notifPayload, err := existingSpringBootDefinition.NotificationPayload(
			notifications.NotificationOperationUpdated,
			false,
			time.Now().Unix(),
		)
		if err != nil {
			h.Handler.Logger.Error("handler error: error creating NATS notification", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
		}
		h.Handler.JS.Publish(notif.SpringBootDefinitionUpdateSubject, *notifPayload)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		existingSpringBootDefinition,
		objectType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

// @Summary updates an existing spring boot definition by replacing the entire object.
// @Description Replace a spring boot definition in the database.  All required fields must be provided.
// @Description If any optional fields are not provided, they will be null post-update.
// @Description Note: This API endpint is for updating spring boot definition objects only.
// @Description Request bodies that include related objects will be accepted, however
// @Description the related objects will not be changed.  Call the patch or put method for
// @Description each particular existing object to change them.
// @ID replace-v0-springBootDefinition
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Param springBootDefinition body api_v0.SpringBootDefinition true "SpringBootDefinition object"
// @Success 200 {object} v0.Response "OK"
// @Failure 400 {object} v0.Response "Bad Request"
// @Failure 404 {object} v0.Response "Not Found"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/spring-boot-definitions/{id} [PUT]
func (h Handler) ReplaceSpringBootDefinition(c echo.Context) error {
	objectType := api_v0.ObjectTypeSpringBootDefinition
	springBootDefinitionID := c.Param("id")
	var existingSpringBootDefinition api_v0.SpringBootDefinition
	if result := h.Handler.RequestDB(c).First(&existingSpringBootDefinition, springBootDefinitionID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, objectType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, objectType)
	}

	// check for empty payload, invalid or unsupported fields, optional associations, etc.
	if id, err := tpapiserver_lib.PayloadCheck(c, true, true, objectType, existingSpringBootDefinition); err != nil {
		h.Handler.Logger.Error("handler error: error performing payload check", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), objectType)
	}

	// bind payload
	var updatedSpringBootDefinition api_v0.SpringBootDefinition
	if err := c.Bind(&updatedSpringBootDefinition); err != nil {
		h.Handler.Logger.Error("handler error: error binding payload", zap.Error(err))
		return tpapiserver_lib.ResponseStatusBindErr(c, nil, err, objectType)
	}

	// check for missing required fields
	if id, err := tpapiserver_lib.ValidateBoundData(c, updatedSpringBootDefinition, objectType); err != nil {
		h.Handler.Logger.Error("handler error: error validating bound data", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), objectType)
	}

	// persist provided data
	updatedSpringBootDefinition.ID = existingSpringBootDefinition.ID
	// the save runs inside a retryable transaction. Under SERIALIZABLE
	// isolation CockroachDB answers a write conflict with SQLSTATE 40001
	// and expects the client to re-run it. Only the write is retried: the
	// read above contributes the primary key, which the URL fixes, so it
	// cannot go stale between attempts.
	if err := crdbgorm.ExecuteTx(
		c.Request().Context(), h.Handler.DB, nil,
		func(tx *gorm.DB) error {
			return tx.Scopes(tpapiserver_lib.QueryScopes(c)...).Session(&gorm.Session{FullSaveAssociations: false}).Omit("CreatedAt", "DeletedAt").Save(&updatedSpringBootDefinition).Error
		},
	); err != nil {
		h.Handler.Logger.Error("handler error: error persisting object", zap.Error(err))
		// check if this is a custom HTTP error with specific status code
		var httpErr *tputil_v0.HttpError
		if errors.As(err, &httpErr) {
			return tpapiserver_lib.ResponseStatusErr(
				httpErr.GetStatusCode(), c, nil, err, objectType,
			)
		}
		return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
	}

	// reload updated data from DB
	if result := h.Handler.RequestDB(c).First(&existingSpringBootDefinition, springBootDefinitionID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, objectType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, objectType)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		existingSpringBootDefinition,
		objectType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

// @Summary deletes a spring boot definition.
// @Description Delete a spring boot definition by ID from the database.
// @ID delete-v0-springBootDefinition
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Success 200 {object} v0.Response "OK"
// @Failure 404 {object} v0.Response "Not Found"
// @Failure 409 {object} v0.Response "Conflict"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/spring-boot-definitions/{id} [DELETE]
func (h Handler) DeleteSpringBootDefinition(c echo.Context) error {
	objectType := api_v0.ObjectTypeSpringBootDefinition
	springBootDefinitionID := c.Param("id")
	var springBootDefinition api_v0.SpringBootDefinition
	if result := h.Handler.RequestDB(c).Preload("SpringBootInstances").First(&springBootDefinition, springBootDefinitionID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, objectType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, objectType)
	}

	// check to make sure no dependent instances exist for this definition
	if len(springBootDefinition.SpringBootInstances) != 0 {
		err := errors.New("spring boot definition has related spring boot instances - cannot be deleted")
		return tpapiserver_lib.ResponseStatus409(c, nil, err, objectType)
	}

	// pre-check synchronously so the client sees the 409 - without this, reconciled types only surface the block to the reconciler
	if checkErr := tpapi_v0.CheckBlockingAttachedObjectReferences(h.Handler.RequestDB(c), &springBootDefinition); checkErr != nil {
		var blockedErr *tpapi_v0.BlockedDeleteError
		if errors.As(checkErr, &blockedErr) {
			return tphandlers_v0.RespondBlockedDelete(
				c,
				h.Handler.RequestDB(c),
				blockedErr,
			)
		}
		return tpapiserver_lib.ResponseStatus500(c, nil, checkErr, objectType)
	}
	// schedule for deletion if not already scheduled
	// if scheduled and reconciled, delete object from DB
	// if scheduled but not reconciled, return 409 (controller is working on it)
	if springBootDefinition.DeletionScheduled == nil {
		// schedule for deletion
		reconciled := false
		timestamp := time.Now().UTC()
		scheduledSpringBootDefinition := api_v0.SpringBootDefinition{
			Reconciliation: tpapi_v0.Reconciliation{
				DeletionScheduled: &timestamp,
				Reconciled:        &reconciled,
			}}
		if err := crdbgorm.ExecuteTx(
			c.Request().Context(), h.Handler.DB, nil,
			func(tx *gorm.DB) error {
				return tx.Scopes(tpapiserver_lib.QueryScopes(c)...).Model(&springBootDefinition).Updates(&scheduledSpringBootDefinition).Error
			},
		); err != nil {
			h.Handler.Logger.Error("handler error: error creating scheduled deletion", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
		}
		// notify controller
		notifPayload, err := springBootDefinition.NotificationPayload(
			notifications.NotificationOperationDeleted,
			false,
			time.Now().Unix(),
		)
		if err != nil {
			h.Handler.Logger.Error("handler error: error creating NATS notification", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
		}
		h.Handler.JS.Publish(notif.SpringBootDefinitionDeleteSubject, *notifPayload)
	} else {
		if springBootDefinition.DeletionConfirmed == nil {
			// if deletion scheduled but not reconciled, return 409 - deletion
			// already underway
			return tpapiserver_lib.ResponseStatus409(c, nil, errors.New(fmt.Sprintf(
				"object with ID %d already being deleted",
				*springBootDefinition.ID,
			)), objectType)
		} else {
			// object scheduled for deletion and confirmed - it can be deleted
			// from DB
			if err := crdbgorm.ExecuteTx(
				c.Request().Context(), h.Handler.DB, nil,
				func(tx *gorm.DB) error {
					return tx.Scopes(tpapiserver_lib.QueryScopes(c)...).Delete(&springBootDefinition).Error
				},
			); err != nil {
				h.Handler.Logger.Error("handler error: error deleting object", zap.Error(err))
				// surface BlockedDeleteError from gorm hook - backstop in case an attached object reference was created after the pre-check
				var blockedErr *tpapi_v0.BlockedDeleteError
				if errors.As(err, &blockedErr) {
					return tphandlers_v0.RespondBlockedDelete(
						c,
						h.Handler.RequestDB(c),
						blockedErr,
					)
				}
				// check if this is a custom HTTP error with specific status code
				var httpErr *tputil_v0.HttpError
				if errors.As(err, &httpErr) {
					return tpapiserver_lib.ResponseStatusErr(
						httpErr.GetStatusCode(), c, nil, err, objectType,
					)
				}
				return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
			}
		}
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		springBootDefinition,
		objectType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

///////////////////////////////////////////////////////////////////////////////
// SpringBootInstance
///////////////////////////////////////////////////////////////////////////////

// @Summary GetSpringBootInstanceVersions gets the supported versions for the spring boot instance API.
// @Description Get the supported API versions for spring boot instances.
// @ID springBootInstance-get-versions
// @Produce json
// @Success 200 {object} tpapiserver_lib.ApiObjectVersions "OK"
// @Router /threeport-io/spring-boot-instances/versions [GET]
func (h Handler) GetSpringBootInstanceVersions(c echo.Context) error {
	return c.JSON(http.StatusOK, tpapiserver_lib.ObjectVersions[string(api_v0.ObjectTypeSpringBootInstance)])
}

// @Summary adds a new spring boot instance.
// @Description Add a new spring boot instance to the Threeport database.
// @ID add-v0-springBootInstance
// @Accept json
// @Produce json
// @Param springBootInstance body api_v0.SpringBootInstance true "SpringBootInstance object"
// @Success 201 {object} v0.Response "Created"
// @Failure 400 {object} v0.Response "Bad Request"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/spring-boot-instances [POST]
func (h Handler) AddSpringBootInstance(c echo.Context) error {
	objectType := api_v0.ObjectTypeSpringBootInstance
	var springBootInstance api_v0.SpringBootInstance

	// check for empty payload, unsupported fields, GORM Model fields, optional associations, etc.
	if id, err := tpapiserver_lib.PayloadCheck(c, true, false, objectType, springBootInstance); err != nil {
		h.Handler.Logger.Error("handler error: error performing payload check", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), objectType)
	}

	if err := c.Bind(&springBootInstance); err != nil {
		h.Handler.Logger.Error("handler error: error binding object", zap.Error(err))
		return tpapiserver_lib.ResponseStatusBindErr(c, nil, err, objectType)
	}

	// check for missing required fields
	if id, err := tpapiserver_lib.ValidateBoundData(c, springBootInstance, objectType); err != nil {
		h.Handler.Logger.Error("handler error: error validating bound data", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), objectType)
	}

	// the create runs inside a retryable transaction. Under
	// SERIALIZABLE isolation CockroachDB answers a write conflict with
	// SQLSTATE 40001 and expects the client to re-run the transaction.
	// the duplicate-name read joins it: a restart has to re-check the
	// name, and checking outside the transaction leaves a window where
	// two concurrent creates both find the name free.
	nameUsed := false
	if err := crdbgorm.ExecuteTx(
		c.Request().Context(), h.Handler.DB, nil,
		func(tx *gorm.DB) error {
			// the database assigns the primary key, so a retried attempt
			// must not carry the one a rolled-back attempt was given
			springBootInstance.ID = nil
			nameUsed = true
			var existingSpringBootInstance api_v0.SpringBootInstance
			if result := tx.Scopes(tpapiserver_lib.QueryScopes(c)...).Where("name = ?", springBootInstance.Name).First(&existingSpringBootInstance); result.Error != nil {
				if !errors.Is(result.Error, gorm.ErrRecordNotFound) {
					return result.Error
				}
				nameUsed = false
			}
			// the name is taken; leave the transaction without writing
			// and let the caller answer 409
			if nameUsed {
				return nil
			}
			return tx.Scopes(tpapiserver_lib.QueryScopes(c)...).Create(&springBootInstance).Error
		},
	); err != nil {
		h.Handler.Logger.Error("handler error: error creating object", zap.Error(err))
		// check if this is a custom HTTP error with specific status code
		var httpErr *tputil_v0.HttpError
		if errors.As(err, &httpErr) {
			return tpapiserver_lib.ResponseStatusErr(
				httpErr.GetStatusCode(), c, nil, err, objectType,
			)
		}
		return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
	}
	if nameUsed {
		return tpapiserver_lib.ResponseStatus409(c, nil, errors.New("object with provided name already exists"), objectType)
	}

	// notify controller if reconciliation is required
	if !*springBootInstance.Reconciled {
		notifPayload, err := springBootInstance.NotificationPayload(
			notifications.NotificationOperationCreated,
			false,
			time.Now().Unix(),
		)
		if err != nil {
			h.Handler.Logger.Error("handler error: error creating NATS notification", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
		}
		h.Handler.JS.Publish(notif.SpringBootInstanceCreateSubject, *notifPayload)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		springBootInstance,
		objectType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
	}

	return tpapiserver_lib.ResponseStatus201(c, *response)
}

// @Summary gets all spring boot instances.
// @Description Get all spring boot instances from the Threeport database.
// @ID get-v0-springBootInstances
// @Accept json
// @Produce json
// @Param name query string false "filter by exact spring boot instance name (case sensitive)"
// @Success 200 {object} v0.Response "OK"
// @Failure 400 {object} v0.Response "Bad Request"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/spring-boot-instances [GET]
func (h Handler) GetSpringBootInstances(c echo.Context) error {
	objectType := api_v0.ObjectTypeSpringBootInstance

	// get pagination parameters
	pageParams, err := c.(*tpapiserver_lib.CustomContext).GetPaginationParams()
	if err != nil {
		return tpapiserver_lib.ResponseStatus400(c, pageParams, err, objectType)
	}

	// bind filter
	var filter api_v0.SpringBootInstance
	if err := c.Bind(&filter); err != nil {
		h.Handler.Logger.Error("handler error: error binding filter", zap.Error(err))
		return tpapiserver_lib.ResponseStatus400(c, pageParams, err, objectType)
	}

	pagination := new(tpapiserver_lib.Pagination)
	pagination.Limit = pageParams.Limit

	records := &[]api_v0.SpringBootInstance{}
	var returnedCount int64

	switch {
	case pageParams.QueryId == "":
		// no query ID provided, so the client is not requesting a specific page of results
		// count total number of objects
		var totalCount int64
		if result := h.Handler.RequestDB(c).Model(&api_v0.SpringBootInstance{}).Where(&filter).Count(&totalCount); result.Error != nil {
			h.Handler.Logger.Error("handler error: error counting objects", zap.Error(result.Error))
			return tpapiserver_lib.ResponseStatus500(c, pageParams, result.Error, objectType)
		}

		// see if total count is greater than the limit
		pagination.HasMore = totalCount > pagination.Limit

		switch pagination.HasMore {
		case false:
			// if we don't have to paginate, return all records
			if result := h.Handler.RequestDB(c).Order("ID asc").Where(&filter).Find(records); result.Error != nil {
				h.Handler.Logger.Error("handler error: error finding objects", zap.Error(result.Error))
				return tpapiserver_lib.ResponseStatus500(c, pageParams, result.Error, objectType)
			}
			returnedCount = int64(len(*records))
		case true:
			// dispatch to the configured pagination strategy to fetch the first page
			queryTable := filter.TableName()
			queryId, count, err := h.Handler.DispatchGetPaginatedRecords(h.Handler.RequestDB(c).Model(&api_v0.SpringBootInstance{}).Where(&filter), records, queryTable, pageParams)
			if err != nil {
				if errors.Is(err, tpapiserver_lib.ErrInvalidPaginationQueryId) || errors.Is(err, tpapiserver_lib.ErrPaginationSessionExpired) {
					return tpapiserver_lib.ResponseStatus400(c, pageParams, err, objectType)
				}
				h.Handler.Logger.Error("handler error: error fetching paginated records", zap.Error(err))
				return tpapiserver_lib.ResponseStatus500(c, pageParams, err, objectType)
			}
			pagination.QueryId = queryId
			returnedCount = count

			// set the cursor for the next page of results
			if len(*records) > 0 {
				pagination.NextCursor = *(*records)[len(*records)-1].ID
			} else {
				pagination.NextCursor = 0
			}
		}
	case pageParams.QueryId != "" && pageParams.Cursor == 0:
		// client provided a query ID but no cursor, so we cannot fetch the next page of results
		return tpapiserver_lib.ResponseStatus400(c, pageParams, errors.New("cursor is required when query ID is provided"), objectType)
	case pageParams.QueryId != "" && pageParams.Cursor != 0:
		// continuation: dispatch to the configured pagination strategy to fetch the next page
		queryTable := filter.TableName()
		queryId, count, err := h.Handler.DispatchGetPaginatedRecords(h.Handler.RequestDB(c).Model(&api_v0.SpringBootInstance{}).Where(&filter), records, queryTable, pageParams)
		if err != nil {
			if errors.Is(err, tpapiserver_lib.ErrInvalidPaginationQueryId) || errors.Is(err, tpapiserver_lib.ErrPaginationSessionExpired) {
				return tpapiserver_lib.ResponseStatus400(c, pageParams, err, objectType)
			}
			h.Handler.Logger.Error("handler error: error fetching paginated records", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, pageParams, err, objectType)
		}
		pagination.QueryId = queryId
		returnedCount = count

		// set the cursor for the next page of results
		if len(*records) > 0 {
			pagination.NextCursor = *(*records)[len(*records)-1].ID
		} else {
			pagination.NextCursor = 0
		}

		// see if we fetched the last of the records
		pagination.HasMore = returnedCount >= pagination.Limit
	}

	// construct response
	response, err := tpapiserver_lib.CreateResponse(
		&tpapiserver_lib.Meta{
			ObjectCount: returnedCount,
			Pagination:  *pagination,
		},
		*records,
		objectType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, pageParams, err, objectType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

// @Summary gets a spring boot instance.
// @Description Get a particular spring boot instance from the database.
// @ID get-v0-springBootInstance
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Success 200 {object} v0.Response "OK"
// @Failure 404 {object} v0.Response "Not Found"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/spring-boot-instances/{id} [GET]
func (h Handler) GetSpringBootInstance(c echo.Context) error {
	objectType := api_v0.ObjectTypeSpringBootInstance
	springBootInstanceID := c.Param("id")
	var springBootInstance api_v0.SpringBootInstance
	if result := h.Handler.RequestDB(c).
		First(&springBootInstance, springBootInstanceID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, objectType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, objectType)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		springBootInstance,
		objectType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

// @Summary updates specific fields for an existing spring boot instance.
// @Description Update a spring boot instance in the database.  Provide one or more fields to update.
// @Description Note: This API endpint is for updating spring boot instance objects only.
// @Description Request bodies that include related objects will be accepted, however
// @Description the related objects will not be changed.  Call the patch or put method for
// @Description each particular existing object to change them.
// @ID update-v0-springBootInstance
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Param springBootInstance body api_v0.SpringBootInstance true "SpringBootInstance object"
// @Success 200 {object} v0.Response "OK"
// @Failure 400 {object} v0.Response "Bad Request"
// @Failure 404 {object} v0.Response "Not Found"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/spring-boot-instances/{id} [PATCH]
func (h Handler) UpdateSpringBootInstance(c echo.Context) error {
	objectType := api_v0.ObjectTypeSpringBootInstance
	springBootInstanceID := c.Param("id")
	var existingSpringBootInstance api_v0.SpringBootInstance
	// check for empty payload, invalid or unsupported fields, optional associations, etc.
	if id, err := tpapiserver_lib.PayloadCheck(c, true, true, objectType, existingSpringBootInstance); err != nil {
		h.Handler.Logger.Error("handler error: error performing payload check", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), objectType)
	}

	// bind payload
	var updatedSpringBootInstance api_v0.SpringBootInstance
	if err := c.Bind(&updatedSpringBootInstance); err != nil {
		h.Handler.Logger.Error("handler error: error binding payload", zap.Error(err))
		return tpapiserver_lib.ResponseStatusBindErr(c, nil, err, objectType)
	}

	// the read and the write retry together. Under SERIALIZABLE
	// isolation CockroachDB answers a conflict with SQLSTATE 40001 and
	// expects the client to re-run the transaction; a restart that
	// re-ran only the write would land it on a stale row. RequestDB is
	// not used because ExecuteTx opens the transaction itself, so the
	// query scopes it would have applied go on tx instead.
	if err := crdbgorm.ExecuteTx(
		c.Request().Context(), h.Handler.DB, nil,
		func(tx *gorm.DB) error {
			// a retried attempt must not read into the previous one's leftovers
			existingSpringBootInstance = api_v0.SpringBootInstance{}
			if result := tx.Scopes(tpapiserver_lib.QueryScopes(c)...).First(&existingSpringBootInstance, springBootInstanceID); result.Error != nil {
				return result.Error
			}
			return tx.Scopes(tpapiserver_lib.QueryScopes(c)...).Model(&existingSpringBootInstance).Updates(&updatedSpringBootInstance).Error
		},
	); err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, err, objectType)
		}
		h.Handler.Logger.Error("handler error: error updating object", zap.Error(err))
		// check if this is a custom HTTP error with specific status code
		var httpErr *tputil_v0.HttpError
		if errors.As(err, &httpErr) {
			return tpapiserver_lib.ResponseStatusErr(
				httpErr.GetStatusCode(), c, nil, err, objectType,
			)
		}
		return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
	}

	// notify controller if reconciliation is required
	if !*existingSpringBootInstance.Reconciled {
		notifPayload, err := existingSpringBootInstance.NotificationPayload(
			notifications.NotificationOperationUpdated,
			false,
			time.Now().Unix(),
		)
		if err != nil {
			h.Handler.Logger.Error("handler error: error creating NATS notification", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
		}
		h.Handler.JS.Publish(notif.SpringBootInstanceUpdateSubject, *notifPayload)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		existingSpringBootInstance,
		objectType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

// @Summary updates an existing spring boot instance by replacing the entire object.
// @Description Replace a spring boot instance in the database.  All required fields must be provided.
// @Description If any optional fields are not provided, they will be null post-update.
// @Description Note: This API endpint is for updating spring boot instance objects only.
// @Description Request bodies that include related objects will be accepted, however
// @Description the related objects will not be changed.  Call the patch or put method for
// @Description each particular existing object to change them.
// @ID replace-v0-springBootInstance
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Param springBootInstance body api_v0.SpringBootInstance true "SpringBootInstance object"
// @Success 200 {object} v0.Response "OK"
// @Failure 400 {object} v0.Response "Bad Request"
// @Failure 404 {object} v0.Response "Not Found"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/spring-boot-instances/{id} [PUT]
func (h Handler) ReplaceSpringBootInstance(c echo.Context) error {
	objectType := api_v0.ObjectTypeSpringBootInstance
	springBootInstanceID := c.Param("id")
	var existingSpringBootInstance api_v0.SpringBootInstance
	if result := h.Handler.RequestDB(c).First(&existingSpringBootInstance, springBootInstanceID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, objectType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, objectType)
	}

	// check for empty payload, invalid or unsupported fields, optional associations, etc.
	if id, err := tpapiserver_lib.PayloadCheck(c, true, true, objectType, existingSpringBootInstance); err != nil {
		h.Handler.Logger.Error("handler error: error performing payload check", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), objectType)
	}

	// bind payload
	var updatedSpringBootInstance api_v0.SpringBootInstance
	if err := c.Bind(&updatedSpringBootInstance); err != nil {
		h.Handler.Logger.Error("handler error: error binding payload", zap.Error(err))
		return tpapiserver_lib.ResponseStatusBindErr(c, nil, err, objectType)
	}

	// check for missing required fields
	if id, err := tpapiserver_lib.ValidateBoundData(c, updatedSpringBootInstance, objectType); err != nil {
		h.Handler.Logger.Error("handler error: error validating bound data", zap.Error(err))
		return tpapiserver_lib.ResponseStatusErr(id, c, nil, errors.New(err.Error()), objectType)
	}

	// persist provided data
	updatedSpringBootInstance.ID = existingSpringBootInstance.ID
	// the save runs inside a retryable transaction. Under SERIALIZABLE
	// isolation CockroachDB answers a write conflict with SQLSTATE 40001
	// and expects the client to re-run it. Only the write is retried: the
	// read above contributes the primary key, which the URL fixes, so it
	// cannot go stale between attempts.
	if err := crdbgorm.ExecuteTx(
		c.Request().Context(), h.Handler.DB, nil,
		func(tx *gorm.DB) error {
			return tx.Scopes(tpapiserver_lib.QueryScopes(c)...).Session(&gorm.Session{FullSaveAssociations: false}).Omit("CreatedAt", "DeletedAt").Save(&updatedSpringBootInstance).Error
		},
	); err != nil {
		h.Handler.Logger.Error("handler error: error persisting object", zap.Error(err))
		// check if this is a custom HTTP error with specific status code
		var httpErr *tputil_v0.HttpError
		if errors.As(err, &httpErr) {
			return tpapiserver_lib.ResponseStatusErr(
				httpErr.GetStatusCode(), c, nil, err, objectType,
			)
		}
		return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
	}

	// reload updated data from DB
	if result := h.Handler.RequestDB(c).First(&existingSpringBootInstance, springBootInstanceID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, objectType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, objectType)
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		existingSpringBootInstance,
		objectType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}

// @Summary deletes a spring boot instance.
// @Description Delete a spring boot instance by ID from the database.
// @ID delete-v0-springBootInstance
// @Accept json
// @Produce json
// @Param id path int true "ID"
// @Success 200 {object} v0.Response "OK"
// @Failure 404 {object} v0.Response "Not Found"
// @Failure 409 {object} v0.Response "Conflict"
// @Failure 500 {object} v0.Response "Internal Server Error"
// @Router /threeport-io/v0/spring-boot-instances/{id} [DELETE]
func (h Handler) DeleteSpringBootInstance(c echo.Context) error {
	objectType := api_v0.ObjectTypeSpringBootInstance
	springBootInstanceID := c.Param("id")
	var springBootInstance api_v0.SpringBootInstance
	if result := h.Handler.RequestDB(c).First(&springBootInstance, springBootInstanceID); result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return tpapiserver_lib.ResponseStatus404(c, nil, result.Error, objectType)
		}
		h.Handler.Logger.Error("handler error: error finding object", zap.Error(result.Error))
		return tpapiserver_lib.ResponseStatus500(c, nil, result.Error, objectType)
	}

	// pre-check synchronously so the client sees the 409 - without this, reconciled types only surface the block to the reconciler
	if checkErr := tpapi_v0.CheckBlockingAttachedObjectReferences(h.Handler.RequestDB(c), &springBootInstance); checkErr != nil {
		var blockedErr *tpapi_v0.BlockedDeleteError
		if errors.As(checkErr, &blockedErr) {
			return tphandlers_v0.RespondBlockedDelete(
				c,
				h.Handler.RequestDB(c),
				blockedErr,
			)
		}
		return tpapiserver_lib.ResponseStatus500(c, nil, checkErr, objectType)
	}
	// schedule for deletion if not already scheduled
	// if scheduled and reconciled, delete object from DB
	// if scheduled but not reconciled, return 409 (controller is working on it)
	if springBootInstance.DeletionScheduled == nil {
		// schedule for deletion
		reconciled := false
		timestamp := time.Now().UTC()
		scheduledSpringBootInstance := api_v0.SpringBootInstance{
			Reconciliation: tpapi_v0.Reconciliation{
				DeletionScheduled: &timestamp,
				Reconciled:        &reconciled,
			}}
		if err := crdbgorm.ExecuteTx(
			c.Request().Context(), h.Handler.DB, nil,
			func(tx *gorm.DB) error {
				return tx.Scopes(tpapiserver_lib.QueryScopes(c)...).Model(&springBootInstance).Updates(&scheduledSpringBootInstance).Error
			},
		); err != nil {
			h.Handler.Logger.Error("handler error: error creating scheduled deletion", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
		}
		// notify controller
		notifPayload, err := springBootInstance.NotificationPayload(
			notifications.NotificationOperationDeleted,
			false,
			time.Now().Unix(),
		)
		if err != nil {
			h.Handler.Logger.Error("handler error: error creating NATS notification", zap.Error(err))
			return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
		}
		h.Handler.JS.Publish(notif.SpringBootInstanceDeleteSubject, *notifPayload)
	} else {
		if springBootInstance.DeletionConfirmed == nil {
			// if deletion scheduled but not reconciled, return 409 - deletion
			// already underway
			return tpapiserver_lib.ResponseStatus409(c, nil, errors.New(fmt.Sprintf(
				"object with ID %d already being deleted",
				*springBootInstance.ID,
			)), objectType)
		} else {
			// object scheduled for deletion and confirmed - it can be deleted
			// from DB
			if err := crdbgorm.ExecuteTx(
				c.Request().Context(), h.Handler.DB, nil,
				func(tx *gorm.DB) error {
					return tx.Scopes(tpapiserver_lib.QueryScopes(c)...).Delete(&springBootInstance).Error
				},
			); err != nil {
				h.Handler.Logger.Error("handler error: error deleting object", zap.Error(err))
				// surface BlockedDeleteError from gorm hook - backstop in case an attached object reference was created after the pre-check
				var blockedErr *tpapi_v0.BlockedDeleteError
				if errors.As(err, &blockedErr) {
					return tphandlers_v0.RespondBlockedDelete(
						c,
						h.Handler.RequestDB(c),
						blockedErr,
					)
				}
				// check if this is a custom HTTP error with specific status code
				var httpErr *tputil_v0.HttpError
				if errors.As(err, &httpErr) {
					return tpapiserver_lib.ResponseStatusErr(
						httpErr.GetStatusCode(), c, nil, err, objectType,
					)
				}
				return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
			}
		}
	}

	response, err := tpapiserver_lib.CreateResponse(
		tpapiserver_lib.SingleObjectMeta(),
		springBootInstance,
		objectType,
	)
	if err != nil {
		h.Handler.Logger.Error("handler error: error creating response", zap.Error(err))
		return tpapiserver_lib.ResponseStatus500(c, nil, err, objectType)
	}

	return tpapiserver_lib.ResponseStatus200(c, *response)
}
