// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	errors "errors"
	"fmt"
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	tpclientlib "github.com/threeport/threeport/pkg/client/lib/v0"
	tpclient_v0 "github.com/threeport/threeport/pkg/client/v0"
	tpconfig_v0 "github.com/threeport/threeport/pkg/config/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
	"strings"

	"k8s.io/apimachinery/pkg/util/validation"
	api_v0 "spring-boot-threeport-module/pkg/api/v0"
	client_v0 "spring-boot-threeport-module/pkg/client/v0"
)

// deletionWaitAttempts and deletionWaitSeconds bound the wait for a deleted
// instance to leave the API. They are variables rather than constants so a test
// can observe a timeout without sitting through a minute of it.
var (
	deletionWaitAttempts = 60
	deletionWaitSeconds  = 1
)

// SpringBootInstanceConfig is a config abstraction for the SpringBootInstance API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type SpringBootInstanceConfig struct {
	SpringBootInstance SpringBootInstanceValues
}

// SpringBootInstanceValues contains all the attributes needed to manage
// the SpringBootInstance API object.
type SpringBootInstanceValues struct {
	Name *string

	// The Kubernetes runtime to deploy to, named rather than referenced by ID.
	// Left unset, the control plane's default runtime is used, so a user with
	// one cluster does not have to name it.
	KubernetesRuntimeInstance *tpconfig_v0.KubernetesRuntimeInstanceValues

	// When a DomainName is in use, the subdomain to reach this instance on.
	SubDomain *string

	SpringBootDefinition *SpringBootDefinitionValues

	Age *string
}

// Get gets spring boot instances from the Threeport API.
// If the name is set in the SpringBootInstanceValues, it will return the spring boot instance with that name.
// If the name is not set, it will return all spring boot instances.
func (s *SpringBootInstanceConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]SpringBootInstanceConfig, error) {
	springBootInstanceValues := s.SpringBootInstance

	// get API objects
	var springBootInstances *[]api_v0.SpringBootInstance
	switch {
	// if name is provided, get spring boot instance by name
	case springBootInstanceValues.Name != nil:
		springBootInstance, err := client_v0.GetSpringBootInstanceByName(apiClient, apiEndpoint, *springBootInstanceValues.Name)
		if err != nil {
			return nil, fmt.Errorf("failed to get spring boot instance with name %s: %w", *springBootInstanceValues.Name, err)
		}
		springBootInstances = &[]api_v0.SpringBootInstance{*springBootInstance}
	// get all spring boot instances
	default:
		allSpringBootInstances, err := client_v0.GetSpringBootInstances(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to get spring boot instances from Threeport API: %w", err)
		}
		springBootInstances = allSpringBootInstances
	}

	// assemble config objects from API objects. Instances commonly share a
	// runtime and a definition, so resolved names are kept rather than fetched
	// again for every row.
	kubernetesRuntimeNames := make(map[uint]*string)
	springBootDefinitionNames := make(map[uint]*string)

	var springBootInstanceConfigs []SpringBootInstanceConfig
	for _, springBootInstance := range *springBootInstances {
		// the runtime and definition are foreign keys on the API object; the
		// config abstraction exists so the user sees names instead
		var kubernetesRuntimeInstanceValues *tpconfig_v0.KubernetesRuntimeInstanceValues
		if springBootInstance.KubernetesRuntimeInstanceID != nil {
			id := *springBootInstance.KubernetesRuntimeInstanceID
			name, cached := kubernetesRuntimeNames[id]
			if !cached {
				kubernetesRuntimeInstance, err := tpclient_v0.GetKubernetesRuntimeInstanceByID(
					apiClient,
					apiEndpoint,
					id,
				)
				if err != nil {
					return nil, fmt.Errorf(
						"failed to get kubernetes runtime instance with ID %d: %w",
						id, err,
					)
				}
				name = kubernetesRuntimeInstance.Name
				kubernetesRuntimeNames[id] = name
			}
			kubernetesRuntimeInstanceValues = &tpconfig_v0.KubernetesRuntimeInstanceValues{Name: name}
		}

		var springBootDefinitionValues *SpringBootDefinitionValues
		if springBootInstance.SpringBootDefinitionID != nil {
			id := *springBootInstance.SpringBootDefinitionID
			name, cached := springBootDefinitionNames[id]
			if !cached {
				springBootDefinition, err := client_v0.GetSpringBootDefinitionByID(
					apiClient,
					apiEndpoint,
					id,
				)
				if err != nil {
					return nil, fmt.Errorf(
						"failed to get spring boot definition with ID %d: %w",
						id, err,
					)
				}
				name = springBootDefinition.Name
				springBootDefinitionNames[id] = name
			}
			springBootDefinitionValues = &SpringBootDefinitionValues{Name: name}
		}

		springBootInstanceConfig := SpringBootInstanceConfig{
			SpringBootInstance: SpringBootInstanceValues{
				Name:                      springBootInstance.Name,
				KubernetesRuntimeInstance: kubernetesRuntimeInstanceValues,
				SubDomain:                 springBootInstance.SubDomain,
				SpringBootDefinition:      springBootDefinitionValues,
				Age:                       util.Ptr(util.GetAgeFormatted(springBootInstance.CreatedAt)),
			},
		}
		springBootInstanceConfigs = append(springBootInstanceConfigs, springBootInstanceConfig)
	}

	return &springBootInstanceConfigs, nil
}

// Create creates a spring boot instance in the Threeport API.
func (s *SpringBootInstanceConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*SpringBootInstanceConfig, error) {
	springBootInstanceValues := s.SpringBootInstance

	// validate config
	if err := s.Validate(); err != nil {
		// see the note in SpringBootDefinitionConfig.Create: a missing name is what
		// Validate reports, so it cannot be read to describe the failure
		return nil, fmt.Errorf("failed to validate values for spring boot instance: %w", err)
	}

	// resolve the runtime and definition the config names into the foreign keys
	// the API object carries
	kubernetesRuntimeInstance, err := getKubernetesRuntimeInstanceByNameOrDefault(
		apiClient,
		apiEndpoint,
		springBootInstanceValues.KubernetesRuntimeInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get kubernetes runtime instance: %w", err)
	}

	springBootDefinition, err := client_v0.GetSpringBootDefinitionByName(
		apiClient,
		apiEndpoint,
		*springBootInstanceValues.SpringBootDefinition.Name,
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to find spring boot definition with name %s: %w",
			*springBootInstanceValues.SpringBootDefinition.Name, err,
		)
	}

	// construct spring boot instance object
	springBootInstance := api_v0.SpringBootInstance{
		Instance: tpapi_v0.Instance{
			Name: springBootInstanceValues.Name,
		},
		KubernetesRuntimeInstanceID: kubernetesRuntimeInstance.ID,
		SubDomain:                   springBootInstanceValues.SubDomain,
		SpringBootDefinitionID:      springBootDefinition.ID,
	}

	// create spring boot instance
	createdSpringBootInstance, err := client_v0.CreateSpringBootInstance(
		apiClient,
		apiEndpoint,
		&springBootInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create spring boot instance in threeport API: %w", err)
	}

	// construct spring boot instance config
	createdSpringBootInstanceConfig := &SpringBootInstanceConfig{
		SpringBootInstance: SpringBootInstanceValues{
			Name: createdSpringBootInstance.Name,
			KubernetesRuntimeInstance: &tpconfig_v0.KubernetesRuntimeInstanceValues{
				Name: kubernetesRuntimeInstance.Name,
			},
			SubDomain:            createdSpringBootInstance.SubDomain,
			SpringBootDefinition: &SpringBootDefinitionValues{Name: springBootDefinition.Name},
			Age:                  util.Ptr(util.GetAgeFormatted(createdSpringBootInstance.CreatedAt)),
		},
	}

	return createdSpringBootInstanceConfig, nil
}

// Replace updates the entire spring boot instance object in the Threeport API.
// This is a full replacement of all fields in the spring boot instance object.
// This function takes a name parameter to identify the spring boot instance to replace.
// This allows a different name to be provided in the values object for name changes.
func (s *SpringBootInstanceConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*SpringBootInstanceConfig, error) {
	springBootInstanceValues := s.SpringBootInstance

	// validate config
	if err := s.Validate(); err != nil {
		return nil, fmt.Errorf("invalid spring boot instance config: %w", err)
	}

	// get existing spring boot instance by name
	existingSpringBootInstance, err := client_v0.GetSpringBootInstanceByName(
		apiClient,
		apiEndpoint,
		name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find spring boot instance with name %s: %w", name, err)
	}

	// resolve the names the config carries into foreign keys. Unlike create,
	// this keeps the runtime the instance is already on rather than falling back
	// to the default, which would move the workload to another cluster on an
	// edit to an unrelated field.
	kubernetesRuntimeInstance, moved, err := getKubernetesRuntimeInstanceForReplace(
		apiClient,
		apiEndpoint,
		springBootInstanceValues.KubernetesRuntimeInstance,
		existingSpringBootInstance.KubernetesRuntimeInstanceID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get kubernetes runtime instance: %w", err)
	}
	if moved {
		return nil, fmt.Errorf(
			"a spring boot instance may not be moved from its current runtime to %s - create a new instance there instead",
			*springBootInstanceValues.KubernetesRuntimeInstance.Name,
		)
	}

	springBootDefinition, err := client_v0.GetSpringBootDefinitionByName(
		apiClient,
		apiEndpoint,
		*springBootInstanceValues.SpringBootDefinition.Name,
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to find spring boot definition with name %s: %w",
			*springBootInstanceValues.SpringBootDefinition.Name, err,
		)
	}

	// construct updated spring boot instance object. This is a full replacement, so
	// every field the user can set is sent rather than merged onto the existing
	// object.
	updatedSpringBootInstance := &api_v0.SpringBootInstance{
		Common: tpapi_v0.Common{
			ID: existingSpringBootInstance.ID,
		},
		Instance: tpapi_v0.Instance{
			Name: springBootInstanceValues.Name,
		},
		KubernetesRuntimeInstanceID: kubernetesRuntimeInstance.ID,
		SubDomain:                   springBootInstanceValues.SubDomain,
		SpringBootDefinitionID:      springBootDefinition.ID,

		// the workload instance is an owned relationship the reconciler sets,
		// not something the user configures. A replacement that left it out
		// would be asking the API to clear it, which it refuses because an owned
		// relationship is immutable once set.
		KubernetesWorkloadInstanceID: existingSpringBootInstance.KubernetesWorkloadInstanceID,
	}

	// replace spring boot instance
	replacedSpringBootInstance, err := client_v0.ReplaceSpringBootInstance(
		apiClient,
		apiEndpoint,
		updatedSpringBootInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace spring boot instance in threeport API: %w", err)
	}

	// construct updated spring boot instance config
	updatedSpringBootInstanceConfig := &SpringBootInstanceConfig{
		SpringBootInstance: SpringBootInstanceValues{
			Name: replacedSpringBootInstance.Name,
			KubernetesRuntimeInstance: &tpconfig_v0.KubernetesRuntimeInstanceValues{
				Name: kubernetesRuntimeInstance.Name,
			},
			SubDomain:            replacedSpringBootInstance.SubDomain,
			SpringBootDefinition: &SpringBootDefinitionValues{Name: springBootDefinition.Name},
			Age:                  util.Ptr(util.GetAgeFormatted(replacedSpringBootInstance.CreatedAt)),
		},
	}

	return updatedSpringBootInstanceConfig, nil
}

// Delete deletes a spring boot instance from the Threeport API.
func (s *SpringBootInstanceConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*SpringBootInstanceConfig, error) {
	springBootInstanceValues := s.SpringBootInstance

	// delete works by name, and unlike create it does not run Validate first,
	// so the name is checked here rather than dereferenced blind
	if springBootInstanceValues.Name == nil {
		return nil, errors.New("missing required field in config: Name")
	}

	// get spring boot instance by name
	springBootInstance, err := client_v0.GetSpringBootInstanceByName(
		apiClient,
		apiEndpoint,
		*springBootInstanceValues.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find spring boot instance with name %s: %w", *springBootInstanceValues.Name, err)
	}

	// delete spring boot instance
	deletedSpringBootInstance, err := client_v0.DeleteSpringBootInstance(
		apiClient,
		apiEndpoint,
		*springBootInstance.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete spring boot instance from Threeport API: %w", err)
	}

	// wait for the spring boot instance to be deleted. The API marks it for deletion
	// and the reconciler tears the workload down before the row goes away, so
	// returning immediately would let a caller deleting a defined instance try
	// to remove the definition while this instance still refers to it - which
	// the API refuses. Threeport's own instance configs wait the same way.
	if err := util.Retry(deletionWaitAttempts, deletionWaitSeconds, func() error {
		_, err := client_v0.GetSpringBootInstanceByName(apiClient, apiEndpoint, *springBootInstanceValues.Name)
		if err == nil {
			return errors.New("spring boot instance not deleted")
		}

		// only an explicit not found proves the row is gone. Any other error is
		// the API failing to answer, which says nothing about the instance, and
		// reading it as success would let a caller delete the definition while
		// this instance still refers to it.
		if errors.Is(err, tpclientlib.ErrObjectNotFound) {
			return nil
		}

		return fmt.Errorf("failed to check whether the spring boot instance is deleted: %w", err)
	}); err != nil {
		return nil, fmt.Errorf(
			"gave up waiting for spring boot instance %s to be deleted: %w",
			*springBootInstanceValues.Name, err,
		)
	}

	// construct deleted spring boot instance config
	deletedSpringBootInstanceConfig := &SpringBootInstanceConfig{
		SpringBootInstance: SpringBootInstanceValues{
			Name: deletedSpringBootInstance.Name,
		},
	}

	return deletedSpringBootInstanceConfig, nil
}

// Validate validates inputs to create spring boot instances.
func (s *SpringBootInstanceConfig) Validate() error {
	springBootInstanceValues := s.SpringBootInstance
	multiError := util.MultiError{}

	// ensure name is set
	if springBootInstanceValues.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: Name"))
	}

	// the instance name becomes the Kubernetes workload instance's name, and
	// Threeport builds the instance's namespace from it. A namespace is a
	// DNS-1123 label, so a name Kubernetes cannot use leaves the workload with
	// nowhere to be placed - reported here rather than when the namespace is
	// created, which is after the instance was accepted.
	if springBootInstanceValues.Name != nil {
		if errs := validation.IsDNS1123Label(*springBootInstanceValues.Name); len(errs) > 0 {
			multiError.AppendError(fmt.Errorf(
				"invalid value in config for Name: %s: %s",
				*springBootInstanceValues.Name, strings.Join(errs, "; "),
			))
		}
	}

	// an instance has nothing to deploy without a definition, and Create
	// dereferences the name to look it up
	if springBootInstanceValues.SpringBootDefinition == nil || springBootInstanceValues.SpringBootDefinition.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: SpringBootDefinition.Name"))
	}

	return multiError.Error()
}
