// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"
	util "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
)

// SpringBootConfig is a container for a SpringBoot which is a config abstraction for
// the SpringBootDefinition and SpringBootInstance API objects.
// This abstraction allows users to manage definitions and instances together with single operations
// rather than separate operations for each API object.
type SpringBootConfig struct {
	SpringBoot SpringBootValues
}

// SpringBootValues contains all the attributes needed to manage the
// SpringBootDefinition and SpringBootInstance API objects
// together with a single operation.
type SpringBootValues struct {
	// TODO: add fields needed for user to manage a SpringBootDefinition and SpringBootInstance together
	Name *string
	Age  *string
}

// Get gets a spring boot definition and instance from the Threeport API.
func (s *SpringBootConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]SpringBootConfig, error) {
	// get operations
	operations, springBootDefinitions, springBootInstances := s.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute get operations
	if err := operations.Get(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute get operations for spring boot defined instances: %w",
			err,
		)
	}

	// assemble the defined instances
	springBootConfigs := mapToSpringBootDefinedInstances(springBootDefinitions, springBootInstances)

	return springBootConfigs, nil
}

// Create creates a spring boot definition and instance in the Threeport API.
func (s *SpringBootConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]SpringBootConfig, error) {
	// get operations
	operations, springBootDefinitions, springBootInstances := s.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute create operations
	if err := operations.Create(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute create operations for spring boot defined instance with name %s: %w",
			*s.SpringBoot.Name,
			err,
		)
	}

	// assemble the defined instances
	springBootConfigs := mapToSpringBootDefinedInstances(springBootDefinitions, springBootInstances)

	return springBootConfigs, nil
}

// Replace replaces a spring boot definition and instance in the Threeport API.
func (s *SpringBootConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*[]SpringBootConfig, error) {
	// get operations
	operations, springBootDefinitions, springBootInstances := s.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute replace operations
	if err := operations.Replace(name); err != nil {
		return nil, fmt.Errorf(
			"failed to execute replace operations for spring boot defined instance with name %s: %w",
			name,
			err,
		)
	}

	// assemble the defined instances
	springBootConfigs := mapToSpringBootDefinedInstances(springBootDefinitions, springBootInstances)

	return springBootConfigs, nil
}

// Delete deletes a spring boot definition and instance from the Threeport API.
func (s *SpringBootConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]SpringBootConfig, error) {
	// get operations
	operations, _, _ := s.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute delete operations
	if err := operations.Delete(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute delete operations for spring boot defined instance with name %s: %w",
			*s.SpringBoot.Name,
			err,
		)
	}

	return nil, nil
}

// GetOperations returns a slice of operations used to get, create, replace or delete
// a spring boot defined instance.
func (s *SpringBootConfig) GetOperations(
	apiClient *http.Client,
	apiEndpoint string,
) (*util.Operations, *[]SpringBootDefinitionConfig, *[]SpringBootInstanceConfig) {
	springBootValues := s.SpringBoot
	var err error
	var operatedSpringBootDefinitions []SpringBootDefinitionConfig
	var operatedSpringBootInstances []SpringBootInstanceConfig

	operations := util.Operations{}

	// add spring boot definition operation
	// TODO: add appropriate fields to definition values object
	springBootDefinitionConfig := SpringBootDefinitionConfig{
		SpringBootDefinition: SpringBootDefinitionValues{
			Age:  springBootValues.Age,
			Name: springBootValues.Name,
		},
	}
	operations.AppendOperation(util.Operation{
		Create: func() error {
			springBootDefinition, err := springBootDefinitionConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to create spring boot definition with name %s: %w", *springBootValues.Name, err)
			}
			operatedSpringBootDefinitions = append(operatedSpringBootDefinitions, *springBootDefinition)
			return nil
		},
		Delete: func() error {
			_, err = springBootDefinitionConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to delete spring boot definition with name %s: %w", *springBootValues.Name, err)
			}
			return nil
		},
		Get: func() error {
			springBootDefinitions, err := springBootDefinitionConfig.Get(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to get spring boot definitions: %w", err)
			}
			operatedSpringBootDefinitions = append(operatedSpringBootDefinitions, *springBootDefinitions...)
			return nil
		},
		Name: "spring boot definition",
		Replace: func(name string) error {
			springBootDefinition, err := springBootDefinitionConfig.Replace(apiClient, apiEndpoint, name)
			if err != nil {
				return fmt.Errorf("failed to replace spring boot definition with name %s: %w", name, err)
			}
			operatedSpringBootDefinitions = append(operatedSpringBootDefinitions, *springBootDefinition)
			return nil
		},
	})

	// add spring boot instance operation
	// TODO: add appropriate fields to instance values object
	springBootInstanceConfig := SpringBootInstanceConfig{
		SpringBootInstance: SpringBootInstanceValues{
			Age:  springBootValues.Age,
			Name: springBootValues.Name,
		},
	}
	operations.AppendOperation(util.Operation{
		Create: func() error {
			springBootInstance, err := springBootInstanceConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to create spring boot instance with name %s: %w", *springBootValues.Name, err)
			}
			operatedSpringBootInstances = append(operatedSpringBootInstances, *springBootInstance)
			return nil
		},
		Delete: func() error {
			_, err = springBootInstanceConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to delete spring boot instance with name %s: %w", *springBootValues.Name, err)
			}
			return nil
		},
		Get: func() error {
			springBootInstances, err := springBootInstanceConfig.Get(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to get spring boot instances: %w", err)
			}
			operatedSpringBootInstances = append(operatedSpringBootInstances, *springBootInstances...)
			return nil
		},
		Name: "spring boot instance",
		Replace: func(name string) error {
			springBootInstance, err := springBootInstanceConfig.Replace(apiClient, apiEndpoint, name)
			if err != nil {
				return fmt.Errorf("failed to replace spring boot instance with name %s: %w", name, err)
			}
			operatedSpringBootInstances = append(operatedSpringBootInstances, *springBootInstance)
			return nil
		},
	})

	return &operations, &operatedSpringBootDefinitions, &operatedSpringBootInstances
}

// mapToSpringBootDefinedInstances maps a slice of spring boot definition and instance configs
// to a slice of spring boot config objects
func mapToSpringBootDefinedInstances(
	springBootDefinitions *[]SpringBootDefinitionConfig,
	springBootInstances *[]SpringBootInstanceConfig,
) *[]SpringBootConfig {
	var springBootConfigs []SpringBootConfig
	for _, inst := range *springBootInstances {
		for _, def := range *springBootDefinitions {
			instName := *inst.SpringBootInstance.Name
			defName := *def.SpringBootDefinition.Name
			// a defined instance must have matching names for definition and instance
			// and the definition must be associated with the instance
			if instName == defName && *inst.SpringBootInstance.SpringBootDefinition.Name == *def.SpringBootDefinition.Name {
				// TODO: add fields needed for user to manage a SpringBootDefinition and SpringBootInstance together
				springBootConfig := SpringBootConfig{
					SpringBoot: SpringBootValues{
						Age:  inst.SpringBootInstance.Age,
						Name: inst.SpringBootInstance.Name,
					},
				}
				springBootConfigs = append(springBootConfigs, springBootConfig)
				// an instance can only have one matching definition for a defined instance
				// we can break out of the loop after finding the first matching definition
				break
			}
		}
	}

	return &springBootConfigs
}
