// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	"fmt"
	tpconfig_v0 "github.com/threeport/threeport/pkg/config/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
)

// SpringBootConfig is a container for a SpringBoot which is a config abstraction for
// the SpringBootDefinition and SpringBootInstance API objects.
// This abstraction allows users to manage definitions and instances together with single operations
// rather than separate operations for each API object.
type SpringBootConfig struct {
	SpringBoot SpringBootValues
}

// SpringBootValues contains all the attributes needed to manage the
// SpringBootDefinition and SpringBootInstance API objects
// together with a single operation.
type SpringBootValues struct {
	// Name is used for both the definition and the instance: a defined instance
	// is the pair that shares a name.
	Name *string

	// definition attributes
	Image       *string
	Profile     *string
	ServerPort  *int
	JavaOpts    *string
	Environment *string
	Replicas    *int
	Database    *string
	HealthPath  *string

	// CPU and memory for the application container, as Kubernetes quantities
	CpuRequest    *string
	CpuLimit      *string
	MemoryRequest *string
	MemoryLimit   *string

	// instance attributes
	KubernetesRuntimeInstance *tpconfig_v0.KubernetesRuntimeInstanceValues
	SubDomain                 *string

	Age *string
}

// Get gets a spring boot definition and instance from the Threeport API.
func (s *SpringBootConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]SpringBootConfig, error) {
	// get operations
	operations, springBootDefinitions, springBootInstances := s.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute get operations
	if err := operations.Get(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute get operations for spring boot defined instances: %w",
			err,
		)
	}

	// assemble the defined instances
	springBootConfigs := mapToSpringBootDefinedInstances(springBootDefinitions, springBootInstances)

	return springBootConfigs, nil
}

// Create creates a spring boot definition and instance in the Threeport API.
func (s *SpringBootConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]SpringBootConfig, error) {
	// get operations
	operations, springBootDefinitions, springBootInstances := s.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute create operations
	if err := operations.Create(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute create operations for spring boot defined instance %s: %w",
			springBootName(s.SpringBoot.Name),
			err,
		)
	}

	// assemble the defined instances
	springBootConfigs := mapToSpringBootDefinedInstances(springBootDefinitions, springBootInstances)

	return springBootConfigs, nil
}

// Replace replaces a spring boot definition and instance in the Threeport API.
func (s *SpringBootConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*[]SpringBootConfig, error) {
	// get operations
	operations, springBootDefinitions, springBootInstances := s.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute replace operations
	if err := operations.Replace(name); err != nil {
		return nil, fmt.Errorf(
			"failed to execute replace operations for spring boot defined instance with name %s: %w",
			name,
			err,
		)
	}

	// assemble the defined instances
	springBootConfigs := mapToSpringBootDefinedInstances(springBootDefinitions, springBootInstances)

	return springBootConfigs, nil
}

// Delete deletes a spring boot definition and instance from the Threeport API.
func (s *SpringBootConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]SpringBootConfig, error) {
	// get operations
	operations, _, _ := s.GetOperations(
		apiClient,
		apiEndpoint,
	)

	// execute delete operations
	if err := operations.Delete(); err != nil {
		return nil, fmt.Errorf(
			"failed to execute delete operations for spring boot defined instance %s: %w",
			springBootName(s.SpringBoot.Name),
			err,
		)
	}

	return nil, nil
}

// springBootName describes a config's name for an error message. Validate reports a
// missing name, and these messages wrap the failure Validate returns, so the
// name has to be readable even when it is the thing that is absent.
func springBootName(name *string) string {
	if name == nil {
		return "with no name"
	}

	return fmt.Sprintf("with name %s", *name)
}

// GetOperations returns a slice of operations used to get, create, replace or delete
// a spring boot defined instance.
func (s *SpringBootConfig) GetOperations(
	apiClient *http.Client,
	apiEndpoint string,
) (*util.Operations, *[]SpringBootDefinitionConfig, *[]SpringBootInstanceConfig) {
	springBootValues := s.SpringBoot
	var err error
	var operatedSpringBootDefinitions []SpringBootDefinitionConfig
	var operatedSpringBootInstances []SpringBootInstanceConfig

	operations := util.Operations{}

	// add spring boot definition operation
	springBootDefinitionConfig := SpringBootDefinitionConfig{
		SpringBootDefinition: SpringBootDefinitionValues{
			Name:          springBootValues.Name,
			Image:         springBootValues.Image,
			Profile:       springBootValues.Profile,
			ServerPort:    springBootValues.ServerPort,
			JavaOpts:      springBootValues.JavaOpts,
			CpuRequest:    springBootValues.CpuRequest,
			CpuLimit:      springBootValues.CpuLimit,
			MemoryRequest: springBootValues.MemoryRequest,
			MemoryLimit:   springBootValues.MemoryLimit,
			Environment:   springBootValues.Environment,
			Replicas:      springBootValues.Replicas,
			Database:      springBootValues.Database,
			HealthPath:    springBootValues.HealthPath,
			Age:           springBootValues.Age,
		},
	}
	operations.AppendOperation(util.Operation{
		Create: func() error {
			springBootDefinition, err := springBootDefinitionConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to create spring boot definition %s: %w", springBootName(springBootValues.Name), err)
			}
			operatedSpringBootDefinitions = append(operatedSpringBootDefinitions, *springBootDefinition)
			return nil
		},
		Delete: func() error {
			_, err = springBootDefinitionConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to delete spring boot definition %s: %w", springBootName(springBootValues.Name), err)
			}
			return nil
		},
		Get: func() error {
			springBootDefinitions, err := springBootDefinitionConfig.Get(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to get spring boot definitions: %w", err)
			}
			operatedSpringBootDefinitions = append(operatedSpringBootDefinitions, *springBootDefinitions...)
			return nil
		},
		Name: "spring boot definition",
		Replace: func(name string) error {
			springBootDefinition, err := springBootDefinitionConfig.Replace(apiClient, apiEndpoint, name)
			if err != nil {
				return fmt.Errorf("failed to replace spring boot definition with name %s: %w", name, err)
			}
			operatedSpringBootDefinitions = append(operatedSpringBootDefinitions, *springBootDefinition)
			return nil
		},
	})

	// add spring boot instance operation. The instance points at the definition the
	// operation above creates, which carries the same name.
	springBootInstanceConfig := SpringBootInstanceConfig{
		SpringBootInstance: SpringBootInstanceValues{
			Name:                      springBootValues.Name,
			KubernetesRuntimeInstance: springBootValues.KubernetesRuntimeInstance,
			SubDomain:                 springBootValues.SubDomain,
			SpringBootDefinition:      &SpringBootDefinitionValues{Name: springBootValues.Name},
			Age:                       springBootValues.Age,
		},
	}
	operations.AppendOperation(util.Operation{
		Create: func() error {
			springBootInstance, err := springBootInstanceConfig.Create(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to create spring boot instance %s: %w", springBootName(springBootValues.Name), err)
			}
			operatedSpringBootInstances = append(operatedSpringBootInstances, *springBootInstance)
			return nil
		},
		Delete: func() error {
			_, err = springBootInstanceConfig.Delete(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to delete spring boot instance %s: %w", springBootName(springBootValues.Name), err)
			}
			return nil
		},
		Get: func() error {
			springBootInstances, err := springBootInstanceConfig.Get(apiClient, apiEndpoint)
			if err != nil {
				return fmt.Errorf("failed to get spring boot instances: %w", err)
			}
			operatedSpringBootInstances = append(operatedSpringBootInstances, *springBootInstances...)
			return nil
		},
		Name: "spring boot instance",
		Replace: func(name string) error {
			springBootInstance, err := springBootInstanceConfig.Replace(apiClient, apiEndpoint, name)
			if err != nil {
				return fmt.Errorf("failed to replace spring boot instance with name %s: %w", name, err)
			}
			operatedSpringBootInstances = append(operatedSpringBootInstances, *springBootInstance)
			return nil
		},
	})

	return &operations, &operatedSpringBootDefinitions, &operatedSpringBootInstances
}

// mapToSpringBootDefinedInstances maps a slice of spring boot definition and instance configs
// to a slice of spring boot config objects
func mapToSpringBootDefinedInstances(
	springBootDefinitions *[]SpringBootDefinitionConfig,
	springBootInstances *[]SpringBootInstanceConfig,
) *[]SpringBootConfig {
	var springBootConfigs []SpringBootConfig
	for _, inst := range *springBootInstances {
		// an instance with no name or no definition is not half of a defined
		// instance, and the comparisons below would dereference nil
		if inst.SpringBootInstance.Name == nil ||
			inst.SpringBootInstance.SpringBootDefinition == nil ||
			inst.SpringBootInstance.SpringBootDefinition.Name == nil {
			continue
		}

		for _, def := range *springBootDefinitions {
			if def.SpringBootDefinition.Name == nil {
				continue
			}
			instName := *inst.SpringBootInstance.Name
			defName := *def.SpringBootDefinition.Name
			// a defined instance must have matching names for definition and instance
			// and the definition must be associated with the instance
			if instName == defName && *inst.SpringBootInstance.SpringBootDefinition.Name == *def.SpringBootDefinition.Name {
				springBootConfig := SpringBootConfig{
					SpringBoot: SpringBootValues{
						Name:                      inst.SpringBootInstance.Name,
						Image:                     def.SpringBootDefinition.Image,
						Profile:                   def.SpringBootDefinition.Profile,
						ServerPort:                def.SpringBootDefinition.ServerPort,
						JavaOpts:                  def.SpringBootDefinition.JavaOpts,
						CpuRequest:                def.SpringBootDefinition.CpuRequest,
						CpuLimit:                  def.SpringBootDefinition.CpuLimit,
						MemoryRequest:             def.SpringBootDefinition.MemoryRequest,
						MemoryLimit:               def.SpringBootDefinition.MemoryLimit,
						Environment:               def.SpringBootDefinition.Environment,
						Replicas:                  def.SpringBootDefinition.Replicas,
						Database:                  def.SpringBootDefinition.Database,
						HealthPath:                def.SpringBootDefinition.HealthPath,
						KubernetesRuntimeInstance: inst.SpringBootInstance.KubernetesRuntimeInstance,
						SubDomain:                 inst.SpringBootInstance.SubDomain,
						Age:                       inst.SpringBootInstance.Age,
					},
				}
				springBootConfigs = append(springBootConfigs, springBootConfig)
				// an instance can only have one matching definition for a defined instance
				// we can break out of the loop after finding the first matching definition
				break
			}
		}
	}

	return &springBootConfigs
}
