// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	errors "errors"
	"fmt"
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
	api_v0 "spring-boot-threeport-module/pkg/api/v0"
	client_v0 "spring-boot-threeport-module/pkg/client/v0"
)

// SpringBootInstanceConfig is a config abstraction for the SpringBootInstance API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type SpringBootInstanceConfig struct {
	SpringBootInstance SpringBootInstanceValues
}

// SpringBootInstanceValues contains all the attributes needed to manage
// the SpringBootInstance API object.
type SpringBootInstanceValues struct {
	// TODO: add config abstraction fields needed for user to manage a SpringBootInstance
	Name                 *string
	SpringBootDefinition *SpringBootDefinitionValues
	Age                  *string
}

// Get gets spring boot instances from the Threeport API.
// If the name is set in the SpringBootInstanceValues, it will return the spring boot instance with that name.
// If the name is not set, it will return all spring boot instances.
func (s *SpringBootInstanceConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]SpringBootInstanceConfig, error) {
	springBootInstanceValues := s.SpringBootInstance

	// get API objects
	var springBootInstances *[]api_v0.SpringBootInstance
	switch {
	// if name is provided, get spring boot instance by name
	case springBootInstanceValues.Name != nil:
		springBootInstance, err := client_v0.GetSpringBootInstanceByName(apiClient, apiEndpoint, *springBootInstanceValues.Name)
		if err != nil {
			return nil, fmt.Errorf("failed to get spring boot instance with name %s: %w", *springBootInstanceValues.Name, err)
		}
		springBootInstances = &[]api_v0.SpringBootInstance{*springBootInstance}
	// get all spring boot instances
	default:
		allSpringBootInstances, err := client_v0.GetSpringBootInstances(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to get spring boot instances from Threeport API: %w", err)
		}
		springBootInstances = allSpringBootInstances
	}

	// assemble config objects from API objects
	var springBootInstanceConfigs []SpringBootInstanceConfig
	for _, springBootInstance := range *springBootInstances {
		// TODO: add config abstraction fields needed for user to manage a SpringBootInstance
		springBootInstanceConfig := SpringBootInstanceConfig{
			SpringBootInstance: SpringBootInstanceValues{
				Age:  util.Ptr(util.GetAgeFormatted(springBootInstance.CreatedAt)),
				Name: springBootInstance.Name,
			},
		}
		springBootInstanceConfigs = append(springBootInstanceConfigs, springBootInstanceConfig)
	}

	return &springBootInstanceConfigs, nil
}

// Create creates a spring boot instance in the Threeport API.
func (s *SpringBootInstanceConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*SpringBootInstanceConfig, error) {
	springBootInstanceValues := s.SpringBootInstance

	// validate config
	if err := s.Validate(); err != nil {
		return nil, fmt.Errorf("failed to validate values for spring boot instance with name %s: %w", *springBootInstanceValues.Name, err)
	}

	// construct spring boot instance object
	// TODO: add API object fields as needed for SpringBootInstance
	springBootInstance := api_v0.SpringBootInstance{
		Instance: tpapi_v0.Instance{
			Name: springBootInstanceValues.Name,
		},
	}

	// create spring boot instance
	createdSpringBootInstance, err := client_v0.CreateSpringBootInstance(
		apiClient,
		apiEndpoint,
		&springBootInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create spring boot instance in threeport API: %w", err)
	}

	// construct spring boot instance config
	// TODO: add config abstraction fields needed for user to manage a SpringBootInstance
	createdSpringBootInstanceConfig := &SpringBootInstanceConfig{
		SpringBootInstance: SpringBootInstanceValues{
			Age:  util.Ptr(util.GetAgeFormatted(createdSpringBootInstance.CreatedAt)),
			Name: createdSpringBootInstance.Name,
		},
	}

	return createdSpringBootInstanceConfig, nil
}

// Replace updates the entire spring boot instance object in the Threeport API.
// This is a full replacement of all fields in the spring boot instance object.
// This function takes a name parameter to identify the spring boot instance to replace.
// This allows a different name to be provided in the values object for name changes.
func (s *SpringBootInstanceConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*SpringBootInstanceConfig, error) {
	springBootInstanceValues := s.SpringBootInstance

	// validate config
	if err := s.Validate(); err != nil {
		return nil, fmt.Errorf("invalid spring boot instance config: %w", err)
	}

	// get existing spring boot instance by name
	existingSpringBootInstance, err := client_v0.GetSpringBootInstanceByName(
		apiClient,
		apiEndpoint,
		name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find spring boot instance with name %s: %w", name, err)
	}

	// construct updated spring boot instance object
	// TODO: add API object fields as needed for SpringBootInstance
	updatedSpringBootInstance := &api_v0.SpringBootInstance{
		Common: tpapi_v0.Common{
			ID: existingSpringBootInstance.ID,
		},
		Instance: tpapi_v0.Instance{
			Name: springBootInstanceValues.Name,
		},
	}

	// replace spring boot instance
	replacedSpringBootInstance, err := client_v0.ReplaceSpringBootInstance(
		apiClient,
		apiEndpoint,
		updatedSpringBootInstance,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace spring boot instance in threeport API: %w", err)
	}

	// construct updated spring boot instance config
	// TODO: add config abstraction fields needed for user to manage a SpringBootInstance
	updatedSpringBootInstanceConfig := &SpringBootInstanceConfig{
		SpringBootInstance: SpringBootInstanceValues{
			Age:  util.Ptr(util.GetAgeFormatted(replacedSpringBootInstance.CreatedAt)),
			Name: replacedSpringBootInstance.Name,
		},
	}

	return updatedSpringBootInstanceConfig, nil
}

// Delete deletes a spring boot instance from the Threeport API.
func (s *SpringBootInstanceConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*SpringBootInstanceConfig, error) {
	springBootInstanceValues := s.SpringBootInstance

	// get spring boot instance by name
	springBootInstance, err := client_v0.GetSpringBootInstanceByName(
		apiClient,
		apiEndpoint,
		*springBootInstanceValues.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find spring boot instance with name %s: %w", *springBootInstanceValues.Name, err)
	}

	// delete spring boot instance
	deletedSpringBootInstance, err := client_v0.DeleteSpringBootInstance(
		apiClient,
		apiEndpoint,
		*springBootInstance.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete spring boot instance from Threeport API: %w", err)
	}

	// construct deleted spring boot instance config
	// TODO: add config abstraction fields needed for user to manage a SpringBootInstance
	deletedSpringBootInstanceConfig := &SpringBootInstanceConfig{
		SpringBootInstance: SpringBootInstanceValues{
			Name: deletedSpringBootInstance.Name,
		},
	}

	return deletedSpringBootInstanceConfig, nil
}

// Validate validates inputs to create spring boot instances.
func (s *SpringBootInstanceConfig) Validate() error {
	springBootInstanceValues := s.SpringBootInstance
	multiError := util.MultiError{}

	// ensure name is set
	if springBootInstanceValues.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: Name"))
	}

	// TODO: add additional validation as needed

	return multiError.Error()
}
