// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	errors "errors"
	"fmt"
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"k8s.io/apimachinery/pkg/util/validation"
	"net/http"
	api_v0 "spring-boot-threeport-module/pkg/api/v0"
	client_v0 "spring-boot-threeport-module/pkg/client/v0"
	"strings"
)

// SpringBootDefinitionConfig is a config abstraction for the SpringBootDefinition API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type SpringBootDefinitionConfig struct {
	SpringBootDefinition SpringBootDefinitionValues
}

// SpringBootDefinitionValues contains all the attributes needed to manage
// the SpringBootDefinition API object.
type SpringBootDefinitionValues struct {
	Name *string

	// The container image for the Spring Boot application. Required: a Spring
	// Boot project is packaged as a jar it builds itself, so there is no
	// canonical public image and the module cannot deploy anything without one.
	Image *string

	// The value for SPRING_PROFILES_ACTIVE, e.g. postgres,prod. Spring reads it
	// as a comma separated list and the module does not interpret it.
	Profile *string

	// The port the application serves on. Left unset, the API defaults it to
	// 8080, which is what Spring Boot serves on unless the project changed
	// server.port.
	ServerPort *int

	// Options passed to the JVM through JAVA_TOOL_OPTIONS, e.g. -Xmx512m.
	JavaOpts *string

	// The environment the definition is deployed for. It becomes a Kubernetes
	// label and picks the replica and storage defaults; only "prod" is
	// special-cased, anything else gets the development sizing.
	Environment *string

	// The number of application pods. Left unset, the environment decides.
	Replicas *int

	// The database to deploy alongside the application: none or postgres. Left
	// unset, the API defaults it to none, because a Spring Boot application can
	// run on an embedded database and most do in development.
	Database *string

	// The HTTP path the probes ask for. Left unset, the API defaults it to
	// Spring Boot Actuator's health endpoint. An image without the actuator has
	// to point this somewhere that answers.
	HealthPath *string

	Age *string
}

// Get gets spring boot definitions from the Threeport API.
// If the name is set in the SpringBootDefinitionValues, it will return the spring boot definition with that name.
// If the name is not set, it will return all spring boot definitions.
func (s *SpringBootDefinitionConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]SpringBootDefinitionConfig, error) {
	springBootDefinitionValues := s.SpringBootDefinition

	// get API objects
	var springBootDefinitions *[]api_v0.SpringBootDefinition
	switch {
	// if name is provided, get spring boot definition by name
	case springBootDefinitionValues.Name != nil:
		springBootDefinition, err := client_v0.GetSpringBootDefinitionByName(apiClient, apiEndpoint, *springBootDefinitionValues.Name)
		if err != nil {
			return nil, fmt.Errorf("failed to get spring boot definition with name %s: %w", *springBootDefinitionValues.Name, err)
		}
		springBootDefinitions = &[]api_v0.SpringBootDefinition{*springBootDefinition}
	// get all spring boot definitions
	default:
		allSpringBootDefinitions, err := client_v0.GetSpringBootDefinitions(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to get spring boot definitions from Threeport API: %w", err)
		}
		springBootDefinitions = allSpringBootDefinitions
	}

	// assemble config objects from API objects
	var springBootDefinitionConfigs []SpringBootDefinitionConfig
	for _, springBootDefinition := range *springBootDefinitions {
		springBootDefinitionConfig := SpringBootDefinitionConfig{
			SpringBootDefinition: SpringBootDefinitionValues{
				Name:        springBootDefinition.Name,
				Image:       springBootDefinition.Image,
				Profile:     springBootDefinition.Profile,
				ServerPort:  springBootDefinition.ServerPort,
				JavaOpts:    springBootDefinition.JavaOpts,
				Environment: springBootDefinition.Environment,
				Replicas:    springBootDefinition.Replicas,
				Database:    springBootDefinition.Database,
				HealthPath:  springBootDefinition.HealthPath,
				Age:         util.Ptr(util.GetAgeFormatted(springBootDefinition.CreatedAt)),
			},
		}
		springBootDefinitionConfigs = append(springBootDefinitionConfigs, springBootDefinitionConfig)
	}

	return &springBootDefinitionConfigs, nil
}

// Create creates a spring boot definition in the Threeport API.
func (s *SpringBootDefinitionConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*SpringBootDefinitionConfig, error) {
	springBootDefinitionValues := s.SpringBootDefinition

	// validate config
	if err := s.Validate(); err != nil {
		// the name is not interpolated here: a missing name is one of the things
		// Validate reports, so reading it to describe the failure would panic on
		// exactly the config this line exists to explain
		return nil, fmt.Errorf("failed to validate values for spring boot definition: %w", err)
	}

	// construct spring boot definition object. Optional fields are passed through as
	// they arrive, including nil: the API applies its own defaults for
	// Environment, ServerPort, Database and HealthPath, and repeating them here
	// would mean two places to change when one of them moves.
	springBootDefinition := api_v0.SpringBootDefinition{
		Definition: tpapi_v0.Definition{
			Name: springBootDefinitionValues.Name,
		},
		Image:       springBootDefinitionValues.Image,
		Profile:     springBootDefinitionValues.Profile,
		ServerPort:  springBootDefinitionValues.ServerPort,
		JavaOpts:    springBootDefinitionValues.JavaOpts,
		Environment: springBootDefinitionValues.Environment,
		Replicas:    springBootDefinitionValues.Replicas,
		Database:    springBootDefinitionValues.Database,
		HealthPath:  springBootDefinitionValues.HealthPath,
	}

	// create spring boot definition
	createdSpringBootDefinition, err := client_v0.CreateSpringBootDefinition(
		apiClient,
		apiEndpoint,
		&springBootDefinition,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create spring boot definition in threeport API: %w", err)
	}

	// construct spring boot definition config
	createdSpringBootDefinitionConfig := &SpringBootDefinitionConfig{
		SpringBootDefinition: SpringBootDefinitionValues{
			Name:        createdSpringBootDefinition.Name,
			Image:       createdSpringBootDefinition.Image,
			Profile:     createdSpringBootDefinition.Profile,
			ServerPort:  createdSpringBootDefinition.ServerPort,
			JavaOpts:    createdSpringBootDefinition.JavaOpts,
			Environment: createdSpringBootDefinition.Environment,
			Replicas:    createdSpringBootDefinition.Replicas,
			Database:    createdSpringBootDefinition.Database,
			HealthPath:  createdSpringBootDefinition.HealthPath,
			Age:         util.Ptr(util.GetAgeFormatted(createdSpringBootDefinition.CreatedAt)),
		},
	}

	return createdSpringBootDefinitionConfig, nil
}

// Replace updates the entire spring boot definition object in the Threeport API.
// This is a full replacement of all fields in the spring boot definition object.
// This function takes a name parameter to identify the spring boot definition to replace.
// This allows a different name to be provided in the values object for name changes.
func (s *SpringBootDefinitionConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*SpringBootDefinitionConfig, error) {
	springBootDefinitionValues := s.SpringBootDefinition

	// validate config
	if err := s.Validate(); err != nil {
		return nil, fmt.Errorf("invalid spring boot definition config: %w", err)
	}

	// get existing spring boot definition by name
	existingSpringBootDefinition, err := client_v0.GetSpringBootDefinitionByName(
		apiClient,
		apiEndpoint,
		name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find spring boot definition with name %s: %w", name, err)
	}

	// construct updated spring boot definition object. This is a full replacement, so
	// every field the user can set is sent: a field left out of the config is
	// meant to be cleared, not carried over from the existing object.
	updatedSpringBootDefinition := &api_v0.SpringBootDefinition{
		Common: tpapi_v0.Common{
			ID: existingSpringBootDefinition.ID,
		},
		Definition: tpapi_v0.Definition{
			Name: springBootDefinitionValues.Name,
		},
		Image:       springBootDefinitionValues.Image,
		Profile:     springBootDefinitionValues.Profile,
		ServerPort:  springBootDefinitionValues.ServerPort,
		JavaOpts:    springBootDefinitionValues.JavaOpts,
		Environment: springBootDefinitionValues.Environment,
		Replicas:    springBootDefinitionValues.Replicas,
		Database:    springBootDefinitionValues.Database,
		HealthPath:  springBootDefinitionValues.HealthPath,

		// the workload definition is an owned relationship the reconciler sets,
		// not something the user configures. A replacement that left it out
		// would be asking the API to clear it, which it refuses because an owned
		// relationship is immutable once set.
		KubernetesWorkloadDefinitionID: existingSpringBootDefinition.KubernetesWorkloadDefinitionID,
	}

	// replace spring boot definition
	replacedSpringBootDefinition, err := client_v0.ReplaceSpringBootDefinition(
		apiClient,
		apiEndpoint,
		updatedSpringBootDefinition,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace spring boot definition in threeport API: %w", err)
	}

	// construct updated spring boot definition config
	updatedSpringBootDefinitionConfig := &SpringBootDefinitionConfig{
		SpringBootDefinition: SpringBootDefinitionValues{
			Name:        replacedSpringBootDefinition.Name,
			Image:       replacedSpringBootDefinition.Image,
			Profile:     replacedSpringBootDefinition.Profile,
			ServerPort:  replacedSpringBootDefinition.ServerPort,
			JavaOpts:    replacedSpringBootDefinition.JavaOpts,
			Environment: replacedSpringBootDefinition.Environment,
			Replicas:    replacedSpringBootDefinition.Replicas,
			Database:    replacedSpringBootDefinition.Database,
			HealthPath:  replacedSpringBootDefinition.HealthPath,
			Age:         util.Ptr(util.GetAgeFormatted(replacedSpringBootDefinition.CreatedAt)),
		},
	}

	return updatedSpringBootDefinitionConfig, nil
}

// Delete deletes a spring boot definition from the Threeport API.
func (s *SpringBootDefinitionConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*SpringBootDefinitionConfig, error) {
	springBootDefinitionValues := s.SpringBootDefinition

	// delete works by name, and unlike create it does not run Validate first,
	// so the name is checked here rather than dereferenced blind
	if springBootDefinitionValues.Name == nil {
		return nil, errors.New("missing required field in config: Name")
	}

	// get spring boot definition by name
	springBootDefinition, err := client_v0.GetSpringBootDefinitionByName(
		apiClient,
		apiEndpoint,
		*springBootDefinitionValues.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find spring boot definition with name %s: %w", *springBootDefinitionValues.Name, err)
	}

	// delete spring boot definition
	deletedSpringBootDefinition, err := client_v0.DeleteSpringBootDefinition(
		apiClient,
		apiEndpoint,
		*springBootDefinition.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete spring boot definition from Threeport API: %w", err)
	}

	// construct deleted spring boot definition config
	deletedSpringBootDefinitionConfig := &SpringBootDefinitionConfig{
		SpringBootDefinition: SpringBootDefinitionValues{
			Name: deletedSpringBootDefinition.Name,
		},
	}

	return deletedSpringBootDefinitionConfig, nil
}

// Validate validates inputs to create spring boot definitions.
func (s *SpringBootDefinitionConfig) Validate() error {
	springBootDefinitionValues := s.SpringBootDefinition
	multiError := util.MultiError{}

	// ensure name is set
	if springBootDefinitionValues.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: Name"))
	}

	// the name is the app.kubernetes.io/instance label on every object the
	// module renders, and also the prefix of the resource names, so it is
	// subject to the same late failure the environment check prevents
	if springBootDefinitionValues.Name != nil {
		if errs := validation.IsValidLabelValue(*springBootDefinitionValues.Name); len(errs) > 0 {
			multiError.AppendError(fmt.Errorf(
				"invalid value in config for Name: %s: %s",
				*springBootDefinitionValues.Name, strings.Join(errs, "; "),
			))
		}
	}

	// the API rejects a definition without an image, but it does so with a
	// database constraint error rather than something a user can act on
	if springBootDefinitionValues.Image == nil {
		multiError.AppendError(errors.New("missing required field in config: Image"))
	}

	// the environment becomes a Kubernetes label value. An invalid one is not
	// rejected until Threeport tries to apply the manifest, well after the
	// definition was accepted, so it is caught here instead.
	if springBootDefinitionValues.Environment != nil {
		if errs := validation.IsValidLabelValue(*springBootDefinitionValues.Environment); len(errs) > 0 {
			multiError.AppendError(fmt.Errorf(
				"invalid value in config for Environment: %s: %s",
				*springBootDefinitionValues.Environment, strings.Join(errs, "; "),
			))
		}
	}

	// a negative replica count is rejected by the kube API for the same reason,
	// and just as late
	if springBootDefinitionValues.Replicas != nil && *springBootDefinitionValues.Replicas < 0 {
		multiError.AppendError(fmt.Errorf(
			"invalid value in config for Replicas: %d: must not be negative",
			*springBootDefinitionValues.Replicas,
		))
	}

	// a port outside the range is rejected by the kube API, again only once the
	// manifest is applied
	if springBootDefinitionValues.ServerPort != nil {
		port := *springBootDefinitionValues.ServerPort
		if port < 1 || port > 65535 {
			multiError.AppendError(fmt.Errorf(
				"invalid value in config for ServerPort: %d: must be between 1 and 65535",
				port,
			))
		}
	}

	// an unrecognised database is the one invalid value nothing downstream
	// rejects: the manifest deploys PostgreSQL only for "postgres" and renders
	// an application with no database for anything else, so a typo such as
	// "postgresql" would deploy successfully and leave the application without
	// the database the user asked for.
	if springBootDefinitionValues.Database != nil {
		switch *springBootDefinitionValues.Database {
		case api_v0.DatabaseNone, api_v0.DatabasePostgres:
		default:
			multiError.AppendError(fmt.Errorf(
				"invalid value in config for Database: %s: must be %s or %s",
				*springBootDefinitionValues.Database,
				api_v0.DatabaseNone, api_v0.DatabasePostgres,
			))
		}
	}

	// the probes ask for this path over HTTP. A value without a leading slash
	// is rejected by the kube API when the manifest is applied, which is well
	// after the definition was accepted.
	if springBootDefinitionValues.HealthPath != nil &&
		!strings.HasPrefix(*springBootDefinitionValues.HealthPath, "/") {
		multiError.AppendError(fmt.Errorf(
			"invalid value in config for HealthPath: %s: must start with /",
			*springBootDefinitionValues.HealthPath,
		))
	}

	return multiError.Error()
}
