// scaffolding generated by 'threeport-sdk gen' but will not be regenerated - intended for modification

package v0

import (
	errors "errors"
	"fmt"
	tpapi_v0 "github.com/threeport/threeport/pkg/api/v0"
	util "github.com/threeport/threeport/pkg/util/v0"
	"net/http"
	api_v0 "spring-boot-threeport-module/pkg/api/v0"
	client_v0 "spring-boot-threeport-module/pkg/client/v0"
)

// SpringBootDefinitionConfig is a config abstraction for the SpringBootDefinition API object.
// This abstraction allows users to manage API objects with a simplified set of attributes
// and remove the need for users to interract with API object details such as unique IDs
// and foreign keys.
type SpringBootDefinitionConfig struct {
	SpringBootDefinition SpringBootDefinitionValues
}

// SpringBootDefinitionValues contains all the attributes needed to manage
// the SpringBootDefinition API object.
type SpringBootDefinitionValues struct {
	// TODO: add config abstraction fields needed for user to manage a SpringBootDefinition
	Name *string
	Age  *string
}

// Get gets spring boot definitions from the Threeport API.
// If the name is set in the SpringBootDefinitionValues, it will return the spring boot definition with that name.
// If the name is not set, it will return all spring boot definitions.
func (s *SpringBootDefinitionConfig) Get(
	apiClient *http.Client,
	apiEndpoint string,
) (*[]SpringBootDefinitionConfig, error) {
	springBootDefinitionValues := s.SpringBootDefinition

	// get API objects
	var springBootDefinitions *[]api_v0.SpringBootDefinition
	switch {
	// if name is provided, get spring boot definition by name
	case springBootDefinitionValues.Name != nil:
		springBootDefinition, err := client_v0.GetSpringBootDefinitionByName(apiClient, apiEndpoint, *springBootDefinitionValues.Name)
		if err != nil {
			return nil, fmt.Errorf("failed to get spring boot definition with name %s: %w", *springBootDefinitionValues.Name, err)
		}
		springBootDefinitions = &[]api_v0.SpringBootDefinition{*springBootDefinition}
	// get all spring boot definitions
	default:
		allSpringBootDefinitions, err := client_v0.GetSpringBootDefinitions(apiClient, apiEndpoint)
		if err != nil {
			return nil, fmt.Errorf("failed to get spring boot definitions from Threeport API: %w", err)
		}
		springBootDefinitions = allSpringBootDefinitions
	}

	// assemble config objects from API objects
	var springBootDefinitionConfigs []SpringBootDefinitionConfig
	for _, springBootDefinition := range *springBootDefinitions {
		// TODO: add config abstraction fields needed for user to manage a SpringBootDefinition
		springBootDefinitionConfig := SpringBootDefinitionConfig{
			SpringBootDefinition: SpringBootDefinitionValues{
				Age:  util.Ptr(util.GetAgeFormatted(springBootDefinition.CreatedAt)),
				Name: springBootDefinition.Name,
			},
		}
		springBootDefinitionConfigs = append(springBootDefinitionConfigs, springBootDefinitionConfig)
	}

	return &springBootDefinitionConfigs, nil
}

// Create creates a spring boot definition in the Threeport API.
func (s *SpringBootDefinitionConfig) Create(
	apiClient *http.Client,
	apiEndpoint string,
) (*SpringBootDefinitionConfig, error) {
	springBootDefinitionValues := s.SpringBootDefinition

	// validate config
	if err := s.Validate(); err != nil {
		return nil, fmt.Errorf("failed to validate values for spring boot definition with name %s: %w", *springBootDefinitionValues.Name, err)
	}

	// construct spring boot definition object
	// TODO: add API object fields as needed for SpringBootDefinition
	springBootDefinition := api_v0.SpringBootDefinition{
		Definition: tpapi_v0.Definition{
			Name: springBootDefinitionValues.Name,
		},
	}

	// create spring boot definition
	createdSpringBootDefinition, err := client_v0.CreateSpringBootDefinition(
		apiClient,
		apiEndpoint,
		&springBootDefinition,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create spring boot definition in threeport API: %w", err)
	}

	// construct spring boot definition config
	// TODO: add config abstraction fields needed for user to manage a SpringBootDefinition
	createdSpringBootDefinitionConfig := &SpringBootDefinitionConfig{
		SpringBootDefinition: SpringBootDefinitionValues{
			Age:  util.Ptr(util.GetAgeFormatted(createdSpringBootDefinition.CreatedAt)),
			Name: createdSpringBootDefinition.Name,
		},
	}

	return createdSpringBootDefinitionConfig, nil
}

// Replace updates the entire spring boot definition object in the Threeport API.
// This is a full replacement of all fields in the spring boot definition object.
// This function takes a name parameter to identify the spring boot definition to replace.
// This allows a different name to be provided in the values object for name changes.
func (s *SpringBootDefinitionConfig) Replace(
	apiClient *http.Client,
	apiEndpoint string,
	name string,
) (*SpringBootDefinitionConfig, error) {
	springBootDefinitionValues := s.SpringBootDefinition

	// validate config
	if err := s.Validate(); err != nil {
		return nil, fmt.Errorf("invalid spring boot definition config: %w", err)
	}

	// get existing spring boot definition by name
	existingSpringBootDefinition, err := client_v0.GetSpringBootDefinitionByName(
		apiClient,
		apiEndpoint,
		name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find spring boot definition with name %s: %w", name, err)
	}

	// construct updated spring boot definition object
	// TODO: add API object fields as needed for SpringBootDefinition
	updatedSpringBootDefinition := &api_v0.SpringBootDefinition{
		Common: tpapi_v0.Common{
			ID: existingSpringBootDefinition.ID,
		},
		Definition: tpapi_v0.Definition{
			Name: springBootDefinitionValues.Name,
		},
	}

	// replace spring boot definition
	replacedSpringBootDefinition, err := client_v0.ReplaceSpringBootDefinition(
		apiClient,
		apiEndpoint,
		updatedSpringBootDefinition,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to replace spring boot definition in threeport API: %w", err)
	}

	// construct updated spring boot definition config
	// TODO: add config abstraction fields needed for user to manage a SpringBootDefinition
	updatedSpringBootDefinitionConfig := &SpringBootDefinitionConfig{
		SpringBootDefinition: SpringBootDefinitionValues{
			Age:  util.Ptr(util.GetAgeFormatted(replacedSpringBootDefinition.CreatedAt)),
			Name: replacedSpringBootDefinition.Name,
		},
	}

	return updatedSpringBootDefinitionConfig, nil
}

// Delete deletes a spring boot definition from the Threeport API.
func (s *SpringBootDefinitionConfig) Delete(
	apiClient *http.Client,
	apiEndpoint string,
) (*SpringBootDefinitionConfig, error) {
	springBootDefinitionValues := s.SpringBootDefinition

	// get spring boot definition by name
	springBootDefinition, err := client_v0.GetSpringBootDefinitionByName(
		apiClient,
		apiEndpoint,
		*springBootDefinitionValues.Name,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to find spring boot definition with name %s: %w", *springBootDefinitionValues.Name, err)
	}

	// delete spring boot definition
	deletedSpringBootDefinition, err := client_v0.DeleteSpringBootDefinition(
		apiClient,
		apiEndpoint,
		*springBootDefinition.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete spring boot definition from Threeport API: %w", err)
	}

	// construct deleted spring boot definition config
	// TODO: add config abstraction fields needed for user to manage a SpringBootDefinition
	deletedSpringBootDefinitionConfig := &SpringBootDefinitionConfig{
		SpringBootDefinition: SpringBootDefinitionValues{
			Name: deletedSpringBootDefinition.Name,
		},
	}

	return deletedSpringBootDefinitionConfig, nil
}

// Validate validates inputs to create spring boot definitions.
func (s *SpringBootDefinitionConfig) Validate() error {
	springBootDefinitionValues := s.SpringBootDefinition
	multiError := util.MultiError{}

	// ensure name is set
	if springBootDefinitionValues.Name == nil {
		multiError.AppendError(errors.New("missing required field in config: Name"))
	}

	// TODO: add additional validation as needed

	return multiError.Error()
}
